### ISSUE TITLE
Recent versions will consider implementing filter functions, such as Threshold, Sharpen, Sobel?

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneTools#1011]
Recent versions will consider implementing filter functions, such as Threshold, Sharpen, Sobel?

**Comment by dannyrb** [comment]
Can you explain further or provide examples?

**Comment by chenxxcc** [comment]
> Can you explain further or provide examples?
Thank you for your reply!
Filter in Toolbox [https://ivmartel.github.io/dwv-jqui/](https://ivmartel.github.io/dwv-jqui/)

**Comment by dannyrb** [comment]
@chenxxcc, what are these filter functions used for? Do you have any recommendations around how/where these should be implemented?

**Comment by chenxxcc** [comment]
> @chenxxcc, what are these filter functions used for? Do you have any recommendations around how/where these should be implemented?

According to the teacher's description, I think it's a function similar to a filter, roughly the original image has some similar black shops, after sharpening or saturation adjustment, you can easily find the focus.I took two pictures at the scene.
#### Before image processing:
![img1](https://s2.ax1x.com/2019/07/22/eicGQK.jpg)
#### After image processing
![img2](https://s2.ax1x.com/2019/07/22/eicyy8.md.jpg)

**Comment by chenxxcc** [comment]
I also learned about similar image processing examples in GitHub.
[http://brucealm1ghty.github.io/](http://brucealm1ghty.github.io/)

**Comment by swederik** [comment]
You can do this using custom Web Workers in WADO Image Loader:
https://github.com/cornerstonejs/cornerstoneWADOImageLoader

Here's an example that does Sharpen, Emboss, etc:

https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/customWebWorkerTask/index.html

**Comment by chenxxcc** [comment]
My God, I did ignore this library, which I used in my project, but I didn't read the examples myself. I'm sorry. Thank you for your reply.

**Comment by dannyrb** [comment]
I think this was resolved, so I'm going to close this issue for now. I do think that we could make functionality like this easier to use/add, and provide better documentation. I too would have assumed that, if it existed, you would have found information on it in this repository.
