### ISSUE TITLE
How to remove all lines on an element

### ISSUE THREAD

**Issue by unosbaghaie** [cornerstonejs/cornerstoneTools#1013]
How can I remove all lines on an element? (v3)

**Comment by dannyrb** [comment]
Can you provide a better example of the problem you're facing and what you've tried so far?

**Comment by unosbaghaie** [comment]
for example I have used the Length tool and draw some lines on the enabled element. Now I want to remove all those lines at once.

![lines](https://user-images.githubusercontent.com/14114058/61369615-b7e7c200-a8a5-11e9-8bc7-9b96f9185b76.png)

**Comment by jlopes90** [comment]
```
cornerstoneTools.removeToolForElement(element, 'Length')
cornerstone.updateImage(element)
```

**Comment by dannyrb** [comment]
I think the toolState would still exist in that instance, but the tool that renders it would be gone.

You could also clear that tool's state for that image with [`removeToolState`](https://tools.cornerstonejs.org/api/#removeToolState)

**Comment by jlopes90** [comment]
It is

`cornerstoneTools.clearToolState(element, toolName);`

**Comment by dannyrb** [comment]
@all-contributers, please add @jlopes90 for answering questions

**Comment by dannyrb** [comment]
@all-contributors, please add @jlopes90 for answering questions

**Comment by FMCalisto** [comment]
If you want to know more about how the CornerstoneJS tool states are stored and how to use the `cornerstoneTools.clearToolState()` function, you can follow the link to the StackOverflow answer you provided:

https://stackoverflow.com/a/73204850/2371987
