### ISSUE TITLE
cornerstoneTools.init() returns undefined

### ISSUE THREAD

**Issue by TheHidden1** [cornerstonejs/cornerstoneTools#1019]
Hello !

I am trying to create an angular application using cornerstone and cornerstoneTools
and i am facing  an issue when initializing corenerstonetools : 
the cornerstoneTools.init()  function returns undefined.

```typescript
import Hammer from 'hammerjs'
import * as cornerstone from 'cornerstone-core';
import * as cornerstoneMath from 'cornerstone-math';
import * as cornerstoneTools from 'cornerstone-tools';

class SomeComponent {

constructor() {
    cornerstoneTools.external.Hammer = Hammer;
    cornerstoneTools.external.cornerstone = cornerstone;
    cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
    const csTools = cornerstoneTools.init(this.cornerStoneConfig); //  <-- Undefined : 
    console.log(csTools);

  }
}
```
Here is a small example showing what i am trying to do  : 
[stackblitz example](https://stackblitz.com/edit/angular-svyt2r)

Any help would be appreciated and thank you.

**Comment by dannyrb** [comment]
`cornerstoneTools.init()` is not supposed to return a value. If you found old docs that indicated it should, please direct me to them -- they would be outdated from some experiments we tried during the v3 beta.

init is used to setup listeners for cornerstone core's `.enable()` calls, and a few other things. After calling it, the bulk of the API members you will use exist as top level exports on `CornerstoneTools`

**Comment by dannyrb** [comment]
15 minor versions later and you're the first to say anything. Because we often don't use our own docs, we rely on reports like this to help address issues and documentation needs. Thank you!

So yes.
cornerstoneTools.init()

And then methods like setToolActive can just be called off cornerstoneTools:
cornerstoneTools.setToolActive()

**Comment by TheHidden1** [comment]
i see xD, thank you for the fast response

**Comment by dannyrb** [comment]
I'll keep this open until the docs are updated so we don't forget. Thanks again for creating this issue!

**Comment by dannyrb** [comment]
Updated here: https://github.com/cornerstonejs/cornerstoneTools/pull/1023

**Comment by fomin-max** [comment]
Please also check [this example](https://jsfiddle.net/dannyrb/jhxdgu94/), I came across it from the official documentation
