### ISSUE TITLE
Expect to add CTR(mind-to-heart ratio) tools in the next version

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneTools#1027]
Expect to add CTR(mind-to-heart ratio) tools in the next version
![ctr](https://s2.ax1x.com/2019/07/24/eEbmR0.png)

**Comment by chenxxcc** [comment]
https://en.wikipedia.org/wiki/Cardiomegaly#Cardiothoracic_ratio

**Comment by dannyrb** [comment]
These seem like good candidates for 3rd party tools. If you have acceptance criteria and are willing to publish a tool open source, I can provide guidance on how to create a 3rd party cornerstone tool repository/library?
