### ISSUE TITLE
bug: IE11 not support context.ellipse method

### ISSUE THREAD

**Issue by xingbofeng** [cornerstonejs/cornerstoneTools#1037]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

see the [API docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse), IE11 don't support `context.ellipse`.I'd like to use cornerstoneTools on IE11.

and the code:

https://github.com/cornerstonejs/cornerstoneTools/blob/e7099c3e176c7b6ca6ce99fbf8c34d7907c7332a/src/drawing/drawEllipse.js#L68

https://github.com/cornerstonejs/cornerstoneTools/blob/e7099c3e176c7b6ca6ce99fbf8c34d7907c7332a/src/tools/brush/BrushTool.js#L92-L100

hope to draw ellipse like 2.x:

https://github.com/cornerstonejs/cornerstoneTools/blob/cb606085b80b72160e6ad48899f62be995d92272/src/util/drawing.js#L226-L253

I'd like to change the code like this:

```javascript
  if (context.ellipse) {
    const angle = (rotation * Math.PI) / 180;

    path(context, options, context => {
      context.ellipse(center.x, center.y, w / 2, h / 2, angle, 0, 2 * Math.PI);
      context.closePath();
    });
  } else {
    const kappa = 0.5522848,
      ox = (w / 2) * kappa, // Control point offset horizontal
      oy = (h / 2) * kappa, // Control point offset vertical
      xe = xMin + w, // X-end
      ye = yMin + h, // Y-end
      xm = xMin + w / 2, // X-middle
      ym = yMin + h / 2; // Y-middle

    path(context, options, context => {
      context.moveTo(xMin, ym);
      context.bezierCurveTo(xMin, ym - oy, xm - ox, yMin, xm, yMin);
      context.bezierCurveTo(xm + ox, yMin, xe, ym - oy, xe, ym);
      context.bezierCurveTo(xe, ym + oy, xm + ox, ye, xm, ye);
      context.bezierCurveTo(xm - ox, ye, xMin, ym + oy, xMin, ym);
      context.closePath();
    });
  }
```

**Comment by dannyrb** [comment]
@xingbofeng is this polyfill-able? Ideally, we could advise IE11 consumers to use something like:

https://github.com/google/canvas-5-polyfill

If you're pulling the package in with a build-step, I believe that babel fixes this issue for you. Or at least, I'm aware of Viewers that support IE 11 with the current drawing API, and they don't do anything other than target IE11 as a supported browser w/ babel.

**Comment by xingbofeng** [comment]
thanks i will try to use canvas-5-polyfill

**Comment by xingbofeng** [comment]
canvas-5-polyfill is ok for IE11,, now this issue can be closed.
