### ISSUE TITLE
cornerstoneTools.addtool is not a function

### ISSUE THREAD

**Issue by vanye007** [cornerstonejs/cornerstoneTools#1042]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

cornerstoneTools.addtool is not a function

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Codepen With Reproduction of Issue:

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by dannyrb** [comment]
Steps to reproduce?

**Comment by vanye007** [comment]
thanks, i have already fixed the issue
