### ISSUE TITLE
cornerstoneTools init error

### ISSUE THREAD

**Issue by hgdhot** [cornerstonejs/cornerstoneTools#1044]
when i initialize cornerstoneTools.init(), got an error
![1565690990](https://user-images.githubusercontent.com/19300626/62933948-f2d20c80-bdf5-11e9-8550-b2cda93d0e22.png)

**Comment by dannyrb** [comment]
Can you include a snippet of the code you are running, the library versions you are using, and a closer look at the line that is causing that error? Ideally, a CodePen that reproduces the error as well.

**Comment by hgdhot** [comment]
The code i running is as follow
`<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="XTitleHolder">Default title</ui:insert></title>
	
	<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
	<script src="https://cdn.jsdelivr.net/npm/cornerstone-math@0.1.6"></script>
	<script src="https://cdn.jsdelivr.net/npm/cornerstone-core@2.2.4"></script>
	<script src="https://cdn.jsdelivr.net/npm/cornerstone-web-image-loader@2.1.0"></script>
	<script src="https://cdn.jsdelivr.net/npm/cornerstone-tools@3.18.2"></script>
	
	<h:outputScript library="XJavascript" name="XTeleradiology/cornerstoneWADOImageLoader.js" />
	<h:outputScript library="XJavascript" name="XTeleradiology/dicomParser.min.js" />
</h:head>

<h:body style="background-color: #f0f2f5 !important;">

	<h:panelGroup layout="block" id="demo-element"></h:panelGroup>
	<script>

	cornerstoneWADOImageLoader.external.cornerstone = cornerstone;

	cornerstoneTools.external.cornerstone = cornerstone;
	cornerstoneTools.external.Hammer = Hammer;
	cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
	cornerstoneTools.init();
	var config = {
        maxWebWorkers: navigator.hardwareConcurrency || 1,
        startWebWorkersOnDemand : true,
    };
    //cornerstoneWADOImageLoader.webWorkerManager.initialize(config);
	
	const element = document.getElementById('demo-element');
	const imageId = "dicomweb://localhost/wado?studyUID=1.2.840.113704.1.111.2476.1565226891.1&amp;seriesUID=1.2.840.113704.1.111.2476.1565226973.3&amp;objectUID=1.2.840.113704.7.1.1.3000.1565227008.2&amp;requestType=WADO&amp;contentType=application%2Fdicom";
	cornerstone.enable(element);
	
	cornerstone.loadAndCacheImage(imageId).then(function(image) {
	  cornerstone.displayImage(element, image);
	  // Enable our tools
	  //cornerstoneTools.mouseInput.enable(element);
	  cornerstoneTools.mouseWheelInput.enable(element);
	  cornerstoneTools.wwwc.activate(element, 1); // Left Click
	  cornerstoneTools.pan.activate(element, 2); // Middle Click
	  cornerstoneTools.zoom.activate(element, 4); // Right Click
	  cornerstoneTools.zoomWheel.activate(element); // Mouse Wheel
	});
	</script>

</h:body>`

**Comment by hgdhot** [comment]
![1565745311(1)](https://user-images.githubusercontent.com/19300626/62987781-04f29000-be74-11e9-8866-757beca6a213.png)
the line that cause the error

**Comment by dannyrb** [comment]
It looks like you upgraded to `cornerstone-tools@3` from `@2`, but have not updated your code to reflect the changes that took place in that major version bump. For example:

```
  cornerstoneTools.mouseWheelInput.enable(element);
  cornerstoneTools.wwwc.activate(element, 1); // Left Click
  cornerstoneTools.pan.activate(element, 2); // Middle Click
  cornerstoneTools.zoom.activate(element, 4); // Right Click
  cornerstoneTools.zoomWheel.activate(element); // Mouse Wheel
```

Is not how you activate tools in `@3`. `mouseWheelInput.enable()` is no longer exposed by the API either.

**Comment by hgdhot** [comment]
the error still show up even i dropped all the activate code above, the error thrown when the cornerstoneTools.init() get executed.

**Comment by hgdhot** [comment]
sorry, i found what the problem is, i used a wrong version of cornerstone-core,
thanks for your help.

**Comment by dobatruong1111** [comment]
Hello @hgdhot 
Currently which version of cornerstone should i use. I am also getting an error when calling init() from @cornerstonejs/core
![image](https://github.com/cornerstonejs/cornerstoneTools/assets/74960507/bcfc4f61-4a57-4de4-8caf-a95b42a7dc5c)
