### ISSUE TITLE
How to save the canvase state 

### ISSUE THREAD

**Issue by vanye007** [cornerstonejs/cornerstoneTools#1049]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Save the canvas state with the tools

### Steps to Reproduce

1. Once i finish manipulating the canvas
2. Save the canvas exit 
3. On restore, the previous save state should appear along with the tools

**Expected behavior:** the previous save state should appear along with the tools

**Actual behavior:** The canvas is saved but not with the tools and changes made

### Codepen With Reproduction of Issue:

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by dannyrb** [comment]
What have you tried? Where are you getting stuck?

**Comment by vanye007** [comment]
i tried saving the canvas as base64 in a variable
restore the canvas, but it appears as an image.
I want it to be editable again not as an image

**Comment by dannyrb** [comment]
You will need to look at the `getToolState` and `toolStateManager` to access and serialize the application's state for existing tools.

**Comment by vanye007** [comment]
Awesome, thanks alot. That was helpfull
