### ISSUE TITLE
Some annotation tools (Cobb and Bidirectional tool) are not importing, causing error

### ISSUE THREAD

**Issue by vanye007** [cornerstonejs/cornerstoneTools#1050]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. const csTools = cornerstoneTools.init();
2. const CobbAngleTool = cornerstoneTools.CobbAngleTool;
3. csTools.addTool(CobbAngleTool);

**Expected behavior:** add the tool

**Actual behavior:** 
TypeError: apiTool is not a constructorcornerstoneTools.js:9255:14
    addToolForElement https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9255
    addTool https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9276
    forEach self-hosted:266
    addTool https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9275
    <anonymous> file:///C:/Users/user/Documents/GitHub/iMi-Xray-Manager/viewer-master/js/tools.js:42

### Codepen With Reproduction of Issue:

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by vanye007** [comment]
the cobb and biderectional tools are not importing

**Comment by dannyrb** [comment]
```js
import cornerstoneTools from 'cornerstone-tools';

cornerstoneTools.init();
cornerstoneTools.addTool(cornerstoneTools.CobbAngleTool);
```

**Comment by vanye007** [comment]
still getting the same error

TypeError: cornerstoneTools.addTool is not a functiontools.js:41:18

i tried console.log(cornerstoneTools) and i could not find cobb and biderectional tool listed but others are available

**Comment by dannyrb** [comment]
Are you using latest? This appears to work fine:

https://tools.cornerstonejs.org/examples/tools/cobb-angle.html

**Comment by vanye007** [comment]
yeah i am, other tools works perfectly fine apart form those two. when i try importing them. The system crashes with the following error.

TypeError: apiTool is not a constructorcornerstoneTools.js:9255:14
addToolForElement https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9255
addTool https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9276
forEach self-hosted:266
addTool https://cdn.jsdelivr.net/npm/cornerstone-tools@3.0.0-b.641/dist/cornerstoneTools.js:9275
file:///C:/Users/user/Documents/GitHub/iMi-Xray-Manager/viewer-master/js/tools.js:42

**Comment by dannyrb** [comment]
> Are you using latest? 

There error you pasted shows that you're using version `3.0.0-b.641`. That's a "beta" build before version 3 was finalized. It's at least 18 feature releases behind from latest.

**Comment by vanye007** [comment]
Oh alright, how do i get the full version?

**Comment by dannyrb** [comment]
- `https://unpkg.com/cornerstone-tools` will resolve to latest
- `https://unpkg.com/cornerstone-tools@3.18.3` is the current latest, and that URL will always point to that specific version

Or you can download the source from GitHub, or include it as a packaged dependency using `npm`

**Comment by vanye007** [comment]
thank you
