### ISSUE TITLE
Probe Tool configurations

### ISSUE THREAD

**Issue by tunglt1810** [cornerstonejs/cornerstoneTools#1069]
### Prerequisites

* version 4.0.4

### Description

After upgrade version from v3.19.3 to v.4.0.4, the DragProbe tool does not work properly
![image](https://user-images.githubusercontent.com/19906349/64753325-01265c00-d54d-11e9-8899-323c167f8b0d.png)

How can i add configuration for this tool, and how to show HU point instead of MO point when using v3.19.3

![image](https://user-images.githubusercontent.com/19906349/64753424-5ebaa880-d54d-11e9-81d8-523dce776f58.png)

**Comment by JamesAPetts** [comment]
I missed this one because its not in the index demo like all the other tools. The way strategies applied has changed in 4.X, I'll address this.

**Comment by JamesAPetts** [comment]
> and how to show HU point instead of MO point when using v3.19.3

In order to use HU the series must have the correct metadata loaded in a cornerstone metadata provider. If the modality in the `generalSeriesModule` is `'CT'`, then HU will be used.

**Comment by JamesAPetts** [comment]
Fixxed in `#1069`.
