### ISSUE TITLE
StackPrefetch stops when selecting different element (regression)

### ISSUE THREAD

**Issue by frolic06** [cornerstonejs/cornerstoneTools#1071]
This feature was remove during a merge in the version 3.
The parameter 'preserveExistingPool' in stackPrefetch.js no longer exists after the commits on Nov 11, 2018.

**Comment by dannyrb** [comment]
@frolic06 if you can provide more info, I'm sure we can whip up a quick PR? Any links or code snippets? Would you like to draft a PR to expedite things?

**Comment by frolic06** [comment]
I fixed the bug with this code. I am sorry but i am not used to make a PR.
[stackPrefetch.js.txt](https://github.com/cornerstonejs/cornerstoneTools/files/3609959/stackPrefetch.js.txt)

**Comment by frolic06** [comment]
I made a PR, I hope it will help you.

**Comment by dannyrb** [comment]
Thanks, @frolic06! I'll take a peak today.

Linked PR: https://github.com/cornerstonejs/cornerstoneTools/pull/1074

**Comment by frolic06** [comment]
Hello,
I think this issue #900 refers to the same bug.
The fix is still relevant.

**Comment by dannyrb** [comment]
Merged 🎉
