### ISSUE TITLE
Unable to find tool "SphericalBrush" for enabledElement

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstoneTools#1073]
Version 4.0.3: Tool not found "SphericalBrush". #1068
Version 4.0.2: Works.

![Anotação 2019-09-13 121707](https://user-images.githubusercontent.com/50026015/64858899-89c1fc80-d620-11e9-9ecf-08e59d51efc7.png)

**Comment by dannyrb** [comment]
Thanks, @jlopes90. That's odd.
I am able to reproduce on this recent netlify preview:

https://deploy-preview-1072--cornerstone-tools.netlify.com/

**Comment by dannyrb** [comment]
It looks like...

`SphericalBrushTool` extends `BrushTool` extends `BaseBrushTool` extends `BaseTool`

All `BaseXXXTool`'s support passing in `props, defaultProps`, and the merge is handled in `BaseTool`. It looks like I wrongly assumed that `SphericalBrushTool` extended `BaseBrushTool` when I accepted the PR.

`SphericalBrushTool` uses the same render brush method as `BrushTool`, hence the chaining. We need to move this to a mixin or a shared function, and update it to extend `BaseBrushTool` to resolve.

Thanks for the report!

CC: @mikehazell  (just so you're in the loop, as this likely impacts you)

**Comment by dannyrb** [comment]
@jlopes90, should be live once CI cuts latest release
