### ISSUE TITLE
Impossible to get metadata from a specific dicom file

### ISSUE THREAD

**Issue by pzehle** [cornerstonejs/cornerstoneTools#1091]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description

So I used to get my dicom files ordered by using the meta data 'xx00200032', which gives me the position inside the set. Now, I got new files from the doctor and some of these files don't have this metadata, so I see that I have to use the 'x00189318', which kind of gives some other positioning information. The problem I have is, and I don't know if this come from the core, or tools or WADO, if I call image.data.string('x00189318'), I get weird coded strings like: =b�X9´�À�C�lç�aÀã¥�Ä ��À, and if I try to retrieve the meta data with console.log(cornerstone.metaData.get('imagePlane', image.imageId)); I just get undefined. Please notice that imagePlane is just an example, whatever I put in there just returns undefined. Can you please provide support for this?

Thanks!

**Comment by jlopes90** [comment]
Have you ever seen an example [DicomParser](https://rawgit.com/cornerstonejs/dicomParser/master/examples/index.html)?

**Comment by pzehle** [comment]
Hello, thanks for your answer.

Yes, I have seen a lot of examples. And as the question, it doesn't say that I can't or don't know how to retrieve metadata, it says that the metadata being retrieved is either in an incorrect format, or the other available functions provided by this library are not working. I don't think this is a helpful answer to my actual issue, but I thank you for giving support.

**Comment by pzehle** [comment]
My bad, tho the examples are not very clear with the dicom parser library, I managed to do this considering the following:

`// the DataSet object has functions to support every VR type:
            // All string types - string()
            // US - uint16()
            // SS - int16()
            // UL - uint32()
            // SL - int32()
            // FL - float()
            // FD - double()
            // DS - floatString()
            // IS - intString()`
