### ISSUE TITLE
How to change the configuration of the ArrowAnnotate tool getTextCallback and changeTextCallback method

### ISSUE THREAD

**Issue by jesusjames** [cornerstonejs/cornerstoneTools#1105]
### Prerequisites

* [ ] Which version are you using? 4.6
* [ ] Are you reporting to the correct repository? yes
* [ ] Did you search existing issues? yes

### Description

Hello. previously in version 2.4 you could modify the configuration of any tool with the setConfiguration method. I tried to modify the callback functions for the modal of the ArrowAnnotation tool and I could not. The only solution I came up with was to create an ArrowAnnotateCustom that extends from BaseAnnotationTool and modify the getTextCallback and changeTextCallback methods . 
In the new version 4.6 of cornerstoneTools is there any way to change the configuration of ArrorAnnotate?

this.configArrowAnnotate = {
            getTextCallback : this.getTextCallback,
            changeTextCallback : this.changeTextCallback,
            drawHandles : false,
            drawHandlesOnHover : true,
            arrowFirst : true,
        };

![image](https://user-images.githubusercontent.com/17242609/66875768-0c6a0e80-ef75-11e9-8a9a-bae16e9ca037.png)

### CodeSandbox With Reproduction of Issue:

- [Basic Template](https://codesandbox.io/s/cornerstone-basic-issue-template-9slk4)

**Comment by dannyrb** [comment]
👋 Hi @jesusjames, thanks for creating an issue. In `cornerstone-tools@3` and beyond, `configuration` is set when adding a tool:

```js
cornerstoneTools.addTool(ArrowAnnotateTool, {
  configuration: {
    getTextCallback: () => { console.log('get text'); },
    changeTextCallback: () => { console.log('change text'); },
  },
});
```

- [ArrowAnnotateTool configuration](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/ArrowAnnotateTool.js#L33-L50)
- [cornerstone.addTool internals](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/addTool.js#L23)

In general we've earmarked `configuration` as being set in stone once a tool has been created. The idea is that you can use it to effectively create many different tools from the same source. A common use case is creating a `BrushEraserTool` from the `BrushTool` by setting it's always erase flag to true.

We've tried to leave `options` open if you need values that change over time.

I think that's all roughly correct. If you encounter any issues, or if you have any questions, please don't hesitate to comment.

**Comment by jesusjames** [comment]
It's great, thank you very much.

**Comment by mikehazell** [comment]
This piece of info is gold!

> In general we've earmarked configuration as being set in stone once a tool has been created. The idea is that you can use it to effectively create many different tools from the same source. A common use case is creating a BrushEraserTool from the BrushTool by setting it's always erase flag to true.
>
> We've tried to leave options open if you need values that change over time.

It really belongs in the docs.
