### ISSUE TITLE
How do you change the configuration of tools over time.

### ISSUE THREAD

**Issue by jesusjames** [cornerstonejs/cornerstoneTools#1110]
### Prerequisites

* [ ] Which version are you using? (Is it latest?) 4.6
* [ ] Are you reporting to the correct repository? yes
* [ ] Did you search existing issues? (Were any related?) yes

### Description

I am trying to change the magnify tool settings over time.
I have used the setToolOptions () method but this did not work for me.

![image](https://user-images.githubusercontent.com/17242609/67095619-faa68800-f17b-11e9-92dc-c5c8e0d230dd.png)
```javascript
cornerstoneTools.setToolOptions('Magnify', {configutarion: { magnifySize: 125, magnificationLevel: 5 }})
```

so I have solved it by changing this configuration directly in the store.tools of cornerstonTools, which I do not know if it is the right thing or there is an easy and adequate way to change this configuration over time, since I cannot find it in the documentation.

```javascript
export const updateConfigurationTool = (toolName, configuration) => {
    let stateTools = cornerstoneTools.store.state.tools;
    stateTools.forEach((tool, index) => {
        if(tool instanceof cornerstoneTools[`${toolName}Tool`]){ 
            // update tool configuration on all enabled elements
            cornerstoneTools.store.state.tools[index].configuration = configuration;
        }
    });
}

updateConfigurationTool('Magnify',  { magnifySize: 125, magnificationLevel: 5 });
```

**Comment by dannyrb** [comment]
@jesusjames, the tool should probably be updated to move those values to it's `options`, so it can leverage [`setToolOptions`](https://github.com/cornerstonejs/cornerstoneTools/blob/40d30a11daad89c0b6828618dda681fa48d0128d/src/store/setToolOptions.js) to update them.

A PR to accomplish this in a non-breaking way would...

- Add these keys to the tool's options, with an initial value of undefined
- Use `options` keys, if defined; else use `configurations`
- Update code to use `setToolOptions` instead of your custom `updateConfigurationTool`

**Comment by jesusjames** [comment]
I have done the tests and it has not worked for me.
I would like to know what I am doing wrong?
look at this test code -> https://codesandbox.io/embed/cornerstone-basic-issue-template-vb1c4

**Comment by dannyrb** [comment]
Hi @jesusjames, I think we misunderstood one another. I was saying that you CANNOT currently update `magnifySize` and `magnificationLevel` with public API methods. My previous post was alluding to how we could update the tool to such that either of these recipes would work:

```js
// Initial values
cornerstoneTools.addTool(cornerstoneTools.MagnifyTool, {
  configuration: { magnifySize: 225, magnificationLevel: 5 }
});

// Update when changing the tool's mode
cornerstoneTools.setToolActive("Magnify", { 
  mouseButtonMask: 1,
  magnifySize: 100,
  magnificationLevel: 1,
});
```

OR

```js
// Initial values
cornerstoneTools.addTool(cornerstoneTools.MagnifyTool, {
  configuration: { magnifySize: 225, magnificationLevel: 5 }
});
// Update explicitly
cornerstoneTools.setToolOptions("Magnify", { 
  magnifySize: 100,
  magnificationLevel: 1,
});
```

Again, neither of these options work today, but could with some slight modifications to the tool. These changes would require a Pull Request.
