### ISSUE TITLE
Unable to run FreehandScissors tool from example site/source: ApiTool is not a constructor

### ISSUE THREAD

**Issue by mkramers** [cornerstonejs/cornerstoneTools#1111]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description

Version 4.6.2 - `master@4d3646269d0ec0248e7bb28d08e8cbbc47feddd2`
I am experiencing a `TypeError: ApiTool is not a constructor` when running Freehand Scissors tool from the examples page via docker (as per https://github.com/cornerstonejs/cornerstoneTools/tree/master/examples), as well as the hosted examples (https://tools.cornerstonejs.org/examples/tools/freehand-scissors.html).

I am also experiencing this when I try to create my own tool following the guide here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/docs/latest/custom-tools/creating-your-tool.md

### Steps to Reproduce the issue

1. Visit https://tools.cornerstonejs.org/examples/tools/freehand-scissors.html in Firefox/Chrome
2. Open console
3. Observe tool not functioning and error:

```
TypeError: ApiTool is not a constructor        cornerstone-tools@^3:9961:14
    addToolForElement https://unpkg.com/cornerstone-tools@^3:9961
    addTool https://unpkg.com/cornerstone-tools@^3:9989
    forEach self-hosted:266
    addTool https://unpkg.com/cornerstone-tools@^3:9988
    <anonymous> https://tools.cornerstonejs.org/examples/tools/freehand-scissors.html:350
```

**Expected behavior:** (What you expected to happen)
- The tool should work

**Actual behavior:** (What actually happened)
- The tool does not do anything, error is reported in Console.

### CodeSandbox With Reproduction of Issue:
- I could try to import my sample tool if necessary, but I am hoping that the above repro steps are helpful enough.

Thank you for your excellent work!

**Comment by dannyrb** [comment]
Examples were tied to @3 of cornerstone. I've updated them to look at @4. It's worth noting for the seg tools that they're much snappier the smaller the image. Our default example image is a very, very large DX.

Please let me know if you have any other questions/issues ^_^

**Comment by mkramers** [comment]
Thanks! I appreciate the help!
