### ISSUE TITLE
Does this tool support Ionic?

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneTools#1117]
Hello

I am trying to implement these tools into the Ionic Framework ver 1. but in ionic I am facing issue regarding the touch events, this is the warning log I am getting

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more
> 
> hammer.js:222 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> 
> Unable to find tool "StackScrollMultiTouchTool" for enabledElement
> 
> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
> 
> ionic.bundle.js:7517 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

I the `hammer.js` and `ionic.bundle.js`  both the file is having touch events I think that's the reason touch scroll is blocking. Please any one of you had implemented these tools in ionic project. 

Please let me know.

**Comment by pmd23** [comment]
> The bigger issue appears to be your:
> 
> `Unable to find tool "StackScrollMultiTouchTool" for enabledElement`

for this what i need to do so that this touch events are woking properly. also one more thing i want to discuss that when i am applying WL tool its working properly. so what is the issue for all stack took not working.

Thanks

**Comment by dannyrb** [comment]
Reproduction? What have you tried?

**Comment by pmd23** [comment]
I tried 
       
```
       	const scheme = 'wadouri'
const baseUrl = 'https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/' 
const series = [
	'bbmri-53323851.dcm',
    'bbmri-53323707.dcm',
	'bbmri-53323563.dcm'
]

const imageIds = series.map(seriesImage => `${scheme}:${baseUrl}${seriesImage}`);
var element = document.querySelector('.cornerstone-element');//document.getElementById("cornerstone-element");

cornerstoneWebImageLoader.external.cornerstone = cornerstone;
cornerstone.registerImageLoader('http', cornerstoneWebImageLoader.loadImage)
cornerstone.registerImageLoader('https', cornerstoneWebImageLoader.loadImage)
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneTools.init();

cornerstone.enable(element);
//define the stack
const StackScrollMultiTouchTool = cornerstoneTools.StackScrollMultiTouchTool

//define the stack
const stack = {
  currentImageIdIndex: 0,
  imageIds
}

// load images and set the stack
cornerstone.loadImage(imageIds[0]).then((image) => {
  cornerstone.displayImage(element, image)
  cornerstoneTools.addStackStateManager(element, ['stack'])
  cornerstoneTools.addToolState(element, 'stack', stack)
})
	cornerstoneTools.addTool(StackScrollMultiTouchTool)
	cornerstoneTools.setToolActive('StackScrollMultiTouchTool', {  })
```
