### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by gf1371876** [cornerstonejs/cornerstoneTools#1118]
### Prerequisites

* [ ] Which version are you using? (Is it latest?)
   cornerstone-core : 2.3.0
   cornerstone-math:0.1.8
   cornerstone-tools：4.6.2

in this function  
function loadAndViewImage(imageId) {
      // const element = document.getElementById('dicomImage');
      const start = new Date().getTime();
      cornerstone.loadImage(imageId).then(function(image) {
          console.log(image);
          const viewport = cornerstone.getDefaultViewportForImage(element, image);
          cornerstone.displayImage(element, image, viewport);
          if(loaded === false) {
              _**cornerstoneTools.mouseInput.enable(element);**_
              cornerstoneTools.mouseWheelInput.enable(element);
              cornerstoneTools.wwwc.activate(element, 1); // ww/wc is the default tool for left mouse button
              cornerstoneTools.pan.activate(element, 2); // pan is the default tool for middle mouse button
              cornerstoneTools.zoom.activate(element, 4); // zoom is the default tool for right mouse button
              cornerstoneTools.zoomWheel.activate(element); // zoom is the default tool for middle mouse wheel
              cornerstoneTools.imageStats.enable(element);
              loaded = true;
          }
          function getTransferSyntax() {
              const value = image.data.string('x00020010');
              return value + ' [' + uids[value] + ']';
          }

          function getSopClass() {
              const value = image.data.string('x00080016');
              return value + ' [' + uids[value] + ']';
          }

          function getPixelRepresentation() {
              const value = image.data.uint16('x00280103');
              if(value === undefined) {
                  return;
              }
              return value + (value === 0 ? ' (unsigned)' : ' (signed)');
          }

          function getPlanarConfiguration() {
              const value = image.data.uint16('x00280006');
              if(value === undefined) {
                  return;
              }
              return value + (value === 0 ? ' (pixel)' : ' (plane)');
          }

          document.getElementById('transferSyntax').textContent = getTransferSyntax();
          document.getElementById('sopClass').textContent = getSopClass();
          document.getElementById('samplesPerPixel').textContent = image.data.uint16('x00280002');
          document.getElementById('photometricInterpretation').textContent = image.data.string('x00280004');
          document.getElementById('numberOfFrames').textContent = image.data.string('x00280008');
          document.getElementById('planarConfiguration').textContent = getPlanarConfiguration();
          document.getElementById('rows').textContent = image.data.uint16('x00280010');
          document.getElementById('columns').textContent = image.data.uint16('x00280011');
          document.getElementById('pixelSpacing').textContent = image.data.string('x00280030');
          document.getElementById('bitsAllocated').textContent = image.data.uint16('x00280100');
          document.getElementById('bitsStored').textContent = image.data.uint16('x00280101');
          document.getElementById('highBit').textContent = image.data.uint16('x00280102');
          document.getElementById('pixelRepresentation').textContent = getPixelRepresentation();
          document.getElementById('windowCenter').textContent = image.data.string('x00281050');
          document.getElementById('windowWidth').textContent = image.data.string('x00281051');
          document.getElementById('rescaleIntercept').textContent = image.data.string('x00281052');
          document.getElementById('rescaleSlope').textContent = image.data.string('x00281053');
          document.getElementById('basicOffsetTable').textContent = image.data.elements.x7fe00010 && image.data.elements.x7fe00010.basicOffsetTable ? image.data.elements.x7fe00010.basicOffsetTable.length : '';
          document.getElementById('fragments').textContent = image.data.elements.x7fe00010 && image.data.elements.x7fe00010.fragments ? image.data.elements.x7fe00010.fragments.length : '';
          document.getElementById('minStoredPixelValue').textContent = image.minPixelValue;
          document.getElementById('maxStoredPixelValue').textContent = image.maxPixelValue;
          const end = new Date().getTime();
          const time = end - start;
          document.getElementById('totalTime').textContent = time + "ms";
          document.getElementById('loadTime').textContent = image.loadTimeInMS + "ms";
          document.getElementById('decodeTime').textContent = image.decodeTimeInMS + "ms";

      }, function(err) {
          alert(err);
      });
    }

error info 
Uncaught (in promise) TypeError: Cannot read property 'enable' of undefined

**Comment by gf1371876** [comment]
![image](https://user-images.githubusercontent.com/29647385/68109625-fcb36980-ff25-11e9-8c17-4a4d4a780011.png)

**Comment by gf1371876** [comment]
麻烦您方便的时候帮忙看一下这个问题
Please help me to look at this problem at your convenience

**Comment by dannyrb** [comment]
```
cornerstoneTools.mouseInput.enable(element);
cornerstoneTools.mouseWheelInput.enable(element);
cornerstoneTools.wwwc.activate(element, 1); // ww/wc is the default tool for left mouse button
cornerstoneTools.pan.activate(element, 2); // pan is the default tool for middle mouse button
cornerstoneTools.zoom.activate(element, 4); // zoom is the default tool for right mouse button
cornerstoneTools.zoomWheel.activate(element); // zoom is the default tool for middle mouse wheel
cornerstoneTools.imageStats.enable(element);
```

This syntax is from `cornerstone-tools@2`, you're using `cornerstone-tools@4`

Easier to help if you create a CodePen or CodeSandbox that you can share.

**Comment by gf1371876** [comment]
How to create  a CodePen or CodeSandbox ？Do you have any documents for reference?

**Comment by gf1371876** [comment]
I try to change version , If I change to cornerstone-tools@2
error is  Uncaught (in promise) TypeError: Cannot read property 'mouseInput' of undefined

**Comment by gf1371876** [comment]
look at this picture 
![image](https://user-images.githubusercontent.com/29647385/68128765-50887780-ff53-11e9-8397-183e42c2c72d.png)
![image](https://user-images.githubusercontent.com/29647385/68128795-5c743980-ff53-11e9-936c-be9f4b384cf2.png)
it is my code ,error info  is 
![image](https://user-images.githubusercontent.com/29647385/68128856-7ca3f880-ff53-11e9-898d-4d0b642c1e46.png)
![image](https://user-images.githubusercontent.com/29647385/68128876-86c5f700-ff53-11e9-954d-a037e72a9cdc.png)

**Comment by gf1371876** [comment]
https://codepen.io/gf1371876/pen/VwwQrQr

this is my CodePen

**Comment by dannyrb** [comment]
CodePen does not support `import` syntax. You would need to update the settings for the pen to pull in the dependencies from `unpkg` or a similar source.

CodeSandbox supports `import` syntax and a build step

**Comment by gf1371876** [comment]
> ```
> cornerstoneTools.mouseInput.enable(element);
> cornerstoneTools.mouseWheelInput.enable(element);
> cornerstoneTools.wwwc.activate(element, 1); // ww/wc is the default tool for left mouse button
> cornerstoneTools.pan.activate(element, 2); // pan is the default tool for middle mouse button
> cornerstoneTools.zoom.activate(element, 4); // zoom is the default tool for right mouse button
> cornerstoneTools.zoomWheel.activate(element); // zoom is the default tool for middle mouse wheel
> cornerstoneTools.imageStats.enable(element);
> ```
> 
> This syntax is from `cornerstone-tools@2`, you're using `cornerstone-tools@4`
> 
> Easier to help if you create a CodePen or CodeSandbox that you can share.

**I share the CodePen ,I have a question ，if this syntax is from `cornerstone-tools@2`  ，then in `cornerstone-tools@4`   How to write to achieve the same effect ，Thank you for helping me solve this problem**

**Comment by gf1371876** [comment]
https://codepen.io/gf1371876/pen/VwwQrQr?editors=1010

The code has been updated. Please fix it

**Comment by gf1371876** [comment]
![image](https://user-images.githubusercontent.com/29647385/68142289-24c4bc00-ff6a-11e9-8760-b89da589ab3b.png)
![image](https://user-images.githubusercontent.com/29647385/68142314-33ab6e80-ff6a-11e9-974f-de8a3639b585.png)
![image](https://user-images.githubusercontent.com/29647385/68142331-3c9c4000-ff6a-11e9-8621-df42ffcd1298.png)
Please tell me how to use cornerstone-tools@4   to achieve the effect similar to the mouse scrolling in the screenshot ，thank you

**Comment by gf1371876** [comment]
![image](https://user-images.githubusercontent.com/29647385/68171868-73954480-ffb0-11e9-8f24-10a3257bb6c9.png)
How to change transparency or contrast in cornerstone-tools@4  version by mouse sliding

https://codepen.io/gf1371876/pen/VwwQrQr?editors=1010
thanks

**Comment by gf1371876** [comment]
**I resolve this problem** 
thanks
This is the code
**//初始化cornerstone
    function initCornerstone() {
        // const baseUrl = window.ENVIRONMENT === 'development' ? 'http://localhost:4000/': 'https://tools.cornerstonejs.org/examples/';
        // Externals
        cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
        cornerstoneWADOImageLoader.external.dicomParser = dicomParser;
        cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
        cornerstoneTools.external.cornerstone = cornerstone;
        cornerstoneTools.external.Hammer = Hammer;
        // Image Loader
        const config = {
            webWorkerPath: '../asstes/js//cornerstoneWADOImageLoaderCodecs.js',
            taskConfiguration: {
                decodeTask: {
                    codecsPath: '../asstes/js//cornerstoneWADOImageLoaderCodecs.js',
                },
            },
        };
        cornerstoneWADOImageLoader.webWorkerManager.initialize(config);
    }
    //初始化模块的按钮
    function initModeButtons() {
        const nameSpace = `.mode-buttons`;
        const buttons = document.querySelectorAll(`${nameSpace} .set-tool-mode`);
        const handleClick = function(evt) {
        const action = this.dataset.action;
        const options = {
            mouseButtonMask:
            evt.buttons ,
        };
        cornerstoneTools[`setTool${action}`](toolName, options);
        // Remove active style from all buttons
        buttons.forEach(btn => {
            btn.classList.remove('is-primary');
        });
        // Add active style to this button
        this.classList.add('is-primary');
        evt.preventDefault();
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        return false;
        };
        buttons.forEach(btn => {
        btn.addEventListener('contextmenu', handleClick);
        btn.addEventListener('auxclick', handleClick);
        btn.addEventListener('click', handleClick);
        });
    }
    //展示影像
    function showImage(){
        // const baseUrl = window.ENVIRONMENT === 'development' ? 'http://localhost:4000/': 'https://tools.cornerstonejs.org/examples/';
        let url = "/download/wadouri/fe8fe087cca7aabf143acd20da578251.dcm";
        let imageIds = "wadouri:" + url;
        // const imageIds = [
        //     `wadouri:${baseUrl}assets/dicom/exotic/1.dcm`,
        //     `wadouri:${baseUrl}assets/dicom/exotic/2.dcm`,
        // ];
        const stack = {
            currentImageIdIndex: 0,
            imageIds: imageIds,
        };
        cornerstone.loadImage(imageIds).then(function(image) {
            cornerstoneTools.addStackStateManager(element, ['stack']);
            cornerstoneTools.addToolState(element, 'stack', stack);
            cornerstone.displayImage(element, image);
        });
    }
    initCornerstone();
    const element = document.getElementById('dicomImage');
    initModeButtons();
    cornerstoneTools.init({
        showSVGCursors: true,
    });
    cornerstone.enable(element);
    const toolName = 'Wwwc';
    showImage();
    // 设置工具
    function setTools(){
        const apiTool = cornerstoneTools[`${toolName}Tool`];
        cornerstoneTools.addTool(apiTool);
        cornerstoneTools.setToolActive(toolName, { mouseButtonMask: 1 });
    }
    setTools();**
in cornerstone-tools@4  Wwwc tools
thanks
