### ISSUE TITLE
Unable to find tool "StackScrollMultiTouchTool" for enabledElement

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneTools#1120]
I am tring to implement this lib into ionic, but for if having multiple images I am not able to apply the touch event on device.
```
const scheme = 'wadouri'
const baseUrl = 'https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/' 
const series = [
	'bbmri-53323851.dcm',
    'bbmri-53323707.dcm',
	'bbmri-53323563.dcm'
]

const imageIds = series.map(seriesImage => `${scheme}:${baseUrl}${seriesImage}`);
var element = document.querySelector('.cornerstone-element');//document.getElementById("cornerstone-element");

cornerstoneWebImageLoader.external.cornerstone = cornerstone;
cornerstone.registerImageLoader('http', cornerstoneWebImageLoader.loadImage)
cornerstone.registerImageLoader('https', cornerstoneWebImageLoader.loadImage)
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneTools.init();

cornerstone.enable(element);
//define the stack
const StackScrollMultiTouchTool = cornerstoneTools.StackScrollMultiTouchTool

//define the stack
const stack = {
  currentImageIdIndex: 0,
  imageIds
}

// load images and set the stack
cornerstone.loadImage(imageIds[0]).then((image) => {
  cornerstone.displayImage(element, image)
  cornerstoneTools.addStackStateManager(element, ['stack'])
  cornerstoneTools.addToolState(element, 'stack', stack)
})
	cornerstoneTools.addTool(StackScrollMultiTouchTool)
	cornerstoneTools.setToolActive('StackScrollMultiTouchTool', {  })
```

getting this warning

setToolMode.js:234 Unable to find tool "StackScrollMultiTouchTool" for enabledElement

I am using all the latest .js file of cornerstonejs

https://unpkg.com/cornerstone-core
https://unpkg.com/cornerstone-math
https://unpkg.com/cornerstone-tools
https://unpkg.com/dicom-parser@1.8.3/dist/dicomParser.js
https://unpkg.com/cornerstone-wado-image-loader@3.0.6/dist/cornerstoneWADOImageLoader.js
https://unpkg.com/cornerstone-web-image-loader@2.1.0/dist/cornerstoneWebImageLoader.js

what i need to do so that this tool will be functional on mobile.

**Comment by dannyrb** [comment]
That's it's class name, not it's default name:
https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/StackScrollMultiTouchTool.js#L17

You can also override the tool's name when you call `addTool`

**Comment by pmd23** [comment]
okay got it I have just copied the example from 
https://tools.cornerstonejs.org/examples/tools/stack-scroll-multi-touch.html
that's why I was facing the issue. 
But right now everything is working well

Thanks
