### ISSUE TITLE
How to get index of image in StackScrollTool to get dicom tags

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneTools#1121]
When I scroll the viewer dicom images are chnage but i did not get index of that dicom image so that depending upon that index I can pass it another function so that I can able to get **dicom tags** for the respective dicom image scroll index.  	
```
const scheme = 'wadouri'
const baseUrl = 'https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/' 
const series = [
	'bbmri-53323851.dcm',
    'bbmri-53323707.dcm',
	'bbmri-53323563.dcm'
]

const imageIds = series.map(seriesImage => `${scheme}:${baseUrl}${seriesImage}`);
var element = document.querySelector('.cornerstone-element');//document.getElementById("cornerstone-element");
// Add our tool, and set it's mode
cornerstoneWebImageLoader.external.cornerstone = cornerstone;
cornerstone.registerImageLoader('http', cornerstoneWebImageLoader.loadImage)
cornerstone.registerImageLoader('https', cornerstoneWebImageLoader.loadImage)
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneTools.init();

var item1 = cornerstone.enable(element);
//define the stack
const StackScrollTool = cornerstoneTools.StackScrollTool

//define the stack
const stack = {
  currentImageIdIndex: 0,
  imageIds
}

// load images and set the stack
cornerstone.loadImage(imageIds[0]).then((image) => {
  cornerstone.displayImage(element, image)
  cornerstoneTools.addStackStateManager(element, ['stack'])
  cornerstoneTools.addToolState(element, 'stack', stack)
})
	cornerstoneTools.addTool(StackScrollTool)
	cornerstoneTools.setToolActive('StackScroll', {mouseButtonMask: 1 })
```

**Comment by dannyrb** [comment]
When you scroll, cornerstone emits a new image event (see https://github.com/cornerstonejs/cornerstone/blob/master/src/events.js#L2).

The new image event contains the image's ID. This can be used to find:

- Any image ID specific toolstate
- Any image metadata (see cornerstone metadata providers)

**Comment by Raistlfiren** [comment]
I just wanted to add to this issue - you need to place the event on the element and not on cornerstone. I spent hours putting the event on cornerstone, and wondering why it didn't work. The following code worked **after enabling** cornerstone on the element.

```
element.addEventListener('cornerstonenewimage', function (e) {
     window.downloadURL = e.detail.image.imageId.replace('wadouri:', '');
});
```
Thanks!

**Comment by dannyrb** [comment]
@Raistlfiren, this is a good call out. This can be especially tricky if you're dynamically enabling/destroying enabledElements. You can listen, on `cornerstone` for the `element enabled` event, then use the `enabled element` in that event to attach the `cornerstonenewimage` listener.

It might be a worthwhile enhancement to allow listening for `cornerstonenewimage` on `cornerstone`, but also include the `enabled element` that emitted the event. This would likely save consumers some effort.

**Comment by Raistlfiren** [comment]
Thanks @dannyrb for the clarification and update. I will look into it some more, and update my code based upon your input.
