### ISSUE TITLE
Cannot show debug in console

### ISSUE THREAD

**Issue by tunglt1810** [cornerstonejs/cornerstoneTools#1123]
Hi guys,
Im using v4.6.2. After set debug mode on by command 
`localStorage.setItem("debug", "cornerstoneTools:*");`
the tools was crashed. Can you check this error.

![image](https://user-images.githubusercontent.com/19906349/68471686-46b38c80-0251-11ea-9f2d-0f7fbfb434e4.png)

**Comment by MickeyMiao7** [comment]
Hi, we met the issue. Is there any update or patching plan?

**Comment by dannyrb** [comment]
I haven't had time to investigate this, but I am more than happy to accept a PR
