### ISSUE TITLE
Custom Tools: Bundling without Cornertone Tools

### ISSUE THREAD

**Issue by lyan2000** [cornerstonejs/cornerstoneTools#1130]
### Prerequisites

* [X] Which version are you using? (Is it latest?) 4.6.2
* [X] Are you reporting to the correct repository? Yes
* [X] Did you search existing issues? (Were any related?) Yes, searched. No related found

### Steps to Reproduce the issue [NA]

We would like to extend BaseTool/BaseAnnotationTool to create our own tools. We are using similar approaches to create our own webpack bundle. We would like to reference the cornerstone library externally. If I use import then my bundle would include cornerstone, which is not desirable.

Currently I use something like

```
export default function myTool() {
  const { cornerstoneTools, cornerstone } = external;
  const BaseTool = cornerstoneTools.import('base/BaseTool');

  class MyTool extends BaseTool {
    constructor(configuration = {}) {
      const defaultConfig = {
        name: 'My',
        strategies: ...
        supportedInteractionTypes: ['Mouse', 'Touch'],
        configuration: {
          ;

        },
      };
      const initialConfiguration = Object.assign(defaultConfig, configuration);

      super(initialConfiguration);
    }

    :
  }

  return MyTool;
}
```

Is there a better way to do this? thanks!

**Comment by dannyrb** [comment]
@lyan2000, can you import `cornerstone` directly, but then use Webpack `externals` so your output library knows where/how to find cornerstone later?

https://webpack.js.org/configuration/externals/
