### ISSUE TITLE
ionic app rendering issue for second image 

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstoneTools#1135]
Hello I am rendering the dicom image into ionic app for android as well as for ios. while rendering there is a series of images i am pushing it into stack after applying scroll event I can view the next image. but while rendering that 2nd image i am facing some rendering issue, I think issue related to canvas width and height related. 

This is the first image which renders correctly.

![image](https://user-images.githubusercontent.com/2580866/69405545-fbf04500-0d25-11ea-9a4a-bb4b1b97f546.png)

but the second image renders like this.

![image](https://user-images.githubusercontent.com/2580866/69405932-eaf40380-0d26-11ea-9690-db5e0a2c3a6e.png)

**css**
```
.image-canvas-wrapper {
  width: 100%!important;
  height: 80% !important;
  background: black;
}
.image-canvas {
  width: 100% !important;
  height: 100% !important;
}
```
**html code**
```
<div 
  class="image-canvas-wrapper" 
  oncontextmenu="return false" 
  unselectable='on' 
  onselectstart='return false;' 
  onmousedown='return false;'
>
  <!-- DICOM CANVAS TARGET -->
  <div 
    class="image-canvas" 
    oncontextmenu="return false"
  ></div>
</div>
```
**js code**
```
const baseUrl = 'https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/'
const series = [
	'bbmri-53323707.dcm',
	'bbmri-53323851.dcm',	
	'bbmri-53323563.dcm'
]
const imageIds = series.map(seriesImage => `${scheme}:${baseUrl}${seriesImage}`);
var element = document.querySelector('.image-canvas');
cornerstone.loadImage(imageIds[0]).then((image) => {
  cornerstone.displayImage(element, image)
  cornerstoneTools.addStackStateManager(element, ['stack'])
  cornerstoneTools.addToolState(element, 'stack', stack)
})
```
So how can handle this things in ionic app.

**Comment by dannyrb** [comment]
@pmd23, is this the issue you're facing: https://github.com/cornerstonejs/cornerstone/issues/304

**Comment by pmd23** [comment]
yepp :)

**Comment by dannyrb** [comment]
Alright. I'll close this as a duplicate then. You can leverage the workaround called out there, or propose a solution by continuing the discussion there as well.
