### ISSUE TITLE
Is there API documentation or source code to describe how to save and load Annotation and Segmentation? What Annotation and Segmentation data structure are?

### ISSUE THREAD

**Issue by longerking** [cornerstonejs/cornerstoneTools#1137]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Steps to Reproduce the issue

1. When I do add Tools such as LengthTool, FreehandScissorsTool
2. Then I want to save Annotation and Segmentation parameter that I drew on the element  to database of vuejs-dicom App. Attempt to load them the next time user open the application
3. Is there API documentation or source code to describe how to save and load Annotation and Segmentation? What Annotation and Segmentation data structure are?

**Expected behavior:** (What you expected to happen)

**Actual behavior:** (What actually happened)

### CodeSandbox With Reproduction of Issue:
I've added FreehandScissorsTool，but I'm confused about what to do next of saving the Segmentation.
- [FreehandScissorsTool](https://tools.cornerstonejs.org/examples/tools/freehand-scissors.html)

**Comment by JamesAPetts** [comment]
IO using open source libraries is still a work in progress.

Using [dcmjs](https://github.com/dcmjs-org/dcmjs#readme), a library for DICOM manipulation in JavaScript, its possible to interoperate between cornerstoneTools toolState/labelmaps and  DICOM representations.

There are live examples of writing labelmaps to [DICOMSEG](https://dcmjs.netlify.com/createsegmentation/) and annotations to [DICOMSR](https://dcmjs.netlify.com/linearmeasurements/) (sources [here](https://github.com/dcmjs-org/dcmjs/tree/master/examples)).

Although DICOMSEG support is relatively good so far, support for all cornerstone annotations in DICOMSR is lacking, see [an open issue here](https://github.com/OHIF/Viewers/issues/1215).

**Comment by longerking** [comment]
Thanks, @JamesAPetts . I think I need to explain my problem specifically. I have some data in nii (NIFITI) format, and I want to convert it into subdivisions, and then load them on dicom elements. Is this possible? Or is there any way to help me achieve it. Can you give some advice?

**Comment by longerking** [comment]
https://codesandbox.io/embed/priceless-newton-ib1m3

**Comment by zhihli** [comment]
> Thanks, @JamesAPetts . I think I need to explain my problem specifically. I have some data in nii (NIFTI) format, and I want to convert it into segments, and overlay them on the dicom element. is it possible? Is there any way to help me achieve my goal. Can you give me some advice?
@longerking I have the same problem as you，Have you solved it？

**Comment by longerking** [comment]
> > Thanks, @JamesAPetts . I think I need to explain my problem specifically. I have some data in nii (NIFTI) format, and I want to convert it into segments, and overlay them on the dicom element. is it possible? Is there any way to help me achieve my goal. Can you give me some advice?
> > @longerking I have the same problem as you，Have you solved it？

can you make your question clearer? if your problem is like mine, here might be the solution
> https://codesandbox.io/embed/priceless-newton-ib1m3

**Comment by zhihli** [comment]
@longerking yes, I hava a nifti file containing segmentation data，I have seen your example，But I don’t know how to get the required data from nifti and draw it, Can you give me some advice?

**Comment by longerking** [comment]
> @longerking yes, I hava a nifti file containing segmentation data，I have seen your example，But I don’t know how to get the required data from nifti and draw it, Can you give me some advice?

cornerstoneTools load labelMap or segmentation source as an array, so ,the first thing you need to do is convert the nifti(nii or nii.gz) data into numpy array. You could do it via python module NiBabel
> https://nipy.org/nibabel/installation.html

**Comment by zhihli** [comment]
@longerking Thank you for your reply，I will try.   A digression,  are you from China?

**Comment by longerking** [comment]
Yes and hope my answer will help you.

> @longerking Thank you for your reply，I will try. A digression, are you from China?

Yes and hope my answer will help you.

**Comment by zhihli** [comment]
@longerking 你好，能加个联系方式吗, 想请教下具体实现，谢谢

**Comment by longerking** [comment]
> @longerking 你好，能加个联系方式吗, 想请教下具体实现，谢谢

可以，这是我的邮箱： longerking@foxmail.com
