### ISSUE TITLE
Tools not working in Angular 8

### ISSUE THREAD

**Issue by kuehlc** [cornerstonejs/cornerstoneTools#1149]
I am able to get the image to show, but editing the image or dicom is the issue. I tried the examples given, but the "activate" and "enable" functions are seen as non-existent on mouseInput and other actions. I saw something that said those lines are no longer needed, and that you add your own tools. I tried that way with "Pan", but nothing happens after implementation. I don't get any errors. It just does not work regardless of the example I've tried. The code I've included is just one attempt I tried with getting a single image to work with Pan tool. The WADOimage stuff in there is left over from attempts to get dicom functionality to work, but I wanted to try one thing at a time.
![viewercomppart1](https://user-images.githubusercontent.com/22896763/71095406-293be180-2172-11ea-93c4-0639200f55c5.PNG)
![viewercomppart2](https://user-images.githubusercontent.com/22896763/71095410-2b9e3b80-2172-11ea-8742-373aa26dab22.PNG)
![viewercomppart3](https://user-images.githubusercontent.com/22896763/71095418-2d67ff00-2172-11ea-97ef-d78da0c4be51.PNG)

**Comment by dannyrb** [comment]
Can you include code snippets using triple backticks instead of images? If you're using `activate` and `enable`, then you're referencing outdated cornerstone-tools documentation.

**Comment by kuehlc** [comment]
I'm not using activate or enable. That was from a previous try. Currently I'm using addTool and setToolActive with cornerstoneTools.init()

**Comment by kuehlc** [comment]
``` import { Component, OnInit } from '@angular/core';
import $ from 'jquery';
import Hammer from 'hammerjs';
import * as cornerstoneMath from 'cornerstone-math';
import * as dicomParser from 'dicom-parser';
// Cornerstone Libraries
import * as cornerstone from 'cornerstone-core/dist/cornerstone.js';
import * as cornerstoneTools from 'cornerstone-tools';
import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';
// import * as cornerstoneWebImageLoader from 'cornerstone-web-image-loader'

cornerstoneTools.external.$ = $;
cornerstoneTools.external.Hammer = Hammer;
cornerstoneTools.external.cornerstone = cornerstone;
cornerstoneTools.external.cornerstoneMath = cornerstoneMath;

cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
cornerstoneWADOImageLoader.external.dicomParser = dicomParser;

const config = {
  webWorkerPath : '/assets/cornerstoneWADOImageLoaderWebWorker.js',
  taskConfiguration: {
      decodeTask : {
          codecsPath: '/assets/cornerstoneWADOImageLoaderCodecs.js'
      }
  }
};
cornerstoneWADOImageLoader.webWorkerManager.initialize(config);
cornerstoneTools.init();

@Component({
  selector: 'app-viewer',
  templateUrl: './viewer.component.html',
  styleUrls: ['./viewer.component.css']
})
export class ViewerComponent implements OnInit {

  constructor() { }

  ngOnInit() {
        // Enable Canvas
        const canvas = $('.cornerstone-element')[0];
        cornerstone.enable(canvas);
        // ImageId that matches our registered image loader's 'http:' prefix
        // The webImageLoader uses this to make an xhr request to fetch an image
        // Under the hood, it creates a cornerstone "Image" object needed for display
        const imageUrl = 'https://pubs.rsna.org/na101/home/literatum/publisher/rsna/journals/content/radiographics/2018/'
          + 'rg.2018.38.issue-1/rg.2018170120/20171226/images/small/rg.2018170120.fig9b.gif';
        const wadoImageUrl = 'wadouri:https://www.asteris.biz/Keystone/ImageDownload.aspx?ClinicCode=TESTKEYSTONE&ImageId='
          + 'e9833676-1895-1f7c-1117-ffffff171206&ImageType=DicomImage&FrameIndex=0';
        // const wadoImageUrl = 'wadouri:https://pubs.rsna.org/na101/home/literatum/publisher/rsna/journals/content/radiographics/2018/'
        // + 'rg.2018.38.issue-1/rg.2018170120/20171226/images/small/rg.2018170120.fig9b.gif';
        cornerstone.loadImage(wadoImageUrl).then((image) => {
          // Display our loaded image on the target canvas
          cornerstone.displayImage(canvas, image);

          const apiTool = cornerstoneTools[`${'Pan'}Tool`];
          cornerstoneTools.addTool(canvas, apiTool);
          cornerstoneTools.setToolActive('Pan', { mouseButtonMask: 1 });
        });
  }

}

**Comment by kuehlc** [comment]
Here is the same class in the way that you asked to see it. Hope this helps.

**Comment by dannyrb** [comment]
```js
const apiTool = cornerstoneTools[`${'Pan'}Tool`];
cornerstoneTools.addTool(canvas, apiTool);
cornerstoneTools.setToolActive('Pan', { mouseButtonMask: 1 });
```

`const apiTool = cornerstoneTools[`${'Pan'}Tool`];`

You're using string interpolation to concatenate two string. You can access the property directly:

`const panToolClass = cornerstoneTools.PanTool;`

[There are two ways to add a tool](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/addTool.js#L35-L52):

```js
cornerstoneTools.addTool( ToolClass, ToolProps );

cornerstoneTools.addToolForElement( CornerstoneEnabledElement, ToolClass, ToolProps );
```

The `setToolActive` call looks okay 👍 

Your code becomes:

```js
const PanToolClass = cornerstoneTools.PanTool;
cornerstoneTools.addTool(PanToolClass);
cornerstoneTools.setToolActive('Pan', { mouseButtonMask: 1 });
```

If you're use case is simple enough, you may want to init `cornerstoneTools` with [`globalToolSyncEnabled`](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/modules/globalConfigurationModule.js#L4) to avoid common timing pitfalls.

```js
cornerstoneTools.init({
  globalToolSyncEnabled: true,
});
```

You'll also likely want to shift your library setup logic to a separate module that you call at an appropriate time/place.

**Comment by kuehlc** [comment]
The string interpolation was a change for a way I saw in an example. The other method you mentioned was my original way. I was planning to separate this after getting basic functionality to work. I'll try out the globalsync to see if that works. I'm, rewriting an existing app that used an older version of the tools. This link will show what it will eventually be like. http://images.rsna.org/index.html?doi=10.1148/radiol.2019182718&fig=fig1

**Comment by kuehlc** [comment]
It looks like the globalToolSyncEnabled works! Is there documentation on timing for this type of thing? I agree that this should be separated with proper timing

**Comment by kuehlc** [comment]
@dannyrb

**Comment by dannyrb** [comment]
👋 @kuehlc 

> Is there documentation on timing for this type of thing?

Sort-of-kind-of-not-really.

Cornerstone Tools gives you incredibly granular control over which tools are added, how they're configured, and their current bindings _per_ enabled element. In previous versions of `cornerstone-tools` this was more evident as most top level API calls required you to specify the enabled element you want to apply the change to.

While having that kind of control is nice, in reality, the majority of our consumers want each enabled element to have the same tools, configured the same way, with the same bindings.

In `@3`, we created convenience methods like `addTool`. Normally, when you call `addTool`, under the hood, it calls `addToolForElement` for all currently enabled cornerstone elements. However, elements enabled after the `addTool` call would not have that tool.

When the `globalToolSyncEnabled` flag is enabled, `addTool` still calls `addToolForElement` for all currently enabled elements, but it also tracks the call in an internal ledger. Any elements that are enabled "after the fact" have the same call applied to them. This simplifies things quite a bit for the majority of use cases.
