### ISSUE TITLE
simple way to loop the stack?

### ISSUE THREAD

**Issue by tommy-qichang** [cornerstonejs/cornerstoneTools#1158]
### Prerequisites

* [latest ] Which version are you using? (Is it latest?)
* [yes ] Are you reporting to the correct repository?
* [ yes] Did you search existing issues? (Were any related?)

### Description
I think I got lost and couldn't find any helpful documents for this simple function.
I saw the StackScrollMouseWheelTool class has set the loop to false as default. How can I set it as true?
It's a very simple question, but I'm not sure how to modify it elegantly. 

### Steps to Reproduce the issue

1.   cornerstoneTools.addTool(StackScrollMouseWheelTool);

2.  cornerstoneTools.setToolActive('StackScrollMouseWheel', {mouseButtonMask: 1, **loop:true**}); //doesn't work

**Comment by dannyrb** [comment]
Configuration is set at time of tool instantiation. It's a way to create tools with different behaviors, despite being derived from the same tool class. They can't* be changed after add.

Options, like `mouseButtonMask`, are meant to be changed while the tool is in use to influence behavior.

```js
import csTools from 'cornerstone-tools';

csTools.addTool(csTool.StackScrollMouseWheelTool, {
  configuration: { loop: true }
});
```

### `StackScrollMouseWheelTool`

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/StackScrollMouseWheelTool.js#L13-L22

### `addTool(ToolClass, props)`

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/addTool.js#L36-L52

**Comment by tommy-qichang** [comment]
Got it. Thank you for your help!
