### ISSUE TITLE
the pointInFreehand Error

### ISSUE THREAD

**Issue by zzfzfz** [cornerstonejs/cornerstoneTools#1160]
### Prerequisites

* [4.9.0] Which version are you using? (Is it latest?)
* [Yes] Are you reporting to the correct repository?
* [No] Did you search existing issues? (Were any related?)

### Description
When I use the pointInFreehand to determine whether a point is inside a polygon, I find an error.
A ponit is inside a polygon but the pointInFreehand return false
### Steps to Reproduce the issue

1. Modifying test cases in the file FreehandMouseTool.test
```
describe('pointInFreehand.js', function() {
  // Simple square
  const dataHandles = [
    new FreehandHandleData({
      x: 0.0,
      y: 0.0,
    }),
    new FreehandHandleData({
      x: 0.0,
      y: 1.0,
    }),
    new FreehandHandleData({
      x: 1.0,
      y: 0.0,
    }),
  ];

  it('should return true if the point is inside the polygon', function() {
    const point = {
      x: 0.1,
      y: 0.8,
    };
    const isInside = pointInFreehand(dataHandles, point);

    expect(isInside).toBeTruthy();
  });
})
```
2. npm run test
3. I see error
![image](https://user-images.githubusercontent.com/19834927/71792502-e768d180-3073-11ea-8d0a-2fc8cc88e7b7.png)

**Comment by DStar2013** [comment]
:+1: yep，same problem.

there are some problems with  util/pointInFreehand. 
- lineSegmentAtPoint(Returns the y value of the line segment at the x value of the point.) y value should be lp1.y + dydx * (point.x - lp1.x)
- isLineRightOfPoint(Returns true if the line segment is to the right of the point.) need to take gradient.

Commit solves. Can submit a PR for this ? :wink:  @zzfzfz  @dannyrb

**Comment by dannyrb** [comment]
@DStar2013, that would be wonderful ^_^

CC: @JamesAPetts

**Comment by JamesAPetts** [comment]
I've just stumbled across this myself! A PR would be awesome and I'd be happy to review it.
