### ISSUE TITLE
Series Synchronisation and Layout tools

### ISSUE THREAD

**Issue by jaizz2003** [cornerstonejs/cornerstoneTools#1162]
I am trying to build a Synchronization feature in which different series under the same study can be synchronized ( like we have 3 series and I want to scroll the images in all 3 at the same time) so I want to ask are these features already implemented?

I need help in creating these new tools using cornerstone-tool, guide me on how to proceed?

**Comment by jaizz2003** [comment]
Regarding the Layout, Yes it is already implemented and we can extend the size of the grid to any size we want as OHIF viewers have this support and there is no support for series synchronization as much as I find so I am still stuck there.

**Comment by dannyrb** [comment]
Your synchronization question is duplicated here: https://github.com/OHIF/Viewers/issues/1060

## Synchronizers

A synchronizer:

- Is tied to a specific event
- Has a handler for that event
- Has "source" enabled elements
- Has "target" enabled elements

When the event is emitted from a "source" element, the handler is used. Often updating/synchronizing the "target" elements.

## OHIF

If you're trying to implement this in OHIF, I'd recommend the following approach. 

### Assumptions:

- When _any_ viewport's imageIdIndex changes, you want all viewports to update to match
- If other viewport's indexes are out of range of the new index, scroll to their boundary index

### Approach:

All of this logic should live in the `@ohif/extension-cornerstone` extension. It lives in the `OHIF/Viewers` monorepo under `<root>/extensions/cornerstone`. If you're unfamiliar with OHIF extensions, [I recommend reading the docs](https://docs.ohif.org/extensions/)

- Create a [new command](https://docs.ohif.org/extensions/modules/commands.html) that we'll use to toggle the synchronizer on/off
- Create a [new toolbar button](https://docs.ohif.org/extensions/modules/toolbar.html) that calls that command

You have a couple of different options for the logic of the command. You can:

- Add an event listener that listens for created/destroyed enabled elements
    - On create, add a listener for the created enabled element
    - On destroy, remove a listener for the destroyed enabled element
- Add/remove event listeners for all currently enabled elements
- Handle the event with a function that applies the synchronization logic
    - Be careful not to cause an infinite loop
    - Use the event information and cornerstone's API to update/sync each viewport

If you prefer the API that traditional synchronizers provided, you have the option to create one in the extension. Then your command can simply enable/disable the synchronizer. However, you would still need to:

- Monitor for created/destroyed enabled elements
- Potentially track the "active viewport" (or write a handler that doesn't need to know which viewport is active)

**Comment by jaizz2003** [comment]
@dannyrb I am trying to integrate crosshairs and Reference line tools to OHIF viewer(as they already present in cornerstoneTool) using cornerstoneTools, now I have few questions and problems -:
1) I tried to replicate the way I integrated CobbAngle tool to OHIF viewer but I am getting `Cannot read property 'getSourceElements' of undefined`, now I believe this is not the right way to do it, so I need to ask how to get the source and target info using OHIF viewer and send it to Synchronizer in CornerstoneTools.js.
2) I went through Cornerstone and OHIF viewer codes and I don't know exactly how those two are interconnecting? ( I used yarn link to link both)
3) There are files like angle.js, length.js which contains some export method in OHIF viewer repository, now do I have to write it myself for crosshairs or I can import it from cornerstoneTool?
4) Is the synchronizer is written for crosshairs, will it be sufficient to make some changes in it to use it for my own series Synchronizer or I have to write a new separate one?

**Comment by jaizz2003** [comment]
@dannyrb I finally able to implement it. Thanks for the help!!!

**Comment by najimhashgraph** [comment]
Hi @jaizz2003,

I have the same issues, and need also Reference line tools and synchronizing series. I want to use ohif in a multireader study, the radiologist need this to make a good assessment otherwise it creates big limitations. Can you help me? Do you have an instance i can fork or a roadmap how to implement this? 
I hope you can help me.

Thank you in advance.

Greetings,

Najim

**Comment by jaizz2003** [comment]
Hi @najimhashgraph,
To achieve this task, I used CornerstoneTools [https://github.com/cornerstonejs/cornerstoneTools](url) project as an extension and updated it as all the basic/advanced tools in OHIF viewer are taken from that project itself. In that project's src/tools, you will have SeriesSyncTool.js and in src/synchronisation there is another file named Synchroniser. These two files are required for synchronisation of series, you can create a synchroniser in SeriesSyncTool.js and attach the event that you want to trigger the synchronisation.
`const count = 0;

    if (!this.sync) {
      this.sync = new synchronizer('cornerstonetoolsstackscroll', handler);
    }
    if (Object.keys(store.state.enabledElements).length !== count) {
      this.sync.addSource(this.element);
      store.state.enabledElements.forEach(element => {
        this.sync.addTarget(element);
      });
    }`

The above code I have written in _dragcallback(event) method and this creates a new synchroniser and I added source and added the Target. Here I am adding for each enabled element (current series layout (4x1 or 1x1)). Synchroniser handles every task though so main task was to add the Source and Target because these methods handles when to trigger and which one to trigger with mouse dragging.
Please feel free to ask any doubts.
Good Luck!!

**Comment by sinanmb** [comment]
@jaizz2003 for reference lines you can checkout this solution https://github.com/OHIF/Viewers/pull/1482

@jaizz2003, thank you for providing more information on how to implement synchronization. Do you mind sharing your `SeriesSyncTool.js` files with us please? 
In your cone snippet above, I'm not sure what the handler method should do.

**Comment by najimhashgraph** [comment]
Hi @jaizz2003 ,

Thank you for sharing your approach.
I can also not find the file SeriesSyncTool.js in cornerTools, is it possible to share it or can i find it in an other location?

Thanx,

Najim

**Comment by jaizz2003** [comment]
I apologise for posting a response too late ( got caught up in college work).
Here is my whole SeriesSyncTool.js code that I've used.
This code is connected to Synchronizer so if you don't understand anything just trace back and find the flow like how synchronizer is handling the triggered events and then you can even improve the performance of this code. 
Please feel free to ask any doubts.

```
import handler from '../synchronization/stackScrollSynchronizer.js';
import BaseTool from './base/BaseTool.js';
import store, { getModule } from '../store';
import synchronizer from '../synchronization/Synchronizer.js';
import scroll from '../util/scroll.js';
import { getToolState } from '../stateManagement/toolState.js';
import { setToolOptions, getToolOptions } from '../toolOptions.js';
import { stackScrollCursor } from './cursors/index.js';

/**
 * @public
 * @class StackScrollTool
 * @memberof Tools
 *
 * @classdesc Tool for scrolling through a series.
 * @extends Tools.Base.BaseTool
 */
export default class SeriesSyncTool extends BaseTool {
  constructor(props = {}) {
    const defaultProps = {
      name: 'SeriesSync',
      supportedInteractionTypes: ['Mouse', 'Touch'],
      configuration: {
        loop: false,
        allowSkipping: true,
      },
      svgCursor: stackScrollCursor,
    };

    super(props, defaultProps);

    this.mouseDragCallback = this._dragCallback.bind(this);
    this.touchDragCallback = this._dragCallback.bind(this);
  }

  _dragCallback(evt) {
    const count = 0;

    if (!this.sync) {
      this.sync = new synchronizer('cornerstonetoolsstackscroll', handler);
    }
    if (Object.keys(store.state.enabledElements).length !== count) {
      this.sync.addSource(this.element);
      store.state.enabledElements.forEach(element => {
        this.sync.addTarget(element);
      });
    }
    const eventData = evt.detail;
    const { element, deltaPoints } = eventData;
    const { loop, allowSkipping } = this.configuration;
    const options = getToolOptions(this.name, element);

    const pixelsPerImage = this._getPixelPerImage(element);
    const deltaY = this._getDeltaY(element, deltaPoints.page.y);

    if (!pixelsPerImage) {
      return;
    }

    if (Math.abs(deltaY) >= pixelsPerImage) {
      const imageIdIndexOffset = Math.round(deltaY / pixelsPerImage);

      scroll(element, imageIdIndexOffset, loop, allowSkipping);

      options.deltaY = deltaY % pixelsPerImage;
    } else {
      options.deltaY = deltaY;
    }

    setToolOptions(this.name, element, options);
  }

  _getDeltaY(element, deltaPointsY) {
    const options = getToolOptions(this.name, element);
    const deltaY = options.deltaY || 0;

    return deltaY + deltaPointsY;
  }

  _getPixelPerImage(element) {
    const toolData = getToolState(element, 'stack');

    if (!toolData || !toolData.data || !toolData.data.length) {
      return;
    }

    const stackData = toolData.data[0];
    const { stackScrollSpeed } = this.configuration;

    // The Math.max here makes it easier to mouseDrag-scroll small or really large image stacks
    return (
      stackScrollSpeed ||
      Math.max(2, element.offsetHeight / Math.max(stackData.imageIds.length, 8))
    );
  }
}
```

**Comment by najimhashgraph** [comment]
Hi @jaizz2003 ,

Thank you for sharing, did you implement this in  the directory of Viewers\extensions\cornerstone\src or somewhere else in ohif?

Kind regards,
Najim

**Comment by jaizz2003** [comment]
Hey @najimhashgraph ,
`custom-ohif/cornerstoneTools-master/src/tools/SeriesSyncTool.js`

above is the complete path, I am using cornerstoneTools ( it's the js library that handles all the tools in our viewer) and you need to link to our main repository of viewer using yarn link.
I have not changed much just added this file in tools under cornerstoneTools project.

**Comment by najimhashgraph** [comment]
Hi @jaizz2003, 

thank you for the additional information, I used Yarn link for a cloned cornestoneTools where I added the SeriesSyncTools.js, the ohif viewer shows it is linked to this instance but I see nothing happen. As so far my understanding goes of the ohif viewer, in the extension/cornerstone/src directory is a init file do I have to call something in there to add the synchronisation?

Kind regard,
najim

**Comment by jaizz2003** [comment]
Dear @najimhashgraph ,
Yes you have to make changes in init, there are alot of init files I don't remember which one exactly I tackled ( It's been over 8 months since I worked on this project), please see the flow of data and the connections between different files, that will help you alot.
Good Luck!

**Comment by najimhashgraph** [comment]
Hi @jaizz2003,

I think I am almost there, I am struggling with the last step, 
how did you implement the SeriesSyncTool in Viewers/extension/cornerstone/src/init.js. I tried all kind of ways using csTools.setToolActive, adding to toolsGroupedByType, calling it as an function but with no success. But when I use the tool in cornerstoneTools in the index file it seems to work.
Can you help me with this last step, and share how you implemented this in ohif in Viewers/extension/cornerstone/src/init.js file.

Thanks

Kind regard,
Najim

**Comment by najimhashgraph** [comment]
Hi @jaizz2003,

I have figured it out! Thanks for your help and sharing your approach.

Kind regards,
Najim

**Comment by uuutangmeihua** [comment]
I checked the document and didn't understand some places. I didn't know how to expand the synchronization tool and reference line tool. But there is no seriessynctool under my ohif project JS and synchronizer files

**Comment by uuutangmeihua** [comment]
> SeriesSyncTool
I checked the document and didn't understand some places. I didn't know how to expand the synchronization tool and reference line tool. I will directly copy the stackscrolltool of cornerstonetools JS file is copied to the extension \ cornerstone \ SRC \ tools path of ohif project. How else do you need to implement it?

**Comment by uuutangmeihua** [comment]
> * 使用事件信息和基石的 API 更新/同步每个视口

Thank you for your contribution to the synchronization guide function. I simply realized it according to the guide function file you provided. Would like to consult how to use a custom button to operate the function of enable and disable it? How to enable and disable the synchronization window function separately.
