### ISSUE TITLE
Fix: imageIdSpecificStateManager.js

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstoneTools#1173]
[#1151](https://github.com/cornerstonejs/cornerstoneTools/pull/1151#pullrequestreview-350779595)

**Comment by dannyrb** [comment]
I'm sorry. What's the issue?

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstoneTools/blob/4eef070ee0448ce29cbc1fbc1aedd815cef50dbd/src/stateManagement/imageIdSpecificStateManager.js#L97-L105

I think there was an error, missing the "image" object

```
clearImageIdToolState(enabledElement.imageId);
```
to change:
```
clearImageIdToolState(enabledElement.image.imageId);
```

**Comment by jlopes90** [comment]
I updated the recent version and noticed that it was not working erasing annotations, I looked for this problem

**Comment by dannyrb** [comment]
I think you're right. Are you able to draft a PR? When you apply the changes, does it work as you would expect?

**Comment by jlopes90** [comment]
#1174

**Comment by dannyrb** [comment]
@jlopes90, merged. Please let me know if this resolved your issue and we can close.

**Comment by mikehazell** [comment]
Arrgh.. my bad. Thank you for finding / fixing this @jlopes90

**Comment by dannyrb** [comment]
@mikehazell it's no one's bad when we don't have unit tests :p

Thank you both for your contributions!
