### ISSUE TITLE
How to reset/wipe away ww wl values or tool changes on an image?

### ISSUE THREAD

**Issue by kuehlc** [cornerstonejs/cornerstoneTools#1175]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)
#1076 Seems related, but unsure.

### Description

I want to be able to reset an image/dicom to original state (before any wwwc changes or tool edits).

**Comment by dannyrb** [comment]
https://docs.cornerstonejs.org/api.html#reset

`cornerstone.reset(enabledDomElement)`

Resets `viewport` properties; would not clear annotations

**Comment by kuehlc** [comment]
@dannyrb Thanks! Don't know how I missed that in the docs.

**Comment by ryanyr** [comment]
@dannyrb is there a fuc to clear all annotation?

**Comment by dannyrb** [comment]
@ryanyr , you could clear toolState for a specific imageId, or "restoreToolstate" to a clean slate:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/imageIdSpecificStateManager.js#L115

If you're depending on measurementmodified events, I don't think this would emit them. This would only apply to imageIdSpecific managers, so it's possible you'd have some stack, frameOfReference, etc. Manager still holding on to state.

**Comment by ryanyr** [comment]
> @ryanyr , you could clear toolState for a specific imageId, or "restoreToolstate" to a clean slate:
> 
> https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/imageIdSpecificStateManager.js#L115
> 
> If you're depending on measurementmodified events, I don't think this would emit them. This would only apply to imageIdSpecific managers, so it's possible you'd have some stack, frameOfReference, etc. Manager still holding on to state.

Thanks, it works！
