### ISSUE TITLE
API link is broken

### ISSUE THREAD

**Issue by den10** [cornerstonejs/cornerstoneTools#1178]
### Prerequisites

* [ ] Which version are you using? (Is it latest?)
* [ ] Are you reporting to the correct repository?
* [ ] Did you search existing issues? (Were any related?)

### Steps to Reproduce the issue

1. When I do X
2. Then Y
3. I see behavior Z

**Expected behavior:** (What you expected to happen)

**Actual behavior:** (What actually happened)

### CodeSandbox With Reproduction of Issue:

- [Basic Template](https://codesandbox.io/s/cornerstone-basic-issue-template-9slk4)

**Comment by dannyrb** [comment]
Duplicated here: https://github.com/cornerstonejs/cornerstoneTools/issues/1152
