### ISSUE TITLE
Touch support for mobile

### ISSUE THREAD

**Issue by soumanpaul** [cornerstonejs/cornerstoneTools#1180]
Using in mobile app with WebView, how to enable touch tools like pen, zoom functionality?

**Comment by dannyrb** [comment]
Touch support is enabled by default. Most tools support touch, and some tools are touch only. Generally, if a tool is activated with a "gesture" (like pinch), it has its own variant that needs added and activated: 

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/ZoomTouchPinchTool.js

**Comment by soumanpaul** [comment]
solved

**Comment by AlbinManentia** [comment]
@dannyrb  what about annotation tools like length etc
