### ISSUE TITLE
How can I see the API documentation

### ISSUE THREAD

**Issue by haoxl3** [cornerstonejs/cornerstoneTools#1187]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description
I want to see the API documentation, but the link is broken. How can I see the API documentation? When will the API documentation probably be fixed?

### Steps to Reproduce the issue

**Expected behavior:** (What you expected to happen)

**Actual behavior:** (What actually happened)

### CodeSandbox With Reproduction of Issue:

- [Basic Template](https://codesandbox.io/s/cornerstone-basic-issue-template-9slk4)

**Comment by dannyrb** [comment]
Unfortunately, the automatic API doc generation is not working. There is an open issue that is up for grabs: https://github.com/cornerstonejs/cornerstoneTools/issues/1152
