### ISSUE TITLE
Best to way to send data between two tools

### ISSUE THREAD

**Issue by PierreLeGuen** [cornerstonejs/cornerstoneTools#1192]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description

We are trying to create a feature that requires several custom tools working together. What is the best way to communicate between two tools for example? Is this possible?

**Comment by dannyrb** [comment]
@PierreLeGuen are you able to provide a more concrete example?

**Comment by PierreLeGuen** [comment]
@dannyrb of course.
For example, i've a tool to draw a circle, and an other to draw a line apart from the circle. I want to extract the center of the circle and the start/end of the line. This way I can do some calculations and render a result from them.
Please tell me if I wasn't clear enough.

**Comment by dannyrb** [comment]
@PierreLeGuen, I guess I'm not understanding why these wouldn't be a part of the same tool? I'm not sure we have many good public examples, but I have seen private cornerstone-tools implementations of "multipart" tools that combine multiple shapes to calculate some value.
