### ISSUE TITLE
Custom tool renderring

### ISSUE THREAD

**Issue by sinanmb** [cornerstonejs/cornerstoneTools#1205]
Hi,

I have created a custom tool based on the Probe Tool. All I need is a marker on the viewport, with the measurement number displayed next to it (the index of the measurement in the measurement table)

How can I use a custom rendering method, given I can't access the `draw` method (in drawing.index.js) from my custom tool file?

**Comment by dannyrb** [comment]
If you're authoring a 3rd party tool, you extend the BaseAnnotation tool class and implement a render function. The render function is run on each "draw" and often uses "tool state" to inform the draw.

If you look at BaseAnnotation, it provides some guidance around the methods you can implement. If you know your tool is similar to an existing one, cracking it open often provides a lot of insight.

The only notable exception is that tools not bundled with CornerstoneTools may need to use the "getInternalModule" (if I'm remembering the name correctly) to access the library internals exposed in the top level `lib.js` folder. This is where we keep API that's more for advanced users and tool authors

**Comment by sinanmb** [comment]
Hi @dannyrb,

Thank you very much! That was very helpful and I was able to import the methods I needed using
`const draw = csTools.importInternal('drawing/draw');`
