### ISSUE TITLE
Cornerstone Tools Synchronizers - Usage

### ISSUE THREAD

**Issue by Sriram-Ananth** [cornerstonejs/cornerstoneTools#1207]
### Prerequisites

* [x] Which version are you using? v4.12.5
* [x] Are you reporting to the correct repository? Yes
* [ ] Did you search existing issues? (Were any related?) Yes

Not really an issue. Just wanted to know the correct way to switch between synchronizers. 
For example I first initialize a Stack Image Position Synchronizer as follows:

      var synchronizer = new cornerstoneTools.Synchronizer(
        'cornerstonenewimage',
        cornerstoneTools.stackImagePositionSynchronizer)

     < add the elements to the synchronizer with>
          synchronizer.add(element);

      cornerstoneTools.setToolActiveForElement(element, 'StackScroll', { mouseButtonMask: 1, synchronizationContext: synchronizer, });

Now if I want to switch to the Stack Image Index Synchronizer, what is the correct way? Should I just create a new Synchronizer object and add it to the tools?

Thanks in advance for any help. Regards

**Comment by dannyrb** [comment]
@Sriram-Ananth, yes. You can create a new synchronizer if you have alternative behavior you would like to synchronize.. In a recent-ish update, we also made it possible to toggle a synchronizer on/off:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/synchronization/Synchronizer.js#L37

So you might set it's `enabled` property to `false`, and then instantiate/enable the other synchronizer.

**Comment by Sriram-Ananth** [comment]
That worked like a charm. Thank you for the prompt assistance.
