### ISSUE TITLE
 why ReferenceLinesTool always show line

### ISSUE THREAD

**Issue by wmxj** [cornerstonejs/cornerstoneTools#1208]
1 cornerstoneTools'version is 4.13.0
2 i want only non current window and ifferent position show line,but why ReferenceLinesTool always show line in every window

addReferenceLine() {
	 //delete history
	this.windowData.forEach(_window => {
		let _element = this.$refs[_window.id][0];
		synchronizerLine.remove(_element);
		//it seems that this code doesn't work
		cornerstoneTools.removeToolForElement(_element, cornerstoneTools.ReferenceLinesTool);
	});
	//current window
	let element = this.$refs[this.currentWindow][0];
	let currentElementData = cornerstone.getEnabledElement(element);
	let currentType = tool.getImageType(currentElementData.image);
	this.windowData.forEach(_window => {
		let _id = _window.id;
		let _element = this.$refs[_id][0];
		let _enabledElement = cornerstone.getEnabledElement(_element);
		let _positionType = tool.getImageType(_enabledElement.image);
		//only current window or different position add ,but current window don't need show line
		if (_id == this.currentWindow) {
			synchronizerLine.add(_element);
		} else if (_positionType != currentType) {
			synchronizerLine.add(_element);
			cornerstoneTools.addToolForElement(_element, cornerstoneTools.ReferenceLinesTool);
		}
	});
	cornerstoneTools.setToolEnabled('ReferenceLines', {
		synchronizationContext: synchronizerLine
	});

}

**Comment by dannyrb** [comment]
Please add your code as text with formatting, using triple backticks

```js
function example() {
  // do stuff
}
```

**Comment by wmxj** [comment]
[code.txt](https://github.com/cornerstonejs/cornerstoneTools/files/4424693/code.txt)

**Comment by wmxj** [comment]
![1](https://user-images.githubusercontent.com/1752767/78322506-859c0300-75a1-11ea-868b-e82be58e32a5.jpg)

**Comment by wmxj** [comment]
It 's finally solved. we need to add this 'cornerstone.updateImage(element)'  after 'removeToolForElement'

**Comment by wmxj** [comment]
synchronizerLine.remove(_element);
						cornerstoneTools.removeToolForElement(_element,'ReferenceLines');
						cornerstone.updateImage(_element);

**Comment by wangtiechuan** [comment]
const renderLine = (wdinfo: WindowViewInfo) => {
      const wd = wdinfo;
      const thiswin = wd.windows[wd.windowActiveIndex];
      const viewIndex = thiswin?.viewActiveIndex || 0;
      const viewportIndex = createElId(wd.windowActiveIndex!, viewIndex!);

      if (viewportIndex === preViewportIndex) {
        return;
      }

      preViewportIndex = viewportIndex;

      clearSynchronizer();

      const currentElement = this.getEnabledElement(viewportIndex);
      // console.log(currentElement);

      const apiTool = this.getToolName(toolName);

      const otherElement = enabledElements.filter((el) => el !== currentElement);

      const preSync = (
        enabledElement: any,
      ): Promise<{ enabledElement: any; synchronizer: any }> => {
        const synchronizer = new cornerstoneTools.Synchronizer(
          cornerstone.EVENTS.NEW_IMAGE,
          cornerstoneTools.updateImageSynchronizer,
        );

        const stackData = this.getStackData(enabledElement);
        const imageIds = stackData?.imageIds;

        return new Promise((resolve) => {
          cornerstone.loadImage(imageIds[0]).then((image) => {
            synchronizer.add(enabledElement);
            resolve({
              enabledElement,
              synchronizer,
            });
          });
        });
      };

      preSync(currentElement)
        .then((currentElsyncInfo) => {
          this.referenceLineSynchronizer.push(currentElsyncInfo.synchronizer);
          cornerstone.updateImage(currentElement);

          const synchronizerPromise = otherElement.map(preSync);
          Promise.all(synchronizerPromise).then((synchronizerInfos) => {
            this.addTool(toolName);
            cornerstoneTools.removeToolForElement(currentElement, toolName);

            synchronizerInfos.forEach((synchronizerInfo) => {
              synchronizerInfo.synchronizer.add(currentElement);

              const config = {
                synchronizationContext: synchronizerInfo.synchronizer,
              };

              cornerstoneTools.addToolForElement(currentElement, apiTool);
              cornerstoneTools.setToolEnabledForElement(
                synchronizerInfo.enabledElement,
                toolName,
                config,
              );
            });
          });
        })
        .catch((e) => {
          console.log('定位线绘制失败', e);
        });
    };
