### ISSUE TITLE
How can I use the source code for development?

### ISSUE THREAD

**Issue by Hynn01** [cornerstonejs/cornerstoneTools#1222]
### Prerequisites

* [It is latest] Which version are you using? (Is it latest?)
* [yes] Are you reporting to the correct repository?
* [yes, but can't find related issue.] Did you search existing issues? (Were any related?)

### Description
Question 1:
I want to change the source code for development, but I saw the demo uses the released version and uses a link to link to the library. I put the below links into comment, and add the row "import cornerstoneTools from './src/index.js';" in the index.html, but it doesn't work. 
![image](https://user-images.githubusercontent.com/26082974/79481660-62ae2c00-8042-11ea-918f-8e9219d50181.png)
Instead, the console shows this error.
![image](https://user-images.githubusercontent.com/26082974/79481917-b1f45c80-8042-11ea-90f2-39d0b5f4d057.png)
Could you tell me what it is the right way to develop using the source code? I am not very familiar with this...

Question 2:
I want to make a list(like [[(x1,y1,z1),(w1,h1)],[(x2,y2,z2),(w2,h2)],[(x3,y3,z3),(w3,h3)]]) showed by rectangleRoiTool in different stacks(z layer) automatically, instead of human adding the rectangle. Is it possible to implement?
I find these issues similar to what I want to implement, but they just showed how to use the rectangleRoiTool on one stack. I still have no idea how to use it on different stacks?
https://github.com/cornerstonejs/cornerstoneTools/issues/358
https://github.com/cornerstonejs/cornerstoneTools/issues/409

Thank you!

**Comment by dannyrb** [comment]
```
# restore dependencies
npm install

# watch source for changes; rebuild when changes are detected
npm run dev
```

Open `src/index.html` in a browser. Refresh after changes to see them applied.


----

Ideally, we would nuke the less-than-stellar `/examples` directory, and use something like `HtmlWebpackPlugin` and the WebPack Dev Server to serve up something like `src/index.html` in a more developer friendly way.

**Comment by Hynn01** [comment]
Okay, thank you very much!
