### ISSUE TITLE
API Docs link broken

### ISSUE THREAD

**Issue by sjohns0828** [cornerstonejs/cornerstoneTools#1230]
When I navigate to https://tools.cornerstonejs.org/api/ to view the api docs, I get a 404 error. Has the documentation been moved elsewhere?

**Comment by dannyrb** [comment]
See: https://github.com/cornerstonejs/cornerstoneTools/issues/1152

This was a simple API explorer created by parsing the libraries JS Doc. If you need a quick overview, check out index.js and lib.js in src/
