### ISSUE TITLE
Polygon ROI

### ISSUE THREAD

**Issue by cancan101** [cornerstonejs/cornerstoneTools#125]
Along the lines of the rectangle ROI but with the ability to specify multiple knot points.

Something like this: http://ttic.uchicago.edu/~smaji/projects/mturk/interfaces/segmentation/person.html?category-image=person,2011_000745_10.jpg which has some cool features for detecting a closed polygon and indicating such (floating dot gets larger when near initial point).

Also see OsiriX which has the feature albeit with some smoothing offered:
https://osirixpluginbasics.wordpress.com/2010/11/27/polygon-roi-tcpolygon-topolygon-tpencil/

**Comment by cancan101** [comment]
The polygon tool is basically a specific version of: https://github.com/chafey/cornerstoneTools/issues/35.

Perhaps the freehand tool just needs an option to always force the "straight line mode".

**Comment by snagytx** [comment]
this would be something nice to have, looking forward to this.

**Comment by dannyrb** [comment]
@JamesAPetts, I believe the freehand tool more closely resembles what this issue wanted to accomplish. Is that correct?

This issue has seen little activity in 2-years, so I'll close it for now. Feel free to comment if my assumptions are off, or if there are relevant action items for our freehand tool.
