### ISSUE TITLE
How can I save an object (example: ruler, rectangle and etc) in JSON and load and draw it then?

### ISSUE THREAD

**Issue by LexaDel** [cornerstonejs/cornerstoneTools#1250]
Hey! 

How can I save an object (example: ruler, rectangle and etc) in JSON and load and draw it then?

**Comment by cpinchuk** [comment]
This will collect your annotations to JSON

let allROIToolData = {};
            let toolROITypes = ['EllipticalRoi', 'RectangleRoi', 'ArrowAnnotate', 'Length', 'CobbAngle', 'Angle','Bidirectional', 'FreehandRoi', 'Calibration']; // whatever the types you are using and wanting to save

            for (let i = 0; i < toolROITypes.length; i++) {

                let toolROIType = toolROITypes[i];
                let toolROIData = cornerstoneTools.getToolState(myCanvas, toolROIType);

                if (toolROIData !== undefined) {
                    allROIToolData[toolROITypes[i]] = toolROIData;
                }
            }
            let toolROIDataString = JSON.stringify(allROIToolData);

**Comment by cpinchuk** [comment]
This will load them.

 let allROIToolData = JSON.parse(myJSONStingData);
                for (let toolROIType in allROIToolData) {
                    if (allROIToolData.hasOwnProperty(toolROIType)) {
                        for (let i = 0; i < allROIToolData[toolROIType].data.length; i++) {
                            let toolROIData = allROIToolData[toolROIType].data[i];
                            cornerstoneTools.addToolState(myCanvas, toolROIType, toolROIData);
                        }
                    }
                }
                cornerstone.updateImage(myCanvas);

**Comment by LexaDel** [comment]
thanks, i'll try it ))

**Comment by LexaDel** [comment]
@cpinchuk Hello! Maybe you know, how to save Brush tool? I suggest, I can save only ROI tools?
