### ISSUE TITLE
[bug] problems occur when using overlays and annotations at the same time

### ISSUE THREAD

**Issue by ssky10** [cornerstonejs/cornerstoneTools#1311]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description
I would like to add an annotation on top of the cornerstone viewport where I loaded the png image using `context.drawImage()`.

However, Zoom or Pan function works normally when annotations are not added, but when annotations are added, the rest of the elements other than annotations do not work normally.

Also, the overlayTool provided by CornerstoneTool has the same problem.

### Steps to Reproduce the issue

1. When scrolling for the first time in CodeSandbox below, Zoom functions normally, such as a dice png image, a white overlay, and a rectangle in the upper left corner.
2. However, Zoom behaves abnormally as soon as you add text annotations by left-clicking the mouse.
3. This is the same with the cornerstoneTool's wwwc, pan, cornerstone rotates, etc.

### CodeSandbox With Reproduction of Issue:

https://codesandbox.io/s/sleepy-paper-uqj4p?fontsize=14&hidenavigation=1&theme=dark

**Comment by codepage949** [comment]
https://github.com/cornerstonejs/cornerstoneTools/blob/79660e9bc95a9237fd713eaf6e5f2182fca51c3f/src/tools/annotation/TextMarkerTool.js#L124-L147

https://github.com/cornerstonejs/cornerstoneTools/blob/79660e9bc95a9237fd713eaf6e5f2182fca51c3f/src/drawing/getNewContext.js#L12-L18

https://github.com/cornerstonejs/cornerstoneTools/blob/79660e9bc95a9237fd713eaf6e5f2182fca51c3f/src/drawing/draw.js#L13-L17

during drawing of TextMarker, it resets canvas' context by calling `setTransform(...)` in `getNewContext(...)` and it affects other things.

saving and restoring canvas' context in below `draw(...)` seems late.

there are more tools which call `getNewContext(...)` besides TextMarkerTool.

i think it needs to update saving and restoring canvas' context for those tools.
