### ISSUE TITLE
Is there a way to manually switch the currentImageIdIndex in the stack?

### ISSUE THREAD

**Issue by ULQUIARROSYX** [cornerstonejs/cornerstoneTools#1323]
### Prerequisites

* [√ ] Which version are you using? (Is it latest?)
* [√ ] Are you reporting to the correct repository?
* [√ ] Did you search existing issues? (Were any related?)

### Description

I need a function in my project like this: click the button to switch the currentImageIdIndex of the stack in nii.gz, but I can’t find the corresponding api at present

### Steps to Reproduce the issue
1. Clear the current state
2. Modify currentImageIdIndex
3. AddToolState
4. UpdateImage

**Expected behavior:** (What you expected to happen)
The page displays a picture with index 1

**Actual behavior:** (What actually happened)
The data has changed. But the page has not changed (cornerstoneimagerendered triggered)

**Comment by mikehazell** [comment]
Hey @ULQUIARROSYX, what you're probably looking for is `scrollToIndex`.

This is a slightly hidden API which you can access via `cornerstoneTools.importInternal('util/scrollToIndex')`

You can use it like this:

```js
const scrollToIndex = cornerstoneTools.importInternal('util/scrollToIndex');

const newIndex = 21;
scrollToIndex(this.element, newIndex);
```

Limited docs on `importInternal` can be found here: https://tools.cornerstonejs.org/third-party-functionality/#imports

You can find the list of "internal" things you can access here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/lib.js

**Comment by ULQUIARROSYX** [comment]
> Hey @ULQUIARROSYX, what you're probably looking for is `scrollToIndex`.
> 
> This is a slightly hidden API which you can access via `cornerstoneTools.importInternal('util/scrollToIndex')`
> 
> You can use it like this:
> 
> ```js
> const scrollToIndex = cornerstoneTools.importInternal('util/scrollToIndex');
> 
> const newIndex = 21;
> scrollToIndex(this.element, newIndex);
> ```
> 
> Limited docs on `importInternal` can be found here: https://tools.cornerstonejs.org/third-party-functionality/#imports
> 
> You can find the list of "internal" things you can access here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/lib.js

That's exactly what I want, thank you!
