### ISSUE TITLE
How to use stackScroll tool to show two layers on one canvas?

### ISSUE THREAD

**Issue by zhihli** [cornerstonejs/cornerstoneTools#1339]
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description
Thans for your great work ! 
I have a file of dicom list, and a nifti file, I want to use layer to fuse these two files，dicom is base layer，nifti is overlay,  I found this example  
https://github.com/paul-asvb/cornerstoneTools/blob/preservelayeredImageStacks/examples/layeredImageStacks/index.html
I referenced it, but I didn't meet my needs, so,  Do you have any suggestions for me？thanks !

### Steps to Reproduce the issue

1. When I do X
2. Then Y
3. I see behavior Z

**Expected behavior:** (What you expected to happen)

**Actual behavior:** (What actually happened)

### CodeSandbox With Reproduction of Issue:

- [Basic Template](https://codesandbox.io/s/cornerstone-basic-issue-template-9slk4)

**Comment by longerking** [comment]
@zhihli 
Hi Bro! Have you solved this problem?  I also encountered the same problem, but I don't know how to solve it, can you give me some help?

> ### Prerequisites
> * [x]  Which version are you using? (Is it latest?)
> * [x]  Are you reporting to the correct repository?
> * [x]  Did you search existing issues? (Were any related?)
> 
> ### Description
> Thans for your great work !
> I have a file of dicom list, and a nifti file, I want to use layer to fuse these two files，dicom is base layer，nifti is overlay, I found this example
> https://github.com/paul-asvb/cornerstoneTools/blob/preservelayeredImageStacks/examples/layeredImageStacks/index.html
> I referenced it, but I didn't meet my needs, so, Do you have any suggestions for me？thanks !
> 
> ### Steps to Reproduce the issue
> 1. When I do X
> 2. Then Y
> 3. I see behavior Z
> 
> **Expected behavior:** (What you expected to happen)
> 
> **Actual behavior:** (What actually happened)
> 
> ### CodeSandbox With Reproduction of Issue:
> * [Basic Template](https://codesandbox.io/s/cornerstone-basic-issue-template-9slk4)

**Comment by zhihli** [comment]
@longerking，we have communicated through this issue， [issue #1137 ](https://github.com/cornerstonejs/cornerstoneTools/issues/1137#issue-527806390),
