### ISSUE TITLE
Error:Consumers must define stacks in their application if using segmentations in cornerstoneTools.

### ISSUE THREAD

**Issue by JiangWeian** [cornerstonejs/cornerstoneTools#1355]
How to solve this error:
![TIM图片20201211161511](https://user-images.githubusercontent.com/56569509/106681829-447ae200-65fc-11eb-9148-89f38883b54a.png)

**Comment by ronzim** [comment]
Hi @JiangWeian,
if you want to use segmentation module, you have to add a stack manager that contains the list of the cornerstone imageIds and the current active image on which you are using the tool. This should work:
`let stack = { currentImageIdIndex: currentImageIndex, imageIds: imageIds };`
`cornerstoneTools.addStackStateManager(element, ["stack"]);`
`cornerstoneTools.addToolState(element, "stack", stack);`

Or maybe you could try to use [Larvitar](http://larvitar.dvisionlab.com), it's an open source library we build on top of cornerstone and cornerstone tools. It comes with docs and ready-to-use examples!
