### ISSUE TITLE
When multiple tools actived at one time, the one's cachedStats is overwrote by another and not updated.

### ISSUE THREAD

**Issue by Enside** [cornerstonejs/cornerstoneTools#1424]
version: ^5.3.0

Reproduction:
First, active LengthTool and draw a line, then it has a text box.
Second, active AngleTool and draw a angle, then it also has a text box.
Finally, select the text box of LengthTool and move it.

Error:
Console shows an error 'Cannot read property 'x' of undefined', the property `x` should in LengthTool's `cachedStats`, but it's overwrote by AngleTool.
Sometime it just cause an error or make stats data wrong, and view is still look good. While the undefined property is processed before draw it, there would be a fatal error which makes the annotation not rendered.
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
at _createTextBoxContent (RectangleRoiTool.js?t=1630577637869:203)
at RectangleRoiTool.js?t=1630577637869:119
at __webpack_exports__.default (draw.js:15)
at RectangleRoiTool.renderToolData (RectangleRoiTool.js?t=1630577637869:60)
at imageRenderedEventDispatcher.js:39
at Array.forEach (<anonymous>)
at HTMLDivElement.onImageRendered2 (imageRenderedEventDispatcher.js:36)
at triggerEvent (triggerEvent.js:23)
at __webpack_exports__.default (drawImageSync.js:78)
at draw (enable.js:98)
```
I think we should just dispatch the tool data to the corresponding tool. 

There also two other issues in following code:
```
if (data.invalidated === true) {
  if (data.cachedStats) {
    this.throttledUpdateCachedStats(image, element, data)
  } else {
    this.updateCachedStats(image, element, data)
  }
}
```
The first is that `invalidated` property is `false` even `cachedStats` need to be updated. I guess it's because last rendered tool modified it.
The second is throttledUpdateCachedStats is in timing when `cachedStats` is `invalidated`.

So I change the code to:
```
// if (data.invalidated === true) {
//   if (data.cachedStats) {
//     this.throttledUpdateCachedStats(image, element, data)
//    } else {
         this.updateCachedStats(image, element, data)
//    }
// }
```
Then everything works well.

**Comment by ricardonava** [comment]
Hi @Enside Did this really fix the problem?, in my case it makes it  worse.

**Comment by Enside** [comment]
> Hi @Enside Did this really fix the problem?, in my case it makes it worse.

Unfortunately, the problem in leatest version still exists.
I have modified much code by extends XXXTool, and commented out the code above in some of tools' class, although there are still some errors printed in console, the cachedStats is updated correctly, otherwise cachedStats will not be updated.

**Comment by Enside** [comment]
> Hi @Enside Did this really fix the problem?, in my case it makes it worse.

Unfortunately, the problem still exists in latest version .
I have modified much code by extends XXXTool, and commented out the code above in some of tools' class, although there are still some errors printed in console, the cachedStats is updated correctly, otherwise cachedStats will not be updated.

**Comment by Enside** [comment]
@ricardonava Unfortunately, the problem still exists in latest version .
I have modified much code by extends XXXTool, and commented out the code above in some of tools' class, although there are still some errors printed in console, the cachedStats is updated correctly, otherwise cachedStats will not be updated.
