### ISSUE TITLE
Magnifying glass doesn't use full resolution image

### ISSUE THREAD

**Issue by hardmaster92** [cornerstonejs/cornerstoneTools#182]
I recently noticed that the zoom of the magnification glass is not a real zoom. It just gets the area you click and resizes it with interpolation. If you use the zoom tool to zoom out the image and make it really small and then use the magnify tool it all gets pixelated.

**Comment by jpambrun** [comment]
The canvas itself is used as pixel source here: 

https://github.com/chafey/cornerstoneTools/blob/a28f8973360c3072487880c4f6fb9bb82b91eb79/src/imageTools/magnify.js#L131

I agree with @hardmaster92, it is not very useful in this state.

**Comment by diego0020** [comment]
I have an rough implementation of a magnifying glass that uses the full resolution image as source in my fork. If you are interested I can clean it up and make a PR

**Comment by dannyrb** [comment]
Oooh. I'd actually love a link to this? I'm curious to see the path you
took to implement.

**Comment by diego0020** [comment]
here it is 
https://github.com/diego0020/cornerstoneTools/blob/master/src/imageTools/magnify2.js

**Comment by diego0020** [comment]
I basically render the image again in an offscreen canvas of the correct size, and then copy the pixels to the magnifying glass view

**Comment by swederik** [comment]
I'd be happy to review a PR for this if you make one

**Comment by dannyrb** [comment]
This has been merged and fixed :+1:
