### ISSUE TITLE
preventHandleOutsideImage

### ISSUE THREAD

**Issue by EvgheniAnachii** [cornerstonejs/cornerstoneTools#187]
I did not find how can I set the property `preventHandleOutsideImage` inside my application. Does exist a possibility for setting this property with value "true" without extending the whole cornerstoneTools object?

**Comment by swederik** [comment]
Good question... At the moment, no it is not possible to set this easily.

**Comment by dannyrb** [comment]
This is a global setting that defaults to false in `vNext`. You can set it globally, or override behavior on a per tool basis in the tool's configuration.

If you are using `vNext` and need assistance, please don't hesitate to reach out as the docs are still coming along and may not explain this adequately.
