### ISSUE TITLE
Include required metadata for each tool

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#228]
I see the metadata that each tool relies on as a dependency. It would be nice if we had some additional documentation around what `metaData` fields are used across all tools (the DICOM fields they map to), and which ones each tool depends on.

This library is powerful and helpful, but it's not yet very approachable for would be contributors. I think this extra bit of documentation would be helpful.

**Comment by swederik** [comment]
Yes this is sensible and something we should definitely do. Thanks for bringing it up!

**Comment by dannyrb** [comment]
Closing this. I'll make sure it gets included as part of a larger ticket where we write API documentation for each tool.
