### ISSUE TITLE
Start using event.button instead of event.which

### ISSUE THREAD

**Issue by brunoalvesdefaria** [cornerstonejs/cornerstoneTools#229]
CornerstoneTools is currently relying on a non-standard event attribute, the [MouseEvent.which](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which).
This is causing some issues when some specific events on some browsers.
We shall consider start using [MouseEvent.button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) for the next major version.

**Comment by swederik** [comment]
Merged!

**Comment by dannyrb** [comment]
This has been addressed in the `vNext` branch. I doubt it will be backported to `v2`. If anyone encounters issues with the new `MouseEvent.buttons` implementation, please feel free to create a new issue with the bug report.
