### ISSUE TITLE
Add API to change handleRadius on src/manipulators/drawHandles.js

### ISSUE THREAD

**Issue by KErez** [cornerstonejs/cornerstoneTools#252]
Currently the handleRadius is expressed as ```const handleRadius``` thus I cannot set the radius size by myself. 
I would like to have an API call (or other) to be able to change the radius of the handles

**Comment by dannyrb** [comment]
Per #732 

> - By default, the `handleRadius` in `store.state.handleRadius` is used.
> - It can be overridden by providing `handleRadius` in a tool's `configuration`
> - Lastly, each handle can have a `radius` property that will supersede the other configuration options
> 
> So we can now specify `handleRadius` globally, per tool, or per handle
