### ISSUE TITLE
Create GitHub Pages Documentation 

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#255]
1. Setup [GitHub Pages](https://pages.github.com/) for this project using a `documentation` branch
2. Create template documentation pages using a tool like [GitBook](https://www.gitbook.com/pricing) (free for open source)
    - [How to link GitBook to GitHub](https://help.gitbook.com/github/can-i-host-on-github.html)
3. Update `readme` and project description to include a link to documentation
4. Create "Up For Grabs" issues for missing or out of date documentation

@swederik can you assign this to me?

**Comment by swederik** [comment]
I think you can use GH pages on the master branch now as well.

**Comment by dannyrb** [comment]
You can see the start of the GitBook documentation here:

- [https://dannyrb.gitbooks.io/cornerstone-tools/](https://dannyrb.gitbooks.io/cornerstone-tools/)

Ideally, we want to enable the GitHub integration so we can leverage:

> * All updates made to your book from the Editor will also update the GitHub repository.
> * All updates made to your GitBook or GitHub repository will be reflected on the other and update your published book accordingly.

You can enable the integration by following [these instructions](https://help.gitbook.com/github/can-i-host-on-github.html#github-integration)

And you can configure it to sync to a specific branch following the steps in [this GitHub issue](https://github.com/GitbookIO/gitbook/issues/1197)

This will allow us to:

* Keep the docs as part of the same repository
* Sync changes between GitBook and GitHub (and gain version tracking)
* Self-host the documentation using GitHub pages

@swederik we may need @chafey to authorize the app. I think most of this would be easier to grant permissions for under an org (so we may wish to hold off until that change is made).

I'm going to hold on adding much more documentation until we have the integration setup. I'd like for as much of this as possible to be captured by version control/tracking.

Let me know if you have any questions :+1:

**Comment by dannyrb** [comment]
You can see an example of an embedded canvas/demo on the [What is Cornerstone Tools?](https://dannyrb.gitbooks.io/cornerstone-tools/what-is-cornerstone-tools.html) page.

I've already found a few small things we may want to update/fix with some of our NPM packages to make the MVP example a little less bulky/cumbersome (that's the benefit of writing docs, right?).

**Comment by swederik** [comment]
Wow gitbooks looks like it will be perfect for this, thanks for getting this started!

**Comment by dannyrb** [comment]
@swederik, any updates on a transition to OHIF? I want to chip away at these docs, but it feels silly to do it without version control or GitHub pages. Even as a maintainer, I don't believe I have the permissions I'd need to do this unless this project were under an org.

**Comment by dannyrb** [comment]
@swederik Another advantage to moving the cornerstone family to an org:

https://github.com/blog/2471-introducing-team-discussions

If the issue is control, @chafey can create an org called "cornerstone", migrate the libraries, and then if OHIF is eventually handed the keys, it would be as simple as changing owner/admin for the org?

**Comment by dannyrb** [comment]
This is unblocked now that @chafey has moved us transferred his repositories to the `cornerstone` org 🍾 🎉 

I'll remove him as assigned, and work on linking the appropriate repositories to GitBook.

**Comment by dannyrb** [comment]
Found here: https://tools.cornerstonejs.org
Still in it's infancy, but good enough for me to close this issue 🎉 

Thanks for your help and cooperation @swederik && @chafey
