### ISSUE TITLE
Double click handlers are not firing

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstoneTools#290]
For some reason, the dblclick event keeps having event.buttons = 0 for me, so no double click handlers are working. I don't know why.

**Comment by dannyrb** [comment]
Do you have a reproducible example (Double click is working for me on latest)? Could you either link a repo or a codepen/jsfiddle that demonstrates the error? I'd be willing taking a stab, but it would be easier if I had a reproducible source to work from.

**Comment by swederik** [comment]
Fixed it in 2.0.0. It turned out that event.buttons is 0 for dblclick events. Not sure why, so I just set it to use event.which for now.
