### ISSUE TITLE
Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by adreyfus** [cornerstonejs/cornerstoneTools#294]
Hi,

No question here, just a tips.

When I tried to compile the last version with webpack, I had the error: 
`Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'`.

To fix that, run the command: 
`npm install react-scripts` in the Node.js command prompt.

**Comment by dannyrb** [comment]
@adreyfus, I believe if you have `eslint` installed globally, that other `eslint` plugins also need to be installed globally. However, if you only have `eslint` installed locally, then locally installed plugins should work.

Not 💯 sure, but I think this is true.
