### ISSUE TITLE
Travis CI build passed despite errors during compilation

### ISSUE THREAD

**Issue by adreyfus** [cornerstonejs/cornerstoneTools#295]
Is it normal ?

**Comment by dannyrb** [comment]
@adreyfus, can you post a copy of your output? I can get it to build with warnings, but not errors.

**Comment by dannyrb** [comment]
@adreyfus is this still an issue? What are the next steps? Anything I can do to help?

**Comment by adreyfus** [comment]
It seems to be resolved (Travis CI build fails as expected, if there is an error on compilation).
