### ISSUE TITLE
Memory leak with set/getToolOptions

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstoneTools#309]
There is an issue with the new set / get tool options module which was used to help replace jQuery's passing of additional data (e.g. mouse button mask) into event handlers. It never clears the data, not even if the element or tools are disabled.

Relevant code is here:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/toolOptions.js

Options:
- We could set up a 'clearToolOptions' function to be run when a tool is disabled
- We could attach a listener for 'cornerstoneelementdisabled' to clear all element-specific data when an element is disabled
- We could update cornerstone core to incorporate an optional callback to run when an element is disabled, and we could register clearToolOptions to run in this callback.

Not exactly sure what's cleanest, so I'm open to suggestions, and of course pull requests, should anyone wish to fix this themselves!

**Comment by nspin** [comment]
Hello,

Would [this](https://github.com/cornerstonejs/cornerstoneTools/blob/b9e70792d1b0621fdf6014a9ae4572d3fb4ae1f2/src/synchronization/Synchronizer.js#L276) be an appropriate place to call garbage collection logic?
