### ISSUE TITLE
Mouse wheel scroll is reversed on Chrome

### ISSUE THREAD

**Issue by hardmaster92** [cornerstonejs/cornerstoneTools#310]
When I tried the latest version I found out that stack scroll works reversed on Chrome (i tested on firefox too but it seems correct there).

**Comment by dannyrb** [comment]
DeltaY from `wheel` and `mouseWheel` varies by browser. I'm not sure we want to force them all to behave identically, as you may expect the vendor specific scroll when using your browser of choice. More info here:

https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers

**Comment by dannyrb** [comment]
@hardmaster92, if you feel strongly that we should normalize scroll behavior for different browser vendors, this may be a good use case for adding a new "strategy" to the stack scroll tool. Let me know if you need code examples of how we've approached this in the past.

**Comment by swederik** [comment]
Hi Stephen,

Yep this is a known issue I missed during testing. This might be relevant: https://github.com/cornerstonejs/cornerstoneTools/pull/308/

@dannyrb I do feel strongly we should at least normalize the direction :-)

Thanks,

Erik

**Comment by hardmaster92** [comment]
I agree with Erik that it would be good if the direction is the same.

**Comment by freund17** [comment]
As https://github.com/cornerstonejs/cornerstoneTools/pull/308 is now merged, this can be closed.

**Comment by freund17** [comment]
As https://github.com/cornerstonejs/cornerstoneTools/pull/308 is now merged, this issue can be closed.
Though I'm still waiting for the npm release. (Hint, hint https://github.com/cornerstonejs/cornerstoneTools/issues/355)
