### ISSUE TITLE
Rotation and recovery

### ISSUE THREAD

**Issue by zhuashaoweiwu** [cornerstonejs/cornerstoneTools#312]
I want to let the rotation of disable, let the picture go back to the initial position how to set this, thank you!

**Comment by zhuashaoweiwu** [comment]
cornerstoneTools.rotate.disable(element);
 cornerstoneTools.rotateTouchDrag.disable(element);
 的时候At this time.

**Comment by zhuashaoweiwu** [comment]
How to set the angle for him to recover     thank you!

**Comment by jdnarvaez** [comment]
cornerstone.reset(element);

**Comment by zhuashaoweiwu** [comment]
Yes, thank you for your help  jdnarvaez  .
