### ISSUE TITLE
WWWC Synchronizer Problem

### ISSUE THREAD

**Issue by agustingrigoriu** [cornerstonejs/cornerstoneTools#315]
Hi! I've the following layout for my app:
![imagen](https://user-images.githubusercontent.com/19197433/34304329-1e0be09e-e718-11e7-8bb8-111f3c80f311.png)

I'm trying to synchronize the WW/WC Tool to work in every image. My code is the following:
```
 var synchronizer = new cornerstoneTools.Synchronizer(
    "cornerstoneimagerendered",
    cornerstoneTools.wwwcSynchronizer
  );

  var openImage = function(image, element) {
    var imageId = "wadouri:/image/" + image.idimage;
    cornerstone.loadImage(imageId).then(function(dicomImage) {
      cornerstone.enable(element);
      var vp = cornerstone.getDefaultViewportForImage(element, dicomImage);
      if (image.imagelaterality === "R") {
        var imgPixelWidth = dicomImage.columns * vp.scale;
        var divWidth = element.clientWidth;
        var leftPos = (divWidth - imgPixelWidth) / vp.scale / 2;
        vp.translation.x = leftPos;
      }
      if (image.imagelaterality === "L") {
        var imgPixelWidth = dicomImage.columns * vp.scale;
        var divWidth = element.clientWidth;
        var leftPos = -((divWidth - imgPixelWidth) / vp.scale / 2);
        vp.translation.x = leftPos;
      }
      cornerstone.displayImage(element, dicomImage, vp);

      // Enable our tools
      cornerstoneTools.mouseInput.enable(element);
      cornerstoneTools.mouseWheelInput.enable(element);
      cornerstoneTools.wwwc.activate(element, 1); // Left Click
      cornerstoneTools.pan.activate(element, 2); // Middle Click
      cornerstoneTools.zoom.activate(element, 4); // Right Click
      cornerstoneTools.zoomWheel.activate(element); // Mouse Wheel

      synchronizer.add(element);
    });
  };
```
But, although the synchronizer is correctly adding the elements (I know that thanks to the .getSourceElements() method), the wwwc synchronizer is not working.

**Comment by dannyrb** [comment]
That is odd.

Some follow-up questions:
- What version of `cornerstone-core` and `cornerstone-tools` are you using?
- Why do you call `cornerstone.enable(element)` inside of the `.loadImage()` callback?
- Can you successfully add a listener for the event with vanilla-js and see it triggered/called?
- If you're using a dev source, can you verify that the callback is [not] being called?

**Comment by agustingrigoriu** [comment]
Thanks for your answer! The problem was in this example:
[https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/wwwcSynchronizer/index.html](url)
On line 104 you can see this:
`var synchronizer = new cornerstoneTools.Synchronizer("cornerstoneimagerendered", cornerstoneTools.wwwcSynchronizer);`

The problem is that we are calling to **cornerstoneimagerendered**, but it is **CornerstoneImageRendered**.
