### ISSUE TITLE
simpleAngle Click events 

### ISSUE THREAD

**Issue by zhuashaoweiwu** [cornerstonejs/cornerstoneTools#319]
simpleAngle.activate(element, 1);

I want to click on this mark on the page to have an event. What should this do? Who can help me.

**Comment by zhuashaoweiwu** [comment]
I see the binding of the event, but I don't know how to use it
![cccuqwe_ a1gf5cl ttnc5o8b](https://user-images.githubusercontent.com/23515321/34479287-d474d5e0-efe0-11e7-97af-82d4ed7a0d68.png)

**Comment by dannyrb** [comment]
It looks like you're using an older version of `cornerstone-core` and/or `cornerstone-tools`. I recommend updating them to v2.x.x+ to remove the jQuery dependency and to receive better support from our small group of contributors.

Here is a list of helpful resources:
- [Live Examples](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/index.html)
- [Source for live examples](https://github.com/cornerstonejs/cornerstoneTools/tree/master/examples)
- [Simple Angle tool example](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/angleTool/index.html)
- [Source for Simple Angle Tool Example](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/angleTool/index.html#L78-L79)

If after looking at the source code and examples I've provided you still have questions, please let me know. We try to have at least one example for each tool in the `cornerstone-tools` repository. If you believe we could improve the documentation in any way, please let us know.

If this does answer your question, please let me know so I can close this issue.

**Comment by zhuashaoweiwu** [comment]
Thank you for your answer, I'll update my version, but do you know about the click of a mouse click? Thank you very much.

**Comment by zhuashaoweiwu** [comment]
![ddddddddd_gwvi aynx 6v rst kf](https://user-images.githubusercontent.com/23515321/34482665-60ad3a12-eff4-11e7-9dca-9bc71008e72c.png)

**Comment by zhuashaoweiwu** [comment]
Click on the green line and provide the trigger click event.Is there such a Event?

**Comment by dannyrb** [comment]
It's been roughly a week, so I'm going to mark this as closed. Please feel free to follow-up if you still have questions. As always, if you feel our documentation could be improved, or if there is a way to accomplish by an API improvement, please don't hesitate to suggest so in a new issue.
