### ISSUE TITLE
What callbacks or events exist for the Length tool?

### ISSUE THREAD

**Issue by andydarw** [cornerstonejs/cornerstoneTools#320]
After measuring a distance, I want to have a callback event, and then save his coordinates, and after refreshing the page, I can show it. I don't know what events to use.

**Comment by dannyrb** [comment]
[Source for Length Tool (src/imageTools/length.js)](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/length.js)

Which builds off of:
- [src/imageTools/mouseButtonTool.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/mouseButtonTool.js)
- [src/imageTools/TouchTool.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/touchTool.js)

Annnnd if you dig even further in, you'll see that all `toolData` (how we store/update each tool's state) is done here:

- [src/sateManagement/toolState.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/toolState.js)

Please note, you'd want to know when `toolData` is created, removed, or updated. You can see that in these methods:

- [addToolState](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/toolState.js#L20-L33)
- [removeToolState](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/toolState.js#L44-L68)
- [clearToolState](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stateManagement/toolState.js#L70-L78)

If you're using `addToolState` or `removeToolState`, you'll see that they emit the following events respectively:

- `cornerstonetoolsmeasurementadded`
- `cornerstonemeasurementremoved`

If a measurement is dragged, or its "handles" are moved, one of the handle classes will generally call:

- `cornerstonetoolsmeasurementmodified`

You can find a list of all events for `cornerstone-tools` here:

- [src/events.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/events.js)

You can see from the paths that the source code _is not too scary_ to navigate through. Most of the tools aren't overly complex, and they build off "base tools" like `touchTool` and `mouseButtonTool`

**Comment by andydarw** [comment]
Thank you for your help. Do you know how to write the graphics when you re drawing the graphics?

**Comment by dannyrb** [comment]
Quick housekeeping items:

- If this is a new question, can you create a new issue?
- Please include code as a code block snippet, not as an image. It makes it easier to read, search against, and select.

Back to your question, there are a number of ways to customize an existing tool. Often times, it is easier to add a new tool "strategy" or create a new tool entirely so you don't experience merge conflicts as tools are updated over time. If you can provide a more verbose example of what you're trying to accomplish, I may be able to help point you in the right direction.

**Comment by andydarw** [comment]
I want to draw length on my own according to X and y, but I draw out that there is no way to bind mobile events. The mouse cannot move. I tried adding a function to bind events, but failed.

**Comment by dannyrb** [comment]
@andydarw, I'm not sure I fully understand what you're trying to accomplish. The existing `Length` tool already "draws length" with the mouse's (x, y) from event data. By mobile events do you mean Touch Events? The `LengthTouch` tool, when enabled, works exactly like the `Length` tool, but is bound to touch events.

All of these tools work by binding to simple native events. You can find the base implementations for these tools in the `mouseButtonTool` and `touchTool` links I provided above: https://github.com/cornerstonejs/cornerstoneTools/issues/320#issuecomment-355535125

**Comment by andydarw** [comment]
Man, your answer is very detailed. Thank you for your help.
I want to customize the method to adjust

exports.lengthMode = (0, _mouseButtonTool2.default)({
	  createNewMeasurement: acbc,
	  onImageRendered: onImageRendered,
	  pointNearTool: pointNearTool,
	  toolType: toolType
	});

exports.lengthMode.x=function(mouseEventData){
    handleMover(mouseEventData, "length", measurementData, handles, function () {
      measurementData.active = false;
      measurementData.invalidated = true;
      if ((0, _anyHandlesOutsideImage2.default)(mouseEventData, measurementData.handles)) {
        // Delete the measurement
        (0, _toolState.removeToolState)(element, toolType, measurementData);
      }
      element.addEventListener(_events2.default.MOUSE_MOVE, mouseMove);
      element.addEventListener(_events2.default.MOUSE_DOWN, mouseDown);
      element.addEventListener(_events2.default.MOUSE_DOWN_ACTIVATE, mouseDownActivate);
      if (mouseDoubleClick) {
        element.addEventListener(_events2.default.MOUSE_DOUBLE_CLICK, mouseDoubleClick);
      }
      cornerstone.updateImage(element);
    }, preventHandleOutsideImage);

How does this mouseMove define it.?

![image](https://user-images.githubusercontent.com/35130565/34674311-65b39684-f4c0-11e7-92b6-c7d2ed46c096.png)

**Comment by dannyrb** [comment]
Its been a while since this issue has seen activity. It might be worth taking a look at the `vNext` branch, as the tools are a little cleaner and hooking into event callbacks is a lot easier.

I'm still unsure if you were trying to handle events around modifying length measurement data, or trying to create a custom/modified length tool.

In either case, we can continue our discussion, but I'd need clarification. Your examples seem to use bundled code, which is partly why I'm lost.

**Comment by FMCalisto** [comment]
The Length tool in CornerstoneJS does provide several events and callbacks that can be used to customize the behavior of the tools. There are ways to create a custom length tool if necessary. In addition, the `clearToolState` function can be used to [remove tool state and reset the tools](https://stackoverflow.com/a/73204850/2371987). Thanks to everyone for the helpful information and resources.
