### ISSUE TITLE
clip frame

### ISSUE THREAD

**Issue by Bharath0807** [cornerstonejs/cornerstoneTools#321]
can we get the current frame of the clip we are playing when we click on pause or play button. If so, what is the way of doing that

**Comment by dannyrb** [comment]
You can find the live example of `playClip` at this URL:
https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackScroll/index.html

If you look at [the source](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/stackScroll/index.html) for the example, you can see that the overlay information is updated when different events from cornerstone are emitted.

- [cornerstoneimagerendered](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/stackScroll/index.html#L80-L87)
- [cornerstonenewimage](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/stackScroll/index.html#L89-L111)

In the `cornerstonenewimage` event handler, you can see where we grab the image's position in the stack. If you want to access this information outside of those events, there are a couple of ways to snag the current image's / stack's information.

- Use Cornerstone's `getImage` to get the image object currently displayed for the target enabledElement.
    - [cornerstone.getImage(referenceToDOMForEnabledElement)](https://github.com/cornerstonejs/cornerstone/wiki/getImage-api)
- Use Cornerstone Tool's `getToolState` to grab relevant tool data.
    - `cornerstoneTools.getToolState(referenceToDOMForEnabledElement, 'stack')`
- If you're using the WADO image loader, or a different image loader that registers and hydrates a metaDataProvider/Manager, then you can grab that meta data like so (often DICOM tags):
    - `cornerstone.metaData.get('imagePlaneModule', imageId)`
    - Where `imagePlaneModule` is a string that identifies a group of information requested from the store
    - See examples [in the cornerstoneWADOImageLoader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/metaData/metaDataProvider.js#L88-L97) repository

**Comment by dannyrb** [comment]
I hope this means I was able to help, @Bharath0807. If you have any other questions, please feel free to create a new issue. If you think our documentation or API could be better, please feel free to suggest changes/enhancements as well.

Thanks! (:
