### ISSUE TITLE
Change WWWL inside the rectangel ROI

### ISSUE THREAD

**Issue by doananhbao94** [cornerstonejs/cornerstoneTools#322]
Can you create a tool allow user draw a rectangle ROI and change wwwl inside or ouside it?

Thank you too much!

**Comment by dannyrb** [comment]
Hi @doananhbao94, thanks for the suggestion! If you made a pull request, I'd be willing to take a look at it and consider merging? If you need some guidance on how to get started creating a tool, let me know where you're getting hung up and I can try to point you in the right direction.

**Comment by dannyrb** [comment]
This hasn't seen action in 7 months. Its a good candidate for a 3rd party plugin post `v3` release, but it may not longer be ideal as a core tool in this repository.

Closing for now. Please feel free to discuss.
