### ISSUE TITLE
cornerstonetoolsmouseup not triggered on fast mouse clicks

### ISSUE THREAD

**Issue by Lemenxzy** [cornerstonejs/cornerstoneTools#323]
when I click mouse with a fast mouse up, the event of mouse up can't be triggered.
The code is:
```
cornerstoneTools.ellipticalRoi.activate(element, 1);
element.addEventListener('cornerstonetoolsmouseup', this.mouseUpCallback,false);
```

**Comment by dannyrb** [comment]
`cornerstonetoolsmouseup` is only called in a few places:

_Turned on when mouse input is enabled_

- [mouseInput](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/inputSources/mouseInput.js#L79)
    - Specifically prevents fast clicks (less than 200ms) from emitting `MOUSE_UP`. Anything < 200ms emits a click event. Anything > 200ms should emit a mouse up event.

_Used by most tools_

- [moveAllHandles](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/manipulators/moveAllHandles.js#L75-L76)
    - Only added inside `mouseDrag`
- [moveNewHandle](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/manipulators/moveNewHandle.js#L44-L46)
    - Only added inside `mouseDrag`

It looks like we've intentionally used `cornerstonetoolsmouseup` to indicate the end of a drag.

**Comment by Lemenxzy** [comment]
thank you very much . I get it .

**Comment by dannyrb** [comment]
Thanks for reaching out, @Lemenxzy! If you have any additional questions, please don't hesitate to create a new issue. Also, if you think our documentation could be better, always happy to hear what we can add/improve.
