### ISSUE TITLE
add Level-Set ROI

### ISSUE THREAD

**Issue by xhf127** [cornerstonejs/cornerstoneTools#339]
I want a function to add ROI to the image based on LEVELSET, which has the same functions as other ROI
<img width="269" alt="levelset" src="https://user-images.githubusercontent.com/34505500/35659858-9a537734-0743-11e8-8ef9-0b25a0a11155.png">

**Comment by dannyrb** [comment]
Is this similar to the "wand tool" in photoshop? When you select and area, place and ROI around it and any pixels within a certain sensitivity threshold?

**Comment by JamesAPetts** [comment]
@dannyrb , yeah looks like it. If we wanted to achieve something like this I would save the resulting tool data as a freehand ROI so it can be used in the same way. I'd just extend the freehand tool, let the user draw something (i.e. a blob), and do the growth on completion.

**Comment by JamesAPetts** [comment]
There is a lot of room for growth in the way we  generate freehand and brush toolData through other tools.

**Comment by dannyrb** [comment]
This is likely something that can be accomplished by extending the `freehand` tool, or with a 3rd party tool/plugin. I'm going to close this issue for now. If you would like to discuss further, please feel free to comment or create a new issue.

If you believe this should be _core_ functionality, and you'd be willing to drive the effort, we can discuss updating the freehand tool or other options.

If you would like help creating a 3rd party tool, I can offer guidance as you work through creating one.
