### ISSUE TITLE
How to scroll through frames in single dicom image?

### ISSUE THREAD

**Issue by gregmcguffey** [cornerstonejs/cornerstoneTools#341]
If I have a DICOM image that has a bunch of frames, how to I scroll through those. All the examples are using an array of separate images. I need to do this with a single file/image that has many frames.

**Comment by chafey** [comment]
Every image in cornerstone is identified by a unique image id.  CornerstoneWADOImageLoader allows you to specify the frame in a multi-frame by appending the frame you want to the imageId.  For example:
wadouri://host/studyuid/seriesuid/imageuid?frame=5

See example here:
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html

**Comment by gregmcguffey** [comment]
Thanks. I'm getting an error that there is no image loader defined for the imageId.  What in is defining the image loader in the example code? Is it defining the codecs?

**Comment by dannyrb** [comment]
Image Loader: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html#L110

Codecs: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/examples/wadourimultiframe/index.html#L86-L107

The setup is a bit different if you're using `npm` or a bundler.

**Comment by dannyrb** [comment]
I'm going to close this. We don't currently have a `gitbook` for `cornerstoneWADOImageLoader`, but when/if we add one, documentation like this would be a good add 👍

**Comment by kofifus** [comment]
It is important to note that DICOM multiframes contain importunate information on _how_ to cine the frames in terms of timing etc

see: http://dicom.nema.org/medical/Dicom/2017e/output/chtml/part03/sect_C.7.6.5.html

Ideally we should have a tool that can cine a multiframe according to these parameters !

**Comment by majidazn** [comment]
I'm using npm and I want to implementing multi-frames. Do you have any sample code?

**Comment by gregmcguffey** [comment]
Attached is what we are using to handle viewing images with frames.

Hope that helps!
