### ISSUE TITLE
Codepen template to demonstrate issues

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#342]
As @dannyrb has mentioned in #338 it is nice to have a simple Codepen to demonstrate the problem with Cornerstone / Cornerstone Tools. Wouldn't it be nice to have a preconfigured Codepen template where issue creators could simply demonstrate their problems? Maybe we could add a link to it in the Readme in the Contributing section (maybe with a title called "How to report issues").
I created a simple template that could be forked for that purpose: https://codepen.io/medihack/pen/JpGxgv

**Comment by dannyrb** [comment]
^ Thanks for this. I agree on all fronts! I'll create a checklist:

- [ ] Update `contributing.md` to include Codepen template
- [ ] Update issue template to include prompt for reproduction (include codepen)
- [ ] Provide templates/setup for more complex issues (ie. Image stacks)

**Comment by swederik** [comment]
Yeah this is a pretty great idea, we should definitely do this!

**Comment by medihack** [comment]
Good idea to have different templates for more advanced issues. My first try was to set up a more complete template that also includes the WADOImageLoader. Unfortunately, I have not figured out how to use the web worker of the image loader in a CodePen. I'll give it another try on the weekend, and also add some other templates.

**Comment by dannyrb** [comment]
I think the biggest issue with Codepen is that it wants the Webworker files to live on the same domain/host. I'll see if I can swing a pro account so we can leverage their hosted file library. If I make any progress, I'll update this thread. Let me know if you have other ideas around improving this process :+1:

**Comment by dannyrb** [comment]
This is a bit outdated. I'll create a new issue in our Documentation project as we tidy up everything surrounding the latest v3 release.
