### ISSUE TITLE
Map same tool to two different mouse buttons

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#343]
It seems that it is currently not possible to map the same tool (e.g. `wwwc`) to two different buttons.
 The second activation always overwrites the first one ([Codepen example](https://codepen.io/medihack/pen/OQMYde)). Maybe we can fix that and allow mappings like those are handled in [RadiAnt](https://www.radiantviewer.com) (one of the best freeware viewers in my opinion) where the user can map each button by clicking on a tool item.

**Comment by dannyrb** [comment]
Ahh. I think mouse button tools `.remove` listeners "to be safe" before registering new ones. We have a separate issue to track active tools and expose an API method to see which tools are active, and what input they're bound to.

Having that in place would make implementing "Map same tool to two different mouse buttons" much easier.

Really appreciate all of the recent activity! We're in the middle of creating working groups, and hammering out a new "target API" for CornerstoneTools. If you're interested in participating, let me or @swederik know (:

**Comment by swederik** [comment]
It is actually possible to do this already with combinations of the 'which' values. I can't seem to find the right documentation at the moment, but here is how it is done in the OHIF Viewer: 

https://github.com/OHIF/Viewers/blob/master/Packages/ohif-viewerbase/client/lib/toolManager.js#L402

e.g. 5 means left or right, 3 means left or middle, 7 means left, right, or middle...

**Comment by medihack** [comment]
Thanks, that seems to be a good solution for the problem.
@dannyrb Sure, I am interested in participating ... I will drop you an Email later.
