### ISSUE TITLE
how to make dicomRT

### ISSUE THREAD

**Issue by xhf127** [cornerstonejs/cornerstoneTools#346]
I want to know how to build a dicomRT structure through the ROI data and the DICOM series. If there is any clue about the generation of dicomRT, please tell me, thank you.

**Comment by dannyrb** [comment]
@xhf127 what is a `dicomRT` structure? How would you use the ROI and DICOM series data to build it? If you can provide requirements/expectations, we could work together to hammer out a scope and maybe a few implementation details.

**Comment by xhf127** [comment]
https://dicom.innolitics.com/ciods/rt-structure-set

Roi-contour stores the three-dimensional coordinates of the ROI outline. I extract the marking coordinates from imageIdToolState by Python, transform the image coordinates into the anatomical coordinate system, and generate the files needed for the following C++ programs.

Generating DICOM RT structure through https://github.com/midas-journal/midas-journal-316/blob/master/Code/RTSTRUCT/export2RTSTRUCT.cxx

I hope to provide a function to generate DICOM RT structure by JS, use the ROI and DICOM series data, but it looks very difficult

**Comment by xhf127** [comment]
There is a decimal place in the mark coordinates, and I want to know why, is the coordinates in cornerstone ROI an image coordinate system, is that an integer value?

**Comment by dannyrb** [comment]
@xhf127 unfortunately I am not a Radiologist, so I may need more clarification than normal. 

> Roi-contour stores the three-dimensional coordinates of the ROI outline. I extract the marking coordinates from imageIdToolState by Python, transform the image coordinates into the anatomical coordinate system, and generate the files needed for the following C++ programs.

So.. You'd like for `cornerstone` to identify the DICOM tags in the series and return it as a module? Similar to how we [currently do for single images](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadors/metaData/metaDataProvider.js#L14-L23), but for a series? Then, you would like for a new `cornerstone` tool to utilize that module/structure to create an annotation on the image/stack?

Any visualizations or additional information would go a long way toward helping me understand. It may be hard to find someone to create a new tool for a specific/niche use case you have, but I could put you in contact with a contractor? Core functionality, like expanding the metadata provider, is much more likely to be implemented.

> mark coordinates

I'm not sure I know what you mean. Can you provide an example / location in code?

**Comment by JamesAPetts** [comment]
Hey all,

Just a bit of background for @dannyrb: 
DicomRT (RT for radiotherapy) are a set of DICOM SOP classes for storage of ROI data, that reference other DICOM images. For instance a DICOM RTSTRUCT is a DICOM structure that contains a bunch of contours saved in a tree structure, along with information about which DICOM scans these ROIs reference.

There are other dicomRT classes, such as RTSEG, which stores 3D(?) masks, but I am currently less familiar with these.

Back to @xhf127 's question: 

For work I've done on putting the OHIF viewer in XNAT, I've written a parser (built on dicomParser), which pulls information from an RTSTRUCT and constructs freehand ROI data in the viewer's native format. Note that this is all pre-release at the moment, but it is open source and the RTStruct reader can be seen [here](https://github.com/JamesAPetts/OHIF-Viewer-XNAT/blob/xnat-dev-xnat-roi-integration-namesAndColors/StandaloneViewer/StandaloneViewer/client/lib/ROI/classes/RTStructReader.js). It takes an RTSTRUCT in the form of an arraybuffer (pulled off XNAT through a different class), and constructs the data required in the OHIF viewer. This may be a good reference for you if you want to go the other way around.

> There is a decimal place in the mark coordinates, and I want to know why, is the coordinates in cornerstone ROI an image coordinate system, is that an integer value?

RTSTRUCT stores the ROI coordinates in real space (i.e. 3d, in mm) relative to imagePositionPatient and imageOrientationPatient. The freehand ROIs in cornerstoneTools reference pixel coordinates. Thus you need to convert to/from this reference frame using the imagePlane module of the metadata of the image. I do this when importing an RTSTRUCT. 

As far as creating DICOM RTs, I don't currently do this. Instead, I currently save to AIM imageAnnotationCollections (a different format), as this is lighter on the browser and as AIM conveniently stores ROI data in pixel coordinates).

However if you wish to undertake the challenge of writing to RTSTRUCT from your browser, [this JS library may be a good start.](https://github.com/commontk/dcmjs).

I hope some of this information was instructive/useful.

Regards,
JamesAPetts

**Comment by pieper** [comment]
@xhf127 another place to look is our work-in-progress dicom read/write tool in pure javascript, which allows you to create dicom objects in the browser:  https://github.com/pieper/dcmjs

There's no RT support in it yet, but there are SEG and SR examples and I've been working with @swederik and @galelis  on getting this integrated with OHIFViewer (https://github.com/OHIF/Viewers/tree/measurement-table)

The older version of dcjms (in the commontk organization that @JamesAPetts pointed to) is the emscripten cross-compile of dcmtk, so that might also be an option for you since it would give you access to the dcmrt library and associated utilities).  The emscripten version is heavier and arguably a kludge, but dcmtk is a solid tool so it might be a good path.

In any case, as with anything dicom related it's not trivial - let us know how it goes for you.

If anyone else is interested in helping with the dicom-creation-in-a-browser problem speak up and maybe we can all help each other.

**Comment by JamesAPetts** [comment]
Aha, I didn't realize there was a pure js version of dcmjs being worked on, I can definitely foresee this functionality being useful to a lot of people. The measurement table for OHIFViewer is also interesting, I'll keep an eye on both these projects.

**Comment by dannyrb** [comment]
Closing this as part of issue clean-up. Feel free to continue the discussion here, or if you have a new question or feature request, you can create a new issue.
