### ISSUE TITLE
PNG / JPEG ImageLoader - is it possible to load local Image?

### ISSUE THREAD

**Issue by jonaslt** [cornerstonejs/cornerstoneTools#350]
I want to load plain JPG or PNG to the image viewer - I wonder, is it possible to take images from:
1) local file system on server (as now I am only see samples for GET methods or images embeded in code).
2) maybe it would be possible to load images to cornerstone from HTML DOM? Example I can put any of the images on the web to Cornerstone viewer?
I didn't find such functionality - did I miss anything?
Thanks!

**Comment by swederik** [comment]
There is currently no file system support for the Web Image Loader, but it has been requested a few times.

There is an open ticket here: https://github.com/cornerstonejs/cornerstoneWebImageLoader/issues/13

I'll close this issue here and we can leave that one open.
