### ISSUE TITLE
Provides API to access measurement data for serialization purposes

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneTools#358]
### Prerequisites

* [ √] Are you running the latest version?
* [ √] Are you reporting to the correct repository?
* [√ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Hi:
I see cornerstoneTools has this feature:
'Provides API to access measurement data for serialization purposes (e.g. save measurements to database)'.
but I can not find the callback to get the measurement data.

And if i have some coordinate and i want draw rectangle ROI or freehand roi and etc in dicom image viewer by cornerstonetools, so how can i do?

Who can help me? thanks...

**Expected behavior:** 
1.If I use  `cornerstoneTools.rectangleRoi.activate(element, 1)` , I hope to get callback measurement data.
2.I have some coordinates, I want to draw them in dicom image viewer when display image.

**Actual behavior:** no.

**Comment by dannyrb** [comment]
### `cornerstoneTools.getToolState(DOM enabledElement, string toolType)`

- [getToolState() top level export](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/index.js#L53)
- [getToolState() usage in `length` tool](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/imageTools/length.js#L63)
- [getToolState() source](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/stateManagement/toolState.js#L37-L42)

**Example usage:**

```
const enabledElement = document.getElementById('myCornerstoneElement')
const toolType = 'length'
const toolData = cornerstoneTools.getToolState(enabledElement, toolType)
console.log(toolData)
```

_If you want to manually add data for a specific tool, you can use [`addToolState()`](https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/stateManagement/toolState.js#L20-L33). You may need to look at the source for the specific tool you're trying to add state for to make sure you're providing the state in a format it expects.

There aren't "callbacks", but we do emit events for state changes that you can listen for and handle. Some examples of emitted events for tool data changes are:

https://github.com/cornerstonejs/cornerstoneTools/blob/29182180ed3f850ba41c609b98b96464affca5f0/src/events.js#L38-L46

**Comment by hu3402379** [comment]
@dannyrb Thank you for your reply. 
I can add rectangleRoi by use 'addToolState'  in  function 'onImageRendered', and it works well.
the code like this:
`const measurementData = {
                                visible: true,
                                active: true,
                                invalidated: true,
                                handles: {
                                    start: {
                                        x: 100,
                                        y: 100,
                                        highlight: true,
                                        active: false
                                    },
                                    end: {
                                        x: 200,
                                        y: 200,
                                        highlight: true,
                                        active: true
                                    },
                                    textBox: {
                                        active: false,
                                        hasMoved: false,
                                        movesIndependently: false,
                                        drawnIndependently: true,
                                        allowedOutsideImage: true,
                                        hasBoundingBox: true
                                    }
                                }
                            }

                            cornerstoneTools.addToolState(element, 'rectangleRoi', measurementData)`

but, when I drag the rectangle start point or end point to change it's size, the old rectangle is still exist and generate a new rectangle.
I don't know how to upload image in issue, so if you have time, you can test it.

another question: how to hide the textBox, I hope that when drawing a rectangle, textBox do not show.

thank you very much.

**Comment by dannyrb** [comment]
Shoot. It looks like I don't get notifications when the most recent message in a thread is edited. I'll take a stab at providing a response here soon @hu3402379.

Initial thoughts:
1. Have you tried toggling `hasBoundingBox`? (I'm not sure what it does)
2. It may require an API change. If you propose one, and create a PR, we could potentially merge it to give you the ability to not show the textbox.

**Comment by dannyrb** [comment]
I think we solved the root of this, so I'm closing the issue. I'll continue to monitor your PR 👍

**Comment by haoxl3** [comment]
@hu3402379 hi,  I have the same problem as you, but my rectangleRoi is rendered in function 'onImageRendered' , but it doesn't work.  I have to click the rectangle button before the rectangle is displayed. 
Do you know how to make the rectangle display immediately ? 
my code:
```
cornerstone.loadImage(imageId).then(image => {
            cornerstone.displayImage(this.canvas, image);
            
            const measurementData = {
                visible: true,
                active: true, // false,
                color: 'red',
                invalidated: false,
                handles: {
                    start: {
                        x: 235.52,
                        y: 180.90666666666667,
                        highlight: true,
                        active: true, // false,
                        hasMoved: true
                    },
                    end: {
                        x: 265.38666666666666,
                        y: 219.30666666666667,
                        highlight: true,
                        active: true // false
                    },
                    initialRotation: 0,
                    textBox: {
                        active: false,
                        hasMoved: false,
                        movesIndependently: false,
                        drawnIndependently: true,
                        allowedOutsideImage: true,
                        hasBoundingBox: true,
                        x: 265.38666666666666,
                        y: 200.10666666666668,
                        boundingBox: {
                            width: 286.80419921875,
                            height: 45,
                            left: 591,
                            top: 212.00000000000003
                        }
                    }
                },
                cachedStats: {
                    area: 790.2341370000175,
                    count: 1170,
                    mean: -302.44444444444446,
                    variance: 247523.8041785375,
                    stdDev: 497.51764207768304,
                    min: -1024,
                    max: 459,
                    meanStdDevSUV: undefined
                },
                unit: 'HU'
            };
            cornerstoneTools.addToolState(this.canvas, 'RectangleRoi', measurementData);
        });
```

**Comment by dannyrb** [comment]
@haoxl3, please create a new issue for this question
