### ISSUE TITLE
Non intuitive rotation

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#359]
Rotation is IMHO currently very unintuitive (mouse and touch input). When the user holds and drags somewhere in the image the rotation "jumps" dependent on how far the pointer is away from an imaginary 12 o'clock line. It would be more natural if the initial button down determines the zero line and every move is relative to this line.

An example to illustrate this:

The current way:
- Click and hold mouse button at 3 o'clock position of the image.
- Move mouse a bit while holding the mouse button
- Image rotation jumps by 90° (plus/minus some degrees dependent on the movement)

The improved way:
- Click and hold mouse button at 3 o'clock position of the image.
- Move mouse a bit while holding the mouse button
- Image rotates just a few degrees depending on the pointer movement

I would be happy to come up with a PR for that, just need some time.

**Comment by medihack** [comment]
@swederik I work as a radiologist and use this tool quite often, especially for MSK CT/MRI imaging (arms or legs often lie a bit different) and pancreas CT imaging (side of the body is a bit elevated to better distinguish the head of the pancreas from the duodenum). To rotate the image back helps while reporting (radiologists mostly prefer strict axial, sagittal or coronal views). Most PACS viewers I know of only allow to rotate by 90° degree steps, which I really view as an impractical restriction. So in short, I really like this feature and will see how I can improve it :-)

**Comment by jdnarvaez** [comment]
FWIW this was one of the most requested tools by a few of our clients for awhile.

**Comment by swederik** [comment]
Well I stand corrected! Thanks for the input!
