### ISSUE TITLE
Add API setting/param to hide ROI tool's textbox

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneTools#361]
Hi. man,
I have a suggestion. Can you provide a demo for this function:

If i  have rectangleRoi coordinates, it can display the rectangle on image when image rendered, and the rect can be draged, move, resize.

I think it's very useful for some users.

And another suggestion, can you provide an api or parameter to hide the textBox.

Best wish for great developers! thanks

**Comment by dannyrb** [comment]
> If i have rectangleRoi coordinates, it can display the rectangle on image when image rendered, and the rect can be draged, move, resize.

[Rectangle ROI Tool can be demoed here](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/allImageTools/index.html)

Or did you mean restoring state from known Rectangle ROI coordinates, and then allowing the user to use the Rectangle ROI tool?

> And another suggestion, can you provide an api or parameter to hide the textBox.

I'll update your title to include this an enhancement suggestion

**Comment by hu3402379** [comment]
>Or did you mean restoring state from known Rectangle ROI coordinates, and then allowing the user to use the Rectangle ROI tool?
yes, I have achieved this function, and code like this, If someone need:
```
function onNewImage(e) {
    const measurementData = {
             visible: true,
             active: true,
             invalidated: false,
             handles: {
                   start: {
                       x: 100,
                       y: 100,
                       highlight: true,
                      active: false
                      },
              end: {
                     x: 200,
                     y: 200,
                     highlight: true,
                     active: true
                  },
              textBox: {
                    drawnIndependently: true,
                    hasBoundingBox: true,
                    hasMoved: false,
                    movesIndependently: false
               }
           }
    }
 cornerstoneTools.addToolState(element, 'rectangleRoi', measurementData)
}
```
My project has a demand is only displayed the measurement tools, but not textbox, I have see the source code, 
>cornerstoneTools/src/imageTools/rectangleRoi.js

I can hide the textbox when initializing the rectangle roi，  but if I resize the rectangle, the textbox will display.

**Comment by hu3402379** [comment]
I have rebuilded the source code add a condition parameter when drawing textbox.

But I still hope there can be a parameter or API to on/off the textbox like:

````
cornerstoneTools.rectangleRoi.setConfiguration({drawHandlesOnHover: true})

**Comment by dannyrb** [comment]
We're pretty open to API change suggestions. If you're already modifying an rebuilding the source, why not submit a pull request so you don't need to maintain a fork?

**Comment by dannyrb** [comment]
I've left a note in your PR and added a corresponding issue to add this in the `vNext` branch. It likely won't make the 3.0 milestone, but is a good candidate for 3.0.x
