### ISSUE TITLE
Ability to import individual tools from the module, without pulling in all files

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#364]
**Problem:** Our documentation currently recommends importing `cornerstoneTools` like so:

```
// Cornerstone Libraries
import * as cornerstone from 'cornerstone-core'
import * as cornerstoneMath from 'cornerstone-math'
import * as cornerstoneTools from 'cornerstone-tools'
```

Which has the unfortunate side-effect of including all of `cornerstoneTools` in your output bundle. Minified, that's just under 200KB. Unminified? over 500KB.

**Ideally, we want:**

- To make it easier to decrease output bundle size
- To know which parts of `cornerstoneTools` your application depends on
- To increase developer familiarity with the library's namespacing
- To make it easier to leverage advanced bundler features (splitting, dynamic imports, tree shaking, etc)

**Okay, but how do we accomplish this?**

_Here are a few examples of potential ways to enable two elements, and then activate the `wwwc` and `wwwcTouchDrag` tools for each element:_

_Current Approach:_ 
```
import * as cornerstone from 'cornerstone-core'
import * as cornerstoneMath from 'cornerstone-math'
import * as cornerstoneTools from 'cornerstone-tools'

// Create two enabled elements/canvases
cornerstone.enable(myEnabledElement)
cornerstone.enable(myEnabledElement2)

// Setup tools for first element
cornerstoneTools.mouseInput.enable(myEnabledElement)
cornerstoneTools.wwwc.activate(myEnabledElement, 1)
cornerstoneTools.wwwcTouchDrag.activate(myEnabledElement)

// Setup tools for second element
cornerstoneTools.mouseInput.enable(myEnabledElement2)
cornerstoneTools.wwwc.activate(myEnabledElement2, 1)
cornerstoneTools.wwwcTouchDrag.activate(myEnabledElement2)
```

_New Approach 1:_ Uses a per instance config/settings to define behavior
```
import * as cornerstone from 'cornerstone-core'
import * as cornerstoneMath from 'cornerstone-math'
import CornerstoneTools from 'cornerstone-tools'

// Contains registration logic for wwwcMouse and wwwcTouchDrag
import { wwwc } from 'cornerstone-tools/core-tools'

cornerstone.enable(myEnabledElement)
cornerstone.enable(myEnabledElement2)

const csTools = new CornerstoneTools({
    // csTools.activateTool() applies to all enabledElements
    snycToolStatesAcrossEnabledElements: true,
    
    // csTools.activateTool() registers mouse AND touch versions of a tool
    // if an implementation for both exists
    registerMouseAndTouch: true
})

csTools.activateTool(wwwc, { mouseButton: 'left' })
```

_New Approach 2:_ Prefer explicit methods over per instance configuration settings
```
import * as cornerstone from 'cornerstone-core'
import * as cornerstoneMath from 'cornerstone-math'
import CornerstoneTools from 'cornerstone-tools'

import { wwwcMouse, wwwcTouchDrag } from 'cornerstone-tools/core-tools'

cornerstone.enable(myEnabledElement)
cornerstone.enable(myEnabledElement2)

const csTools = new CornerstoneTools()

// Applied to all enabled elements
csTools.activateTool(wwwcMouse, { mouseButton: 'left' })

// Applies to specified enabled element
csTools.activateToolForElement(wwwcTouchDrag, myEnabledElement)
csTools.activateToolForElement(wwwcTouchDrag, myEnabledElement2)
```

### Summary

This would be a big change, and there are a lot of ways to approach this problem. It's worth noting that a change like this, while it allows us to "import individual tools from the module, without pulling in all files", it also opens up the door to a friendlier API, and is an important stepping stone toward _extending tools, registering 3rd party tools, and supporting more complex tools that rely on 3rd party libraries._

Any/all thoughts and contributions on this topic are welcome 👍  Even if it's to tell me that I'm approaching this problem in entirely the wrong way ☝️ 

Tagging some of our more frequent contributors to pick their brains:
@medihack, @swederik, @jpambrun, @adreyfus, @radicalrob, @leonardorame

**Comment by medihack** [comment]
Sounds like a great idea. I like the second explicit approach much better. The first approach to enabling touch events by a global configuration and then adding a `mouseButton` option when activating the tool looks IMHO a bit cumbersome. The second approach looks more hardware agnostic and easier to extend for possible other input methods. And why not just use `csTools.activateTool(enabledElement, tool, toolOptions)`? A developer could easily loop through the enabled elements himself. The smaller and more precise the API the easier to work with it. I also like the renaming of `wwwc` to `wwwcMouse`, much cleaner as the mouse is just an input method like touch.

**Comment by dannyrb** [comment]
Thanks for the feedback, @medihack!

Your thoughts make a lot of sense. A smaller, more precise API would be easier to maintain and it would be less confusing. Part of the reason we're making this change in the first place is because the library has grown too large. That being said, are there common use cases we should account for or make easier? For example:

_External API_

- The ability to activate tools in the same _family_ (same tool, different input type) at the same time
- Applying tool activation/deactivation across all, or a range, of enabledElements
- Deactivate all tools for all canvases, or a specified canvas

_Internal_

- Tracking activated tools per enabledElement
- Tracking enabled input types per enabledElement
- Automatically disabling/enabling input type based on currently activated tools

For a first pass, I think we should keep the _External API_ small, but it may be worth considering what we track internally, and if it's worth supporting/maintaining a certain level of helper/utility methods that make common implementations easier.

I'm happy you like me renaming of `wwwc` to `wwwcMouse`. It's always irked me, because I find the naming of tools like `wwwcTouchDrag` incredibly helpful.

**Comment by dannyrb** [comment]
As an update, this is coming along nicely in `vNext`. Modules are smaller and more explicit in their dependencies. You must import each tool you'd like to use individually. Complicated, less common, tools are relegated to 3rd party plugins.

The last major hurdle is updating our output such that WebPack can more easily determine which bits were unused by the dependent application (using harmony comments), and then allowing something like Uglify to prune unused code.

Oddly, to accomplish this, we would need to punish unmimified, and unbundled code (ie. Native modules that more closely resemble the original source)
