### ISSUE TITLE
Linter should validate JSDoc comments

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#366]
Now that we're relying on `jsdoc` syntax to generate our API docs, we should lint our `jsdoc` comments to make sure they're valid. The `documentation` npm package we're using recommends:

https://eslint.org/docs/rules/valid-jsdoc

**Comment by swederik** [comment]
Should be easy enough to uncomment this: https://github.com/cornerstonejs/cornerstoneTools/blob/master/.eslintrc.js#L257

(but be prepared for the flood of warnings...)

**Comment by swederik** [comment]
Fixed in #574

**Comment by pieper** [comment]
Are the docs being generated and hosted somewhere?

**Comment by swederik** [comment]
They are here at the moment, but could use a lot of cleanup / organization:
https://tools.cornerstonejs.org/api.html

For reference, here is how they are in core (slightly better): https://docs.cornerstonejs.org/api.html

**Comment by pieper** [comment]
Cool thanks 👍
