### ISSUE TITLE
Refactor image tools folder

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#376]
While working on the rotation fix I found it a bit cumbersome that mouse events (`simpleMouseButtonTool`) and touch events (`touchDragTool`, `touchPinchTool`, ...) are so differently handled. Especially those touch functions where I had to introduce a new `simpleTouchTool` function as the other basic touch functions make too many assumptions.

How about a new (file/folder) layout of the image tools? Something like this:

<pre>
imageTools/
  rotate/
    rotateCommon.js
    rotateMouse.js
    rotateTouchDrag.js
    rotateTouchRotate.js
  zoom/
    zoomCommon.js
    zoomMouse.js
    zoomTouchDrag.js
    zoomTouchPinch.js
  ...
  simpleMouseButtonTool.js
  simpleTouchTool.js
</pre>

In the `*Common.js` files, we could put the shared code of the different input methods. While input source specific code is in its own file. If I remember correctly we somewhere had already a similar discussion, but couldn't find it anymore :-/

We could also get rid of all those basic touch function files (`touchDragTool`, `touchPinchTool`, ...), but for this to work, we have to listen to some additional Hammer events (like `pinchend`) in `inputSources/touchInput.js`. Maybe this would add a bit more code, but afterward, touch events and mouse events are handled more similar, which again improves the overall code quality.

What do you think?

**Comment by dannyrb** [comment]
We're starting to make the folder/file structure a bit more intuitive to prep for importing individual tools, rather than being forced to import them all when you `import * as cornerstoneTools from 'cornerstone-tools'`

This is a good add. I'll see about adding it to the in-progress PR

**Comment by dannyrb** [comment]
@medihack, I'm going to close this issue for now. If you find the time, it would be nice to discuss your thoughts on the new `vNext` folder structure. I'm particularly interested in any ideas you have around:

- How to align touch/mouse Event dispatchers
- Which touch events you believe need to be added to align tool behavior
- The new base tools and their support for different "interaction paradigms"
