### ISSUE TITLE
Reference lines don't work on some files

### ISSUE THREAD

**Issue by hardmaster92** [cornerstonejs/cornerstoneTools#379]
### Description

I've been using cornerstoneTools for many years and the reference lines tool always worked fine. But recently I noticed that the lines don't show up on some specific CT series. I tested the same series with desktop viewers like RadiAnt and everything worked fine there. Could it be some missing meta data that can be obtained from the files?

### Steps to Reproduce
I provide you the same study so you can see it for yourself: https://drive.google.com/open?id=1gKaHTeZ00x9C0miSFPaj9fWdnfcrLYJV
1. Download the zip file and extract it
2. Use CT.1.2.826.0.1.3680043.2.600.1.4.3563692304.3788.1522840811.9.dcm as a source element and some of the other series as a target element

OR

1. Open a link to this study on our demo viewer: http://demo.pacs.bg:8081/scpacs/en/WebViewer/Index?UID=1.3.12.2.1107.5.1.4.78923.30000018022706245242100000007&UID_Level=1
**Username: demo
Password: demo**
2. Use the "Split Screen" button to add more views and drag the second or the third series.
3. The reference lines won't show
4. If you need to look at a study where the reference lines work you can check this one for example:
http://demo.pacs.bg:8081/scpacs/en/WebViewer/Index?UID=1.2.826.0.1.3680043.2.600.1.2.2406857181.14472.1509618993.540&UID_Level=1

**Comment by hardmaster92** [comment]
We tried adding this line:
`line.end.add(direction.multiplyScalar(0.5));`
to src/util/pointProjector.js 
below
`119 line.start = origin;`
`120 line.end = origin.clone().add(direction.multiplyScalar(distance));`
 and the reference lines work now. However we are not sure if this is the correct way.

**Comment by dannyrb** [comment]
Hi @hardmaster92, do you encounter this same issue in Version 3? If so, can you create a new issue and reproduction?

If this issue doesn't see much more activity, I will likely close it within the next 6-months.
