### ISSUE TITLE
stackScroll loop and not allowSkipping may block

### ISSUE THREAD

**Issue by sculxp** [cornerstonejs/cornerstoneTools#389]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description
I am using https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/util/scroll.js/#L35 to implement this:
click 'previous' button  -> display the previous image,
click 'next' button -> display the next image

something like this
```
// previous,  loop: true, allowSkipping: false
cornerstoneTools.scroll(this.element, -1, true, false);

// next
cornerstoneTools.scroll(this.element, 1, true, false);
```
after scroll from first to last through previous button, scroll no longer works.

### Steps to Reproduce

1. in scroll function:
```
export default function (element, images, loop = false, allowSkipping = true) {
  ...
  //loop= true
  if (loop) {
    const nbImages = stackData.imageIds.length;
    //newImageIdIndex may be -1
    newImageIdIndex %= nbImages;
  } 
  ...
  //allowSkipping=false
  if (allowSkipping) {
    scrollToIndex(element, newImageIdIndex);
  } else {
    const pendingEvent = {
      index: newImageIdIndex
    };

    stackData.pending.push(pendingEvent);
    scrollWithoutSkipping(stackData, pendingEvent, element);
  }
 ...
}
```

2. in scrollWithoutSkipping function:
```
function scrollWithoutSkipping (stackData, pendingEvent, element) {
   if (stackData.pending[0] === pendingEvent) {
    ...
    const newImageHandler = function (event) {
      //index won't be -1 (normally) , so the first pendingEvent is not removed, which cause the block
      const index = stackData.imageIds.indexOf(event.detail.image.imageId);

      if (index === pendingEvent.index) {
        stackData.pending.splice(stackData.pending.indexOf(pendingEvent), 1);
        element.removeEventListener('cornerstonenewimage', newImageHandler);

        if (stackData.pending.length > 0) {
          scrollWithoutSkipping(stackData, stackData.pending[0], element);
        }
      }
    };
   ...
   }
}
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
stackScroll blocked.

### Codepen With Reproduction of Issue:
I can not access rawgit.com easily,  so no reproduction code at the moment.

**Comment by sculxp** [comment]
Yes, but it's not a big problem.

**Comment by dannyrb** [comment]
This issue has not seen much activity. I'm going to close it for now. Please feel free to comment here, either with a reproduction, or to continue the discussion and we can re-open if need be.
