### ISSUE TITLE
Uncaught TypeError: Cannot read property 'point' of undefined     at HTMLDivElement.g (app.js:50865)

### ISSUE THREAD

**Issue by rangata** [cornerstonejs/cornerstoneTools#396]
Hello, Guys!

I just started to develop my own project using cornerstone libraries on top of Laravel 5.6 + Vue.

The image element init, but when I try to apply any filter from cornerstoneTools I get this errorUncaught TypeError: Cannot read property 'point' of undefined     at HTMLDivElement.g (app.js:50865)

Here is my source code:
<template>
<div>
    <div class="row">
        <div class="row">
            <div class="col-xs-2">
                <ul class="list-group">
                    <a href="#" id="disable" class="list-group-item">Disable</a>
                    <a href="#" id="enable" class="list-group-item">Enable</a>
                    <a href="#" id="activate" class="list-group-item">Activate</a>
                    <a href="#" id="deactivate" class="list-group-item">Deactivate</a>
                    <a href="#" id="defaultStrategy" class="list-group-item">Default Strategy</a>
                    <a href="#" id="osirixStrategy" class="list-group-item">Osirix Strategy</a>

                </ul>
            </div>
            <div class="col-xs-6">
                <div style="width:512px;height:512px;position:relative;display:inline-block;color:white;"
                     oncontextmenu="return false"
                     class='cornerstone-enabled-image'
                     unselectable='on'
                     onselectstart='return false;'
                     onmousedown='return false;'>
                    <div id="dicomImage"
                         style="width:512px;height:512px;top:0px;left:0px; position:absolute;">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</template>
<script>
    // var imageId = 'http://localhost:8000/image/preview.png';
    import Hammer from 'hammerjs';                    // npm install --save hammerjs
    import * as cornerstone from 'cornerstone-core';  // npm install --save cornerstone-core
    import * as cornerstoneTools from 'cornerstone-tools';
    import * as cornerstoneWebImageLoader from 'cornerstone-web-image-loader';

    // Specify external dependencies
    cornerstoneTools.external.cornerstone = cornerstone;
    cornerstoneTools.external.Hammer = Hammer;
    cornerstoneWebImageLoader.external.cornerstone = cornerstone;

    export default {
        name: "EditPatient",

        mounted() {
            cornerstoneTools.wwwc.strategies.osirix  = function(eventData) {
                var imageDynamicRange = eventData.image.maxPixelValue - eventData.image.minPixelValue;
                var multiplier = imageDynamicRange / 1024;

                var deltaX = eventData.deltaPoints.page.x * multiplier;
                var deltaY = eventData.deltaPoints.page.y * multiplier;

                eventData.viewport.voi.windowWidth += (deltaX);
                eventData.viewport.voi.windowCenter -= (deltaY);
            };

            var element = document.getElementById('dicomImage');

            var imageId = 'http://localhost:8000/image/preview.png';

            // image enable the dicomImage element
            cornerstone.enable(element);
            cornerstoneTools.mouseInput.enable(element);

            cornerstone.loadImage(imageId).then(function(image) {
                cornerstone.displayImage(element, image);

                // Enable all tools we want to use with this element
                cornerstoneTools.wwwc.activate(element, 1);
                activate("activate");

                function activate(id) {
                    document.querySelectorAll('a').forEach(function(elem) {
                        elem.classList.remove('active');
                    });

                    document.getElementById(id).classList.add('active');
                }

                // Tool button event handlers that set the new active tool
                document.getElementById('disable').addEventListener('click', function() {
                    activate("disable");
                    cornerstoneTools.wwwc.disable(element);
                    return false;
                });
                document.getElementById('activate').addEventListener('click', function() {
                    activate("activate");
                    cornerstoneTools.wwwc.activate(element, 1);
                    return false;
                });
                document.getElementById('defaultStrategy').addEventListener('click', function() {
                    activate("defaultStrategy");
                    cornerstoneTools.wwwc.strategy = cornerstoneTools.wwwc.strategies.default;
                    cornerstoneTools.wwwc.activate(element, 1);
                    return false;
                });
                document.getElementById('osirixStrategy').addEventListener('click', function() {
                    activate("osirixStrategy");
                    cornerstoneTools.wwwc.strategy = cornerstoneTools.wwwc.strategies.osirix;
                    cornerstoneTools.wwwc.activate(element, 1);
                    return false;
                });
            });
        }
    }
</script>

<style scoped>

</style>

**Comment by ofleaf** [comment]
did you fixed it?

**Comment by dannyrb** [comment]
Do you have a repository or [codesandbox](https://codesandbox.io/) you can share that produces this error? Also, your code formatting is a bit off. Can you edit your question to make it easier to read?

**Comment by ofleaf** [comment]
@dannyrb Could you check my repo?
[https://github.com/ofleaf/webpacs-proto](url)

**Comment by dannyrb** [comment]
This component? I'll take a peak on Monday:
- https://github.com/ofleaf/webpacs-proto/blob/master/src/components/worklist/WorkList.vue

We're using Cornerstone + Vue in production, so it shouldn't be too hard to see what we're doing differently.

**Comment by ofleaf** [comment]
@dannyrb Yes, the WorkList.vue component. Could you tell me which part is causing the problem?

**Comment by dannyrb** [comment]
It's a little bit easier to see when you use the unminified version of cornerstone-tools for development. You can do that by changing your import:

_minified (default):_
`import * as cornerstoneTools from 'cornerstone-tools';`

_unminified:_
`import * as cornerstoneTools from 'cornerstone-tools/dist/cornerstoneTools.js';`


![image](https://user-images.githubusercontent.com/5797588/42347296-7cf49e08-8073-11e8-83a0-ea046af31977.png)

The error I'm seeing shows that you didn't setup `cornerstoneMath` as an external dependency. It's likely used by one of the tools for help calculating something.

**Comment by ofleaf** [comment]
@dannyrb Thanks for reply. I fixed it.
`cornerstoneTools.external.cornerstoneMath = cornerstoneMath`
