### ISSUE TITLE
how to get all dicoms pixels

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneTools#400]
### Prerequisites

* [ √] Are you running the latest version?
* [√ ] Are you reporting to the correct repository?
* [ √] Did you perform a cursory search?

### Description
Hi, I have a question.

If I have a series, it includes about 100 dicom files.

For example, sheets 3 to 10, each with a rectangle，
and I need to calculate the sum of the pixels in the 3rd to 10th rectangles。

I have read the source code, 

`cornerstone.getPixels(element, left, top, width, height)`

Now I can scroll to the 3rd pixel of calculation and then scroll to the next calculation until I get to the 10th sheet and calculate their sum。

I think this is unwise。

I want to get all the element pixels in the first one。So，how can i solve it。

thanks。

**Comment by dannyrb** [comment]
While you could probably create something like this in `cornerstone-tools`, the `cornerstone` repository may be a better candidate.

It may be worth recreating this issue in that repository. If you feel I am mistaken, please feel free to comment and we can consider reopening this issue.
