### ISSUE TITLE
Calculate the volume

### ISSUE THREAD

**Issue by xhf127** [cornerstonejs/cornerstoneTools#408]
### Prerequisites

* [√] Are you running the latest version?
* [√] Are you reporting to the correct repository?
* [√] Did you perform a cursory search?

### Description
If I make different ROI markings on the adjacent layers, I have the area. How do I calculate the volume of these ROI layers?

**Comment by JamesAPetts** [comment]
This isn't yet implemented. I have intention of eventually doing this at some point in the future, but it is not yet high priority.

From a more conceptual standpoint, what needs to be done is to parse the series of ROIs and calculate the volume of each slice using the two rois that surround it (whilst knowing the slice thickness), and splitting this up into simple easily calculable shapes. There are standard algorithms for doing this in the literature.

**Comment by pieper** [comment]
Here's some useful background on the topic of calculating volumes from slices:

http://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html

**Comment by JamesAPetts** [comment]
This brings up some good points, if you just want the volume of all the voxels completely enclosed within the VOI, we already have all of the information. Sum up the volume of pixels within the current mask aswell as above and below (with some neuances for the top and bottom of the volume.

Of course calculating the volume of the isosurface (if required) is a little more imvolved.

P.S. I think this should probs be part of cornerstone math no? As long as it can be relatively agnostic to tool format.

**Comment by xhf127** [comment]
I see, thank you.

**Comment by dannyrb** [comment]
@jamesAPetts, before I tag this, do you see calculations like this as part of the tools library, or as a 3rd party tool? Should we consider adding a new baseTool to assist, or any helper methods?

**Comment by JamesAPetts** [comment]
I would think this functionality could be added to cornerstone-math at some point, as long as it is kept generic enough, with an array of roi's being one possible input. I think we'd have a better idea where it should go when/if we implement this though. I personally don't think its essential for v3.0 though.

**Comment by dannyrb** [comment]
I believe the question here has been answered. We can create a new issue for discussion/implementation details should/when we decide to move forward on this.
