### ISSUE TITLE
How to delete current draw tools on canvas

### ISSUE THREAD

**Issue by jackyshaw2017** [cornerstonejs/cornerstoneTools#413]
when  I  press keyboard 'delete',I want to delete current draw  with green color,Is there a solution？

![qq 20180601102701](https://user-images.githubusercontent.com/30282633/40817714-6f16ee38-6586-11e8-8f93-63246c6f1de2.png)

**Comment by jackyshaw2017** [comment]
![qq 20180601102701](https://user-images.githubusercontent.com/30282633/40817694-5be8a02c-6586-11e8-93c4-5b740350f314.png)

**Comment by JamesAPetts** [comment]
We have a new eraser tool that was implemented in PR #433.

You can check it out on the allImageTools example page.

**Comment by dannyrb** [comment]
Per @JamesAPetts comment, you can find the eraser tool example demo + src here:

[All Image Tools Example Page](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/allImageTools/index.html)

[All Image Tools Source Code](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/allImageTools/index.html)

If you'd rather not enable the eraser tool, you can drag the annotation "off canvas" and it will be removed.
