### ISSUE TITLE
stop scrolling page only when mousewheel is over element

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneTools#414]
I have this use case where a page has a long list of cornerstone elements, and would like to disable the page scroll only when the user scrolls over any image (I have stackScrollWheel enabled), but let the page scroll when the user use the mouse wheel outside the cornerstone elements.

In the following image, if the user moves the mouse over the gray area (left and right side of the image grid) and uses the mouse wheel, the page should scroll, but if the user positions the mouse pointer over any image it should scroll the image stack, but not the page.

![image](https://user-images.githubusercontent.com/1405017/40838007-b31e0a1c-6572-11e8-9305-3f5a3b5e22ea.png)

Can you help me with this?.

**Comment by dannyrb** [comment]
Interesting use case. Most viewers I've seen so far accomplish this by having a page who's height never exceeds 100% (ie. there's nothing to scroll to). Part of me is wondering if this is the best UX for the view you're trying to accomplish?

You can't cancel or stop the propagation of a `scroll` event, but you can cancel the `mouse`, `touch scroll` and keyboard `buttons` associated with scrolling (effectively preventing scrolling):

https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily

For your use case, you'd want to prevent the mouse/touch events when a user is interacting with a canvas, after normal canvas interactions have occurred.

**Comment by leonardorame** [comment]
Hi @dannyrb, yes, I can disable scroll on the element's DIV by using this code:

      cellDiv.onwheel = function(e) {
        e = e || window.event;
        if (e.preventDefault)
            e.preventDefault();
        e.returnValue = false;
      };

But this also prevents stackScroll from working, is there a way to call stackScroll manually in these cases?.

**Comment by leonardorame** [comment]
I solved it by replacing `overflow: auto` with `overflow: hidden` and implementing a page panning by using `$('.viewport').scrollTop` and `$('.viewport').scrollLeft`.

Regards,
Leonardo.
