### ISSUE TITLE
Brush tool render in every image of stack after deactivate

### ISSUE THREAD

**Issue by chungchi300** [cornerstonejs/cornerstoneTools#418]
### Steps to Reproduce

1. Draw brushes on Stack A
2. Deactivate brush by 
```
    cornerstoneTools.brush.deactivate(element);
```

3. Move stack to Stack B

**Expected behavior:** The brushes should not render in Stack B

**Actual behavior:** Visible in stack B,even in C

### Codepen With Reproduction of Issue:

- [Brush tool render in every image of stack after deactivate ](https://codepen.io/chungchi300/pen/RJgbJN)

**Comment by JamesAPetts** [comment]
I've fixed this in PR #434 :).
