### ISSUE TITLE
More complex activation scenarios of tools.

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#422]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description
At the moment it is not possible (as far as I know) to only activate a tool when for example a key and button is pressed at the same time (e.g. shift key + left mouse button == drag, but only left mouse button == zoom).

 I am not sure what a good implementation of such functionality would be. A possible solution I can think of would be to let the user provide a callback function (instead of a `mouseButtonMask`) when calling the `activate` function so that he can programmatically decide if the tool is triggered or not. 

Something like:
```
cornerstoneTools.zoom.activate(element, eventData => {
	if (eventData.event.shiftKey && event.which === 2)
		return true;
	return false;
});

What do you think? Would you solve this somehow else?

**Comment by dannyrb** [comment]
@medihack we have a _very rough_ roadmap where we shift the `activate` method to live on `cornerstoneTools`, and you pass it:

- The tool you'd want to activate
- The element to activate the tool for
- etc.

As well as some advanced tool management shifted down from the OHIF repo. I think it will be easier to add more advanced activation scenarios when we have a single activation point for all tools. I also think we need to find the time to publish a more visible roadmap, and track its progress.

That being said, your proposed change makes sense for our current API, and can probably be done without a major version bump. Sorry for digressing, it felt relevant enough to mention.

**Comment by medihack** [comment]
@dannyrb Thanks for the explanation. Do you already have some (rough) specification somewhere of the upcoming API? Is there already something coded (which branch)? What do you think when it will be merged into the master branch (weeks? month?).

Yes, I think the above suggestion can be done without a major version dump. But it is still a bit of work as currently all `isMouseButtonEnabled` checks are done in the tools itself (e.g. [wwwc](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/wwwc.js#L24)). I think it makes sense to move those checks to `simpleMouseButtonTool` and handle it there.

Dependent on how long it will take for the new API to be released I will add the feature to the current one. But if the new API is somewhere near, maybe it would make more sense that I help a bit there.

**Comment by dannyrb** [comment]
@medihack, 2 months later... Haha

The `vNext` branch will eventually become `v3` and be merged into master. All of the `mouseButtonMask` filtering takes place in the `eventDispatchers`. Adding the behavior you want would be a much, much easier enhancement in the new branch.

Maybe take a peak and we can discuss possible implementations? I don't see this as a blocker for `vNext` release, but it does look like a nice and easy value add. If you want assistance or a walkthrough before you get started, llease don't hesitats to reach out.

Note: add to vNext project board, create new version labels to help indicate which features are (non)blocking

**Comment by dannyrb** [comment]
Duplicates: https://github.com/cornerstonejs/cornerstoneTools/issues/177

I've added a comment there regarding this functionality. There are technically ways to achieve it in vNext for custom tools. Updating the EventDispatchers to handle this would be easy enough, but it's at least worth discussing if this is the best path forward.

**Comment by dannyrb** [comment]
See comments in #177. I'm open to adding something like this to our roadmap, but I want to be sure that tools with key modifiers aren't the better decision here. Feel free to kickstart this conversation again.
