### ISSUE TITLE
freehand tool doesn't expose `pointNearTool`

### ISSUE THREAD

**Issue by dlwire** [cornerstonejs/cornerstoneTools#427]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

The other tools I consume from imageTools expose a `pointNearTool` function which allows me to check if a mouse click is near tool data in a way which is specific to the tool itself. I've been using this to write an eraser tool, which I'd be happy to contribute back if there's interest. However, the freehand roi tool doesn't expose this function. If I'm right, please confirm, this would just be adding `pointNearTool` to https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/freehand.js#L1163. Happy to get a PR together for that, just let me know if I'm on the right track.

### Steps to Reproduce

1. inspect cornerstoneTools.freehand

**Expected behavior:** It includes a `pointNearTool` function

**Actual behavior:** It doesn't

### Codepen With Reproduction of Issue: https://codepen.io/dlwire/pen/bKOmqx

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by swederik** [comment]
@JamesAPetts Mind including that in your next update?

**Comment by JamesAPetts** [comment]
@swederik , sure thing, I'll get on this with the next push!
A global eraser tool sounds really useful @dlwrie!

Thanks,

JamesAPetts

**Comment by JamesAPetts** [comment]
This should be solved by PR #431.
