### ISSUE TITLE
Does reference line display the cutting view or is it separate image ?

### ISSUE THREAD

**Issue by algates90** [cornerstonejs/cornerstoneTools#435]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

The example of reference lines shows as if two separate images are loaded to two cornerstone elements and synchronized. 

My question is if you have series of images belonging to the same CT loaded into one element and applying a reference line on that will display the cutting view on another element. Is this possible ? Does reference lines solve this purpose ?

**Comment by algates90** [comment]
@swederik  @dannyrb  Is there an updated example on how to implement the reference lines with the new metadata provider in place (referring to closed issue #242) ??

**Comment by swederik** [comment]
Hi there,

I do not understand your initial question. What do you mean by cutting view? The reference lines only project the corners of one image onto the viewport displaying a second image.

**Comment by algates90** [comment]
Is it possible to have different views like this using cornerstone ??

http://rii.uthscsa.edu/mango/papaya/

**Comment by swederik** [comment]
That is multiplanar reformatting. It is independent of the reference line functionality. It is possible but you will have to write an image loader to load your volumetric data and reslice it to create the image you want.

**Comment by algates90** [comment]
@swederik Thanks a lot for your clarification. I was in an impression that reference lines somehow relates to this.

I understand that Multiplanar reconstruction is necessary to implement such views. Is it already in the roadmap for cornerstone ?

**Comment by swederik** [comment]
Yes I think we might add an example of how to do basic orthogonal MPR to cornerstoneTools soon.

**Comment by dannyrb** [comment]
I believe the question has been answered, so I will close this issue. Please feel free to create a new issue if you have additional questions.

**Comment by krishnauppili** [comment]
Hi @swederik ,

Is there any update on adding basic orthogonal MPR to cornerstoneTools?
