### ISSUE TITLE
deactivate freehand tool breaks all other tools

### ISSUE THREAD

**Issue by caoool** [cornerstonejs/cornerstoneTools#437]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

deactivate freehand tool will cause other tools stop working

### Steps to Reproduce

1. Deactivate all other tools 

2. Activate targeting tool

3. rectangleRoi tool or other tools will not work

**Expected behavior:** Switching tools like usual, deactivating all other tools than activate targeting tool

**Actual behavior:** Other tools will not activate after deactivate freehand tool

### Codepen With Reproduction of Issue:

```
deactivateAll = (element) => {
    cornerstoneTools.stackScroll.deactivate(element)
    cornerstoneTools.zoom.deactivate(element)
    cornerstoneTools.wwwc.deactivate(element)
    cornerstoneTools.rectangleRoi.deactivate(element)
    cornerstoneTools.freehand.deactivate(element)
}
```
```
toggleRect = (e) => {
    const element = document.getElementById('dicomImage')
    this.deactivateAll(element)
    cornerstoneTools.rectangleRoi.activate(element, 1)
}
```

**Comment by JamesAPetts** [comment]
Hmm, what do you mean by step 2: "Activate targeting tool"? And how is the problem related the freehand tool in the example you give?

Running examples/allImageTools, everything is working is expected, same if the tool is imported into the OHIF viewer.

Perhaps you've found an edge case, and any more information would be appreciated!

**Comment by caoool** [comment]
Thanks for the quick respond!

Basically the situation is
1. When I activate a tool, for example rectangleRoi to mouse button 1, I need to deactivate all other tools first to make sure mouse button 1 only does 1 thing
2. freehand is one of the tool that I deactivate and the one causes issue
3. Deactivating other tools like zoom, wwwc, pan does not prevent activating another tool (like rectangleRoi) later
4. Deactivating freehand, however, will cause the issue that other tools won't activate

for example 
calling `cornerstoneTools.rectangleRoi.activate(element, 1)`
after `cornerstoneTools.freehand.deactivate(element)'
does not activate rectangleRoi tool

Please let me know if there is any other information or testings I can do to provide a clearer case description.

**Comment by JamesAPetts** [comment]
Hmm, this is strange, this is working on master on examples/allImageTools, which does just this:

`function disableAllTools()
        {
            cornerstoneTools.wwwc.disable(element);
            cornerstoneTools.pan.activate(element, 2); // 2 is middle mouse button
            cornerstoneTools.zoom.activate(element, 4); // 4 is right mouse button
            cornerstoneTools.probe.deactivate(element, 1);
            cornerstoneTools.length.deactivate(element, 1);
            cornerstoneTools.ellipticalRoi.deactivate(element, 1);
            cornerstoneTools.rectangleRoi.deactivate(element, 1);
            cornerstoneTools.angle.deactivate(element, 1);
            cornerstoneTools.highlight.deactivate(element, 1);
            cornerstoneTools.freehand.deactivate(element, 1);
            cornerstoneTools.eraser.deactivate(element, 1);
        }

        document.getElementById('rectangleroi').addEventListener('click', function() {
            activate('rectangleroi')
            disableAllTools();
            cornerstoneTools.rectangleRoi.activate(element, 1);
        });

        document.getElementById('freehand').addEventListener('click', function() {
            activate('freehand')
            disableAllTools();
            cornerstoneTools.freehand.activate(element, 1);
        });
`

**Comment by JamesAPetts** [comment]
Oh, could it be that you aren't passing the mask:

cornerstoneTools.freehand.deactivate(element, 1)

**Comment by caoool** [comment]
Thanks, I will test passing mask and post back soon!

**Comment by caoool** [comment]
OMG, it worked.
My bad that I didn't read carefully.
Thank you very much!
