### ISSUE TITLE
The scroll indicator does not work in 2.3.8

### ISSUE THREAD

**Issue by Saucistophe** [cornerstonejs/cornerstoneTools#454]
### Description

I just updated to version 2.3.8, and the scroll indicator does not show where it did.
It also stopped working on the live examples (https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackScroll/index.html) where it worked just yesterday.

### Steps to Reproduce

Enable the stack scroll indicator with cornerstoneTools.scrollIndicator.enable(element);
The bottom bar indicator should show up, it doesn't.

**Comment by timleslie** [comment]
This is a bug in the changes I made in: https://github.com/cornerstonejs/cornerstoneTools/commit/18d9d2438f24d69122e2b5e52c46b9dac6a28af2?

```
        heigh: scrollBarHeight
```

should be 
```
        height: scrollBarHeight
```

at 

https://github.com/cornerstonejs/cornerstoneTools/blob/18d9d2438f24d69122e2b5e52c46b9dac6a28af2/src/stackTools/scrollIndicator.js#L76

Let me quickly put together a PR to fix this. Thanks for the bug report!

**Comment by Saucistophe** [comment]
Thank _you_ for such a quick reply :)

**Comment by timleslie** [comment]
#455 Fixes this. Apologies for the breakage! Ping @swederik.
