### ISSUE TITLE
Allow an easy enabling/disabling of synchronizers

### ISSUE THREAD

**Issue by Saucistophe** [cornerstonejs/cornerstoneTools#464]
### Description

According to the demo, and having had a look at the code, I think there is no easy way to disable a Synchronizer without manually removing viewers.
In my case, I handle viewers on the go, removing them, adding them to the view, etc. The trouble is we have a "Synchronize" button that toggles the synchronization between viewers.
Instead of removing all viewers and adding them all back, and registering new viewer only if the Synchronized mode is active, it would be way easier to add them systematically to the synchronizers and toggling their status from disabled to enabled:

`panZoomSynchronizer.enabled = false;`

If you think that's a valid idea and/or that there are no alternative, I'd be happy to submit a PR.

**Comment by dannyrb** [comment]
The solution for this was merged, so I will close the issue.
