### ISSUE TITLE
How to modify the mouse event in stackScroll/stackScrollWheel  

### ISSUE THREAD

**Issue by Honey-hoo** [cornerstonejs/cornerstoneTools#478]
How to choose to trigger rolling instead of triggering mouseEnter?
I want to click one image series then use ` stackScroll/stackScrollWheel `, and I do not expect the mouse hover to trigger the rolling ;

**Comment by swederik** [comment]
I do not understand the question. What are you trying to do?

stackScroll uses mouse drag to scroll the stack of images
stackScrollWheel uses the mouse wheel to scroll the stack of images

If you don't want mouse drag to change images, just don't enable that tool.

**Comment by dannyrb** [comment]
@Honey-hoo, please feel free to provide clarification if your problem was not resolved, and then we can reopen this issue.
