### ISSUE TITLE
List of small chores for near end of v3 dev.

### ISSUE THREAD

**Issue by JamesAPetts** [cornerstonejs/cornerstoneTools#483]
Here is an ongoing list of small improvements which will be easier to implement once we are all done with our feature branches.

- [x] Capitalize all classes as per JS convention.
- [x] Rename mouseToolEventDispatcher.isAwaitingMouseUp something more appropriate. (isAwaitingToolUse?).
- [x] isValidTarget should probably take evt rather than eventData?
- [x] baseAnnotationTool.onImageRendered -> baseAnnotationTool.renderToolData.
- [ ] methods and variables that interact with the `enabledElement` should be named/labeled `enabledElement` consistently in place of the shorter `element`

Please feel free to comment and I'll add them to the list.

**Comment by JamesAPetts** [comment]
I'll do this at the review stage once all tools are in.

**Comment by dannyrb** [comment]
@JamesAPetts for capitalize all classes, how strict do you want to be? The only built-in linting rule I can find is [new-cap](https://eslint.org/docs/rules/new-cap) which @swederik commented out at some point?

But that would not cover:

- Class file names
- When importing a class to use it as a base for another class

I agree with your `isValidTarget` comment. In general, I think everything can be a bit more flexible if we pass the whole event rather than just the `eventData`

**Comment by JamesAPetts** [comment]
@dannyrb, I agree anything that can be instantiated via New should be capitalized. As far as file naming goes, I think we need to discuss and go by consensus of the team. In my opinion any file that exports only one class definition should have its filename capitalized. This makes sense when you consider export default, e.g.:

MyClass.js:

```
export default class {
  // Blah
}
```

someJsFile.js:

```
import MyClass from './MyClass.js';
```
I see this style a lot in React apps etc. @swederik is also using this pattern in the OHIF Viewer (see e.g. Packages/ohif-cornerstone-settings/imports/client/lib/classes/MetadataProvider.js.

In general, I think it would be beneficial to host a meeting a little further down the line to come to consensus on all api and styling issues?

**Comment by swederik** [comment]
I agree with @JamesAPetts. If the eslint rule was commented out, it was probably because I was too lazy to fix the warnings at the time.

**Comment by JamesAPetts** [comment]
I'm going to close this for now. We have a much more developed list of issues on the vNext board.
