### ISSUE TITLE
Allow for custom event handlers to be called for each event instead of the default assumed in mouseToolEventDispatcher.

### ISSUE THREAD

**Issue by JamesAPetts** [cornerstonejs/cornerstoneTools#484]
So that complex tools may override behavior.

**Comment by dannyrb** [comment]
@JamesAPetts what does your imagined implementation of this look like? Most of the dispatcher methods are, more or less:

- Filter tools by `mode` (and sometimes `data`) to find viable tools
- Of the viable tools, determine which tool is the best candidate
- Either apply a method we expect to see on the tool, or handle the event in a consistent way for all tools (ie. mouse down either moving "a handle" or "all handles")

We could...

- Allow an alternate way, per tool, to determine if the tool is viable
    - Instead of using `pointNearTool`, use a more generic method if it exists on the tool
    - Instead of using `proximityToTool`, use a more generic "ranking" method
- Allow tools to expose a more generic method that supersedes the default applied behavior in instances where there is a default behavior
- Create a 4th step at the end of each method that is a callback/hook for tools to use
    - Similar to the `setToolMode` methods

There are probably other options I'm missing. I think the above would be clearer if we cleaned up some of the `dispatcher` methods as well.

**Comment by dannyrb** [comment]
I think we've knocked this out in recent PRs. Nearly every event should have some kind of callback implemented at this point, and override behavior for handle/pointNearTool events
