### ISSUE TITLE
Cancel mouse-tool-interaction when getting deactivated

### ISSUE THREAD

**Issue by freund17** [cornerstonejs/cornerstoneTools#505]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Say, for example, I activated the WWWC-tool for the left mouse-button:
```JavaScript
cornerstone.tools.wwwc.activate(element, 1)
```

I start dragging the mouse... (Everything working as expected.)
Now, *while I am still dragging*, I deactivate the tool. (For example due to another event.)

```JavaScript
cornerstone.tools.wwwc.deactivate(element)
```

Even though the tool is now disabled, I am still able to use it as long as I am still holding the mouse-button pressed.

### Steps to Reproduce

1. Activate a mouse-dragging based tool
2. Start using it (hold assigned mouse-button)
3. Deactivate tool
4. Continue using the tool despite being deactivated

**Expected behavior:**

Tool stops to function as soon as it gets deactivated.
(Exactly the way touch-drag-based tools currently do.)

**Actual behavior:**

Tool continues to function as normal until a mouse-button is lifted.

### Codepen With Reproduction of Issue:

https://codepen.io/anon/pen/ejVeGK

After clicking the button, the wwwc tool is activated and again deactivated after 1 sec.

### Solution

After inspecting the code, the problem is quite obvious and probably easy to fix:
`src/imageTools/simpleMouseButtonTool.js` only receives a `mouseDownCallback`. Additionally some kind of `deactivatedCallback` is needed, to signal the implementing tools (for example `src/imageTools/wwwc.js`), that they need to unbind their `EVENTS.MOUSE_DRAG`-Listeners.

I can start a PR for this.

**Comment by freund17** [comment]
@dannyrb @swederik 
So... whats the intended strategy for this?

**Comment by dannyrb** [comment]
Sorry, @freund17. I've been a bit consumed by the changes for the upcoming major release on the `vNext` branch.

Your case is interesting. I haven't yet run into a scenario where I need to change a drag tool's state while it's in use. I appreciate the codepen, it makes it _very_ clear what is happening, and what behavior you expect.

I "think", by default, this will be addressed in `vNext` by default, because of the way the new `eventDispatchers` work. It might be worth giving it a try, as we're kicking its tires and getting ready to formally beta test it ourselves. If this is urgent for you, I think the callback your proposing is reasonable, and I'd be willing to look at a PR for it.

@swederik may have additional thoughts.

**Comment by freund17** [comment]
Thanks for the reply.
As it is not very urgent, I think I can wait for vNext to land...
Is there something like a migration manual somewhere?
I tried to update the codepen to check whether the issue would get fixed, but I couldn't get the tool to work...
I dove in the code a bit and found that the tools are now classes. But they lack some kind of `activate`-Method.
I expect there to be some `addTool`-function for enabled elements, but I couldn't find that either...
Am I blind?

**Comment by dannyrb** [comment]
@freund17 on my list to `fork` your codepen with a working example today. I'll see what I can do 🙌

**Comment by dannyrb** [comment]
@freund17: https://codepen.io/dannyrb/pen/pZBQOP?editors=0010

It appears to work. The `@next`/vNext is still very unstable. We're doing an "internal beta" shortly with a number of our primary contributing teams; after we work out a few more kinks, you'll begin to see more formal documentation and a migration guide. It's still a little too early for us to actively encourage adoption/migration.

**Comment by dannyrb** [comment]
@fruend17, I'm making this as closed. If you find that the demo I provided does not work as expected (or that the finalized version of vNext does not), please feel free to re-open this issue.

If you would like to Beta test vNext and provide feedback as well continue to shape and ultimately publish is, please feel free to send an email to danny.ri.brown@gmail.com, and I will add you to contributor Slack group.
