### ISSUE TITLE
How to get coordinates of rectangle roi

### ISSUE THREAD

**Issue by vdemario** [cornerstonejs/cornerstoneTools#507]
This is a question instead of a real issue, I apologize if this isn't the right place.

I'd like to get the (x,y) coordinates of the points that define a rectangle roi drawn by the user. At first I won't do anything specific with it, just submit it to the backend for persisting in a database.

I've searched through the wiki, the website and the source code of the examples but I can't figure out how to get those values on my js code.

Enabling and using the tool is very straightforward, which is great. I'd appreciate help for the extraction of the values.

**Comment by therladbsgh** [comment]
You can fetch the points through [getToolState(element, "rectangleRoi").](https://github.com/cornerstonejs/cornerstoneTools/wiki/DataManagement)

[Here's an example where I call the function when the image is rendered.](https://codesandbox.io/s/912rrrqpq4)

**Comment by vdemario** [comment]
Thank you very much @therladbsgh, it worked perfectly.
