### ISSUE TITLE
Provide option to disable brush tool's imageLayer-Copying

### ISSUE THREAD

**Issue by the-kenny** [cornerstonejs/cornerstoneTools#515]
`cornerstoneTools.brush` started copying image shown at the time of activation to a separate layer that's entirely managed by `brush` in bbc329198ac81a5fff618b13e6cffacea2527229 ([relevant lines](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/paintingTools/brushTool.js#L268-L271))

This leads to issues with stacks where activating the `brush` tool and then switching to other images in the stack still showing the image from when the tool was activated. There's no option to disable this behavior, nor is there a way to get the added layer's id to manually clean up.

I think the brush tool should a) clean up after itself in `deactivate()` and b) have an option to disable this behavior.

### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

**Comment by the-kenny** [comment]
@dannyrb Thanks! Looking forward to it :-)

**Comment by dannyrb** [comment]
@JamesAPetts is this issue resolved in the `vNext` branches implementation?

**Comment by JamesAPetts** [comment]
We no longer use the layer api in vNext, I simply convert the data to a bitmap and render it straight to the canvas, so this shouldn't be an issuee.

**Comment by dannyrb** [comment]
@the-kenny, it's still a little rough, but the `vNext` branch will eventually become `v3` of `cornerstoneTools` when it's merged into `master`. It may be worth trying out it's `brush tool` implementation to see if it works as you would expect.

I'll close this issue for now. Feel free to continue to discuss, or to open a new issue for anything related to the new brush tool implementation.

**Comment by the-kenny** [comment]
Thanks for the explanation! I’ll have a look at the vNext branch. 

Cheers
