### ISSUE TITLE
stackPrefetch stops when selecting different element

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneTools#529]
Hi, I have two divs. I assign a stack to each and do a `cornerstoneTools.stackPrefetch.enable(elem1);` to start prefetching the 1nst div. Then, I do the same on the 2nd div (I call it elem2). The problem I found is the prefetching of the first element stops when the 2nd element is enabled.

Is this the expected behavior of stackPrefetch?.

**Comment by fcortes** [comment]
From what I understand it shouldn't stop the prefetching of the first element. From looking at the source, the prefetching is actually done by the `requestPoolManager` which after adding a new cornerstone imageId should only add new elements to the `requestPool`.

There is actually a parameter on the `addRequest` (addToBeginning) to specify if the new elements should have priority before the current elements but it is not being used in the [stackPrefetch ](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/stackTools/stackPrefetch.js#L176), so it should default to false, though I haven't tested it. You can test if this is actually the case by adding a console.log(requestPool) at the end of the addRequest method [here](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/requestPool/requestPoolManager.js#L65).

Maybe you could try to write a small working example of this on a codepen to better understand the issue.

**Comment by leonardorame** [comment]
Thanks  @fcortes, after doing what you recommended I found that aparently the requestPool is replaced by a new one when I call `cornerstoneTools.stackPrefetch(elem2);`.

I don't have a minimal example to show this here, but what I basically do is this:

```
var openImage = function(imageId) {
    cornerstone.loadAndCacheImage(imageId).then {
        function(image) {
            // -- get the element based on imageId and viewport...
            cornerstone.displayImage(element, image, viewport);
            cornerstoneTools.stackPrefetch(element);
        }
    }
};
```

**Comment by Saucistophe** [comment]
We've add the same problem and solved it by tweaking the stack prefetch:
- Prevent the poolManager clearing for prefetches, so that it does not forget what it's doing.
- Insert the images at the beginning, but from last to first. This way, it's added to the top with the greatest priority, but does load in the intended order.

We've tested it with two side-by-side viewer and it worked like a charm: each time we interact with a viewer, the other one stops loading and the current one resumes loading, even if the current image changes. When it's over, the remaining one loads. Really neat!

I'm working on a PR to handle it with a configuration parameter.

**Comment by swederik** [comment]
Looks like we can close this since #542 was merged.

**Comment by mikehazell** [comment]
What happened to this change? Unless I've lost my mind, the changes are no-longer in master and no-longer appear in the history of that file.

Master now:
https://github.com/cornerstonejs/cornerstoneTools/blob/82e0e988043bf6d4bb69ace48e9882d5e069bce1/src/stackTools/stackPrefetch.js#L13-L15

PR marked as merged:
https://github.com/cornerstonejs/cornerstoneTools/pull/542/files#diff-b5e5d95181782e7ebf78d4fd7591a55a

**Comment by Saucistophe** [comment]
Indeed.

**Comment by dannyrb** [comment]
@mikehazell this may have been lost when we bumped from v2 to v3. A lot of the merging was by hand, and there were a decent number of changes. It's possible this one slipped by. Feel free to create a new issue if this needs to be addressed.
