### ISSUE TITLE
How to handle passive mouse events whilst using the brushTool

### ISSUE THREAD

**Issue by JamesAPetts** [cornerstonejs/cornerstoneTools#540]
Lets get the Needs Discussion board to use:

There are two avenues I can see to handle passive mouse events whilst using the brushTool, both don't sound ideal:

- Completely ignore the passive status of all other tools.
- Make painting potentially more fiddly on a densely annotated image.

I'm leaning towards the first option, as I can see it being really annoying to paint near/under other annotations.

Any thoughts @cornerstonejs/vnext-contributors ?

^How we should tag people, @galelis (and perhaps others) need to join the team.

**Comment by dannyrb** [comment]
> Completely ignore the passive status of all other tools.

Would be my vote as well. Now that we have a `baseBrushTool`, maybe we even go one step further and say that when a `brushTool` is your "primary active" (left mouse button mask, or touch), that we don't highlight the tools w/ `pointNearTool` or `nearbyHandle`

**Comment by diego0020** [comment]
Maybe we should have a mechanism for disabling the highlighting; and at application level turn off highlighting for the other tools.

**Comment by dannyrb** [comment]
@cornerstonejs/vnext-contributors
-- Is how you would tag the relevant users, @JamesAPetts

**Comment by JamesAPetts** [comment]
@diego0020 @dannyrb: Concerning an API fro disabling highlighting, wouldn't simply turning all other `passive` tools to `enabled` be equivalent and cleaner?

**Comment by dannyrb** [comment]
The advantage of a setting is that you can more easily "restore" the mode of all tools. If you set them all to enabled (And half were already enabled) it would be hard to know which ones to restore to passive when using a tool other than brush.

**Comment by JamesAPetts** [comment]
Right, that's a good point. I guess we could just have a new module in the store for highlighting, and this can be checked by all the tools' `renderTool` functions.

**Comment by dannyrb** [comment]
Most tools "highlights" based on a property we set in `move`, `down`, or `start` events. It may require less of a re factor to handle the logic in the dispatchers.

It fits nicely with the changes we have slated for new tool bools:

- isHovered
- isSelected

**Comment by JamesAPetts** [comment]
Fixed some PR's ago! :).
