### ISSUE TITLE
Mean, stddev, area calculation not updated during modification of RectangleROI and EllipseROI tool

### ISSUE THREAD

**Issue by atisman89** [cornerstonejs/cornerstoneTools#546]
Not sure if this is a feature or bug, but I noticed a difference in the behavior of a newer version of Cornerstone tool. The mean, stddev, area value in the tool text box is not being updated during modification of RectangleROI and EllipseROI tool (by mouse dragging). Was this change made intentionally in a newer version? Then, is there any way to make the values be updated during the tool modification? BTW, the "length" tool is still updating the length value during the modification. Thank you for your input in advance!

**Comment by dannyrb** [comment]
Is there a specific version you are using? Does the value not update at all? Does it update when you've finished resizing or placing the annotation? Does it update as you drag?

**Comment by atisman89** [comment]
It does not update as I drag but updates only when I finish dragging. I verified that this behavior is same in the demo example.

**Comment by dannyrb** [comment]
It may have been removed because the calculation was a bit much for large images and to fire for each drag event.

I'm not sure there's much value in the seeing updates on drag, as you're usually selection a visual region and not a specific amount of space. (Please correct me if I'm wrong.)

@swederik may know if the change was on purpose or if its a bug.

**Comment by atisman89** [comment]
Thank you for your quick response. If this change was on purpose, I figured out that setting the tool data's "invalidated" property to "true" for each "cornerstonetoolsmeasurementmodified" event would override the change and update the stats while dragging handle / resizing the tools. I'm not sure if this is a proper way though and recommend to provide this option as a configurable item for those tools. Thanks.
