### ISSUE TITLE
Can I clear each length by mouse right click after use length tool?

### ISSUE THREAD

**Issue by ofleaf** [cornerstonejs/cornerstoneTools#560]
I refer to the clearToolData example, I try to clear the tool data.

`document.getElementById('clearLengthData').addEventListener('click', function() {`
`cornerstoneTools.clearToolState(element, "length");`
`cornerstone.updateImage(element);`
`});`

When I used multiple length tools, I want clear each length by right click.
Should I change some code in cornerstoneTools?

**Comment by FMCalisto** [comment]
To clear the data for each length tool individually by right-clicking, you can add a listener for the right-click event on the element where the length tools are being used. Then, use the `clearToolState` function to clear the state for the specific tool and measurement data.

Here is an example of how to do this for the length tool:

```JavaScript
// add right-click event listener to the element where the length tool is being used
element.addEventListener('cornerstonetoolsmousedown', function (evt) {
  if (evt.detail.event.which === 3) { // check if right mouse button is clicked
    var toolStateManager = cornerstoneTools.getToolStateManager(element);
    var data = toolStateManager.get(element, 'length');
    if (data && data.data && data.data.length > 0) { // check if there is measurement data for length tool
      var measurementData = data.data[data.data.length - 1];
      cornerstoneTools.clearToolState(element, 'length', measurementData);
      cornerstone.updateImage(element);
    }
  }
});
```

This code listens for the `cornerstonetoolsmousedown` event on the element, which is triggered when a mouse button is pressed down while a tool is active. The code checks if the right mouse button is clicked and if there is measurement data for the length tool. If both conditions are met, it uses `clearToolState` function to clear the tool state for the specific measurement data and then updates the image.

You can use this code in response to a right-click event to clear the length tool state for that specific measurement:

https://stackoverflow.com/a/73204850/2371987
