### ISSUE TITLE
How to painting sagittal、coronal、transversal slices for dicom of js,I look up the doc but  I  am not seek out a way,Please help me ~

### ISSUE THREAD

**Issue by lalalawututu** [cornerstonejs/cornerstoneTools#567]
### Prerequisites

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Codepen With Reproduction of Issue:

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by dannyrb** [comment]
I believe what you're asking about is support for MPR

> Multi Planar Reconstruction (MPR) generates new "slices" based on the series of axial slices acquired by a CT or MR from any given direction.

Related Issues:
- https://github.com/cornerstonejs/cornerstoneTools/issues/335
- https://github.com/cornerstonejs/cornerstone/issues/189

We do not yet support this functionality. There has been some talk about how to accomplish it. Different groups have created working concepts for both 2D and 3D MPR in Cornerstone, but I believe all existing source is proprietary/closed.

You might have some luck reaching out to [Radical Imaging](http://radicalimaging.com/) for paid services to develop the functionality you need. They're the only consultancy I'm aware of that works heavily with Cornerstone.

**Comment by lalalawututu** [comment]
@dannyrb 
I think the connerStone have its own api. if I use Multi Planar Reconstruction (MPR),can I combined utilization with the connerstone ?

**Comment by dannyrb** [comment]
@lalalawututu if you're accomplishing MPR with a 3rd party library, you'll likely need to create a custom "Image Loader" to create/load the images into Cornerstone.

**Comment by yiuyiu** [comment]
@dannyrb hello, i found  **ami.js** can do the mpr, but its source is quite difficult for me to read, so i want to accomplish by myself. could you give me some advice or refs to do this. i have read the related issues. but i can not find the concrete algorithms o(╥﹏╥)o

**Comment by dannyrb** [comment]
@yiuyiu, @swederik may have some code lying around. I know he's played with [ami.js](https://github.com/FNNDSC/ami) as well as [vtk.js](https://github.com/kitware/vtk-js) and [xtk.js](https://github.com/xtk/X). The challenging part is using the generated images in/with Cornerstone and Cornerstone Tools. If you hatch an elegant solution, I'm sure many people would be interested to hear and see more on this topic.
