### ISSUE TITLE
I want to know, for example, src, how does length.js know that it has finished drawing this line?Thank you

### ISSUE THREAD

**Issue by jkkjinagke** [cornerstonejs/cornerstoneTools#578]

**Comment by jkkjinagke** [comment]
@dannyrb hello dannyrb, First of all, I said that I really like the frame you wrote.I want to know, for example, src, how does length.js know that it has finished drawing this line?Thank you

**Comment by dannyrb** [comment]
@jkkjinagke, are you asking how the tool itself knows that an annotation has been completed (the internal mechanics)? Or are you asking how to receive updates every time an annotation is placed, moved, resized, or removed?

**Comment by jkkjinagke** [comment]
@dannyrb I hope that I can have an introduced api that will allow me to do the functions I need, and then disturb again. Why do undefined% occur when loading the progress bar?

**Comment by dannyrb** [comment]
@jkkjinagke, can you add a code sample that reproduces the issue?

**Comment by jkkjinagke** [comment]
@dannyrb  cornerstone.events.addEventListener("cornerstoneimageloadprogress",function(event){
            console.log(event);
            const eventData = event.detail;
            console.log(`${eventData.percentComplete}%`);
        });   eventData.percentComplete == undefined;

**Comment by jkkjinagke** [comment]
@dannyrb hello dannyrb  ! Why can I load localComplete when I read local, and the cloud will not work? Undefined? Is it a dcm problem?

**Comment by dannyrb** [comment]
@jkkjinagke, I believe we may be up against a bit of a language barrier. I'm unable to fully understand what you're asking. However, I may still be able to help if you provide a full example that demonstrates the error you're encountering. Tools that can help you provide an example are:

- [Codepen](https://codepen.io/pen/)
- [JS Fiddle](https://jsfiddle.net/)
- Or a link to a GitHub repository that includes _ONLY_ the minimum amount of code needed to reproduce the example

**Comment by jkkjinagke** [comment]
@dannyrb The dcm file eventData.percentComplete opened locally can display the percentage, but when I take the dcm file from the cloud, it will display undefined%. I want to ask what is the reason?

**Comment by jkkjinagke** [comment]
@dannyrb hello dannyrb 。I recently got a new feature and it has been completed. I think it is possible to save the current event base64 by converting it to a file type format and storing it in a computer class so that you can get the uploaded image. If you need the code, I can provide it to you. , very small features, hehe. The problem provided by the upload has been resolved, the percentage is not displayed on Google, but it can be on Firefox, and finally the response to the cancellation of loading, and finally, under the expression, I like your open source JS

**Comment by dannyrb** [comment]
> The problem provided by the upload has been resolved, the percentage is not displayed on Google, but it can be on Firefox, and finally the response to the cancellation of loading, and finally, under the expression, I like your open source JS

I think this is resolved? 

If the issue is not resolved, please feel free to continue commenting. Please include a minimal reproduction for any issues you do have, as I believe we have a slight language barrier.

**Comment by jkkjinagke** [comment]
@dannyrb Can you help me see why I can't open this dcm? 
[test.zip](https://github.com/cornerstonejs/cornerstoneTools/files/2517349/test.zip)    This is the dcm resource map, thank you
