### ISSUE TITLE
Issue when we mix Rotate with BrushTool, EllipseRoiTool and RectangleRoiTool.

### ISSUE THREAD

**Issue by JamesAPetts** [cornerstonejs/cornerstoneTools#579]
Steps to reproduce:
- Open global example
- Paint with the brush, draw a circlular ROI and an rectangluar ROI.
- Select Rotate tool and rotate the image something like 45 degrees. All three tools are distorted.
-  Select Brush and try to use the tool. It will paint in the wrong place.
- New Rectangles and ellipses can be drawn 'correctly' with the tilted angle, but when you rotate the image back, you don't get back what you intended to mark up.

For strict 90 degree rotations, the rectangle and circle stay intact. This is because the geometry is based off two control points, which reference a certain pixel, and are safe to rotation. Tools like angle, length, freehand and probe that only draw straight lines between control points are safe to rotation.

The brush renders incorrectly even with 90 degree rotations (try drawing around an object in the demo), and you cannot draw in the correct place. It seems to do some strange image flip, if you compare a rotate of a circular brush to an overlayed circular roi tool.

Thanks @galelis

**Comment by JamesAPetts** [comment]
Ok after some further deliberation with @swederik, I've come to the conclusion that the issues with the brush and the rois is identical, just the brush segmentation isn't rotationally symmetric within its control points.

Let me demonstrate, I've drawn 4 'segmentations' that fill up the canvas, as well as a rect and circle:
<img width="628" alt="screen shot 2018-09-20 at 11 10 54" src="https://user-images.githubusercontent.com/25818497/45811852-1f54d580-bcc6-11e8-9f3d-e76d08b90a6a.png">

Then rotating ~30 degrees clockwise, the image gets skewed:
<img width="792" alt="screen shot 2018-09-20 at 11 11 38" src="https://user-images.githubusercontent.com/25818497/45811858-2380f300-bcc6-11e8-9c99-ea3fc09d4f1a.png">
It dissapears at exactly 45 degrees, at around 60 degrees the control points have flipped sides, and the image is rendered within those control points to the canvas:
<img width="784" alt="screen shot 2018-09-20 at 11 12 00" src="https://user-images.githubusercontent.com/25818497/45811861-25e34d00-bcc6-11e8-9fc0-c473dff14aef.png">
At 90 degrees the circle and rectangle look as expected after a rotation, because they are rotationally symmetric. The brush tool isn't flipped as its control nodes are rotated, then the image is rendered within these nodes, so it looks the same as it did unrotated.
<img width="619" alt="screen shot 2018-09-20 at 11 12 11" src="https://user-images.githubusercontent.com/25818497/45811864-2845a700-bcc6-11e8-986f-4895ffbdfeb9.png">

What is really needed is a rotation of the entire canvas. I'm going to play with transform of the tools in image rendered, but I feel this is a more fundamental issue. Tagging @chafey , as @swederik  said you were the author of the rotation stuff in cornerstone core, do you have any insight into how we could fix this issue globally?

Thanks,
J

**Comment by JamesAPetts** [comment]
Just confirming I'm now working on this.

**Comment by JamesAPetts** [comment]
This is fixed for the brush layer for arbitrary rotations + h/v flips in #755.

The issues with the elliptical and rectangular ROI tools remain for now.

**Comment by JamesAPetts** [comment]
Thanks @daniel2101 for fixing the rectangles and ellipses in #916 ! :)

**Comment by prateekghosh** [comment]
Hey can you please help me out of removing the brush tool data from the canvas I didn't find solution for that.
