### ISSUE TITLE
Angle tool rounding issues

### ISSUE THREAD

**Issue by knopkem** [cornerstonejs/cornerstoneTools#580]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

When moving the angle tool entirely, the measured angle changes (~1deg)

### Steps to Reproduce

1. Open the example "allImageTools"
2. Select angle tool and draw any angle
3. Move the tool (dragging a line not a handle)

**Expected behavior:** [What you expected to happen]

The angle shown does not change

**Actual behavior:** [What actually happened]

The angle changes

### Codepen With Reproduction of Issue:

The issue seems to come from rounding (Math.ceil) of the current handle position.

See Ln 100-103 in:
https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/angleTool.js

Removing the Math.ceil fixes the issue.

**Comment by dannyrb** [comment]
This makes sense. If you change the position and the coordinates overall rounding moves the measurements a greater difference, you could see a shift.

@knopkem, Would you be up to PR'ing this change? Ideally against the `vNext` branch so we don't need to remember to port it over.

**Comment by knopkem** [comment]
sure, will do.
