### ISSUE TITLE
Problem when using cornerstoneTools and cornerstone as a module in a node.js project

### ISSUE THREAD

**Issue by vsaase** [cornerstonejs/cornerstoneTools#584]
https://github.com/cornerstonejs/cornerstoneTools/blob/1f7d41d15c795dc99f8e395713cf9d63094f49b0/src/externalModules.js#L1

Hey, I am encountering some problems here when loading cornerstone and cornerstoneTools as a module with `require` or `import`. Then `window.cornerstone` is not available to cornerstoneTools.

**Comment by vsaase** [comment]
`window.Hammer` is working, but `window.cornerstone` not. Maybe something with how webpack creates the module file for cornerstone?
 
Thats how I import:
```
import * as Hammer from 'hammerjs';
import * as cornerstone from 'cornerstone-core/dist/cornerstone.js';
import * as cornerstoneMath from 'cornerstone-math/dist/cornerstoneMath.js';
import * as cornerstoneTools from 'cornerstone-tools/dist/cornerstoneTools.js';
import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader.js';

cornerstoneTools.external.Hammer = Hammer;
cornerstoneTools.external.cornerstone = cornerstone;
cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
```

PS: I am trying to make this work for an Ionic app, this is also inside another module
Everything else works just fine.

**Comment by dannyrb** [comment]
@vsaase to @JamesAPetts's point, just make sure you're depending on an _exact_ version, and not loosely in your NPM dependencies. We'll cut a more stable release before too long, but until then, every new release has a chance to introduce a breaking change.

That being said, feedback on what is and is not working for the latest build is always appreciated ^_^

**Comment by galelis** [comment]
@vsaase Hey Victor,
Would you mind to provide me any error log with errors or any other information that could help me to understand your issue? 

I have the @vnext version set up with OHIF Standalone viewer and everything is working fine there as well.  

Ideally, I added that line to prevent the code from breaking in case cornerstone is not present into external (and window)

**Comment by vsaase** [comment]
So I import cornerstone like this:
```
import * as Hammer from 'hammerjs';
import * as cornerstone from 'cornerstone-core/dist/cornerstone.js';
import * as cornerstoneMath from 'cornerstone-math/dist/cornerstoneMath.js';
import * as cornerstoneTools from 'cornerstone-tools/dist/cornerstoneTools.js';
import * as dicomParser from 'dicom-parser/dist/dicomParser.js';

cornerstoneTools.external.Hammer = Hammer;
cornerstoneTools.external.cornerstone = cornerstone;
cornerstoneTools.external.cornerstoneMath = cornerstoneMath;
```

When activating the brush and the image redraws, I get an error in `onImageRenderedBrushEventHandler` because `getNumberOfColors()` of the BrushColorMap returns 0 and therefore toolData.data is empty.

The reason for this is that BrushColorMap is not initialized because cornerstone was not available. When putting a debugger command in store/brushStore.js I see that it is executed at the time I import cornerstoneTools. Here `external.cornerstone == undefined` because `window.cornerstone == undefined`. 
So before I have the chance to set `cornerstoneTools.external.cornerstone = cornerstone;` the cornerstoneTools module must be able to find the cornerstone instance. 
For some reason beyond my knowledge of javascript modules `window.Hammer` is not undefined at the time of importing cornerstoneTools, even though I import Hammer the same way as I import cornerstone.

**Comment by dannyrb** [comment]
I think because you're using modules, the libraries aren't added to window. I have a similar setup, and `window.cornerstone` is undefined, yet everything works as expected. If you have or can create a very minimal repo that reproduces this error, I would be more than happy to get a fix in as early as next week.

Similarly, if you can create a small PR that fixes your issue without causing a breaking change, I would be more than happy to take a look at it, offer feedback, and merge.

**Comment by JamesAPetts** [comment]
Hey @vsaase , after some discussion with @swederik, we've come to the conclusion we just need to generate the brush map during init. In vNext @dannyrb and I are working on initializing modules on instantiation of cornerstoneTools, which is when we should generate the map. In this case cornerstone will have be defined, and the issues you are having in node.js will be fixed.

For that reason I'm reluctant to pull your PR (#591), as the issue will naturally be resolved in the near future, before v3 release. 

I would like to thank you greatly for your hard work on this issue, as you highlighted and demonstrated the flaws in the current setup. :+1:.
