### ISSUE TITLE
bug(?) in playClip()

### ISSUE THREAD

**Issue by fourctv** [cornerstonejs/cornerstoneTools#620]
### Prerequisites

* [y ] Are you running the latest version?
* [y ] Are you reporting to the correct repository?
* [y ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

There seems to be an error in playClip(), where it calls `loadImage()` and `loadAndCacheImage()`.
Those functions take an `imageId`, but `playClip` is calling them using an `imageData` object, not its **imageId** attribute.

I replaced the code in my built copy with the following, and now `playClip()` works as expected:

```
      if (stackData.preventCache === true) {
        loader = cornerstone.loadImage(stackData.imageIds[newImageIdIndex].imageId);
      } else {
        loader = cornerstone.loadAndCacheImage(stackData.imageIds[newImageIdIndex].imageId);
      }
```

I'm using **cornerstoneTools v2.3.9**. I checked **vNext** and the bug seems to be there as well.

**Comment by swederik** [comment]
Yeah that does sound like an issue... Thanks for the report!

**Comment by fourctv** [comment]
Actually that is not a cornerstoneTools bug, but MY bug (of course).

I populated `stack.imageIds` incorrectly, with image data, instead of `imageIds`.

I fixed it on my side and it works as expected.

Sorry to take your time on this.

Closing it.
