### ISSUE TITLE
Angle tool show NaN degree.

### ISSUE THREAD

**Issue by Anduil** [cornerstonejs/cornerstoneTools#629]
### Prerequisites

* [Yes] Are you running the latest version?
* [Yes] Are you reporting to the correct repository?
* [Yes] Did you perform a cursory search?

### Description

Angular CLI: 6.1.5
Node: 8.11.4
OS: win32 x64
Angular: 6.1.9

When i use angle tool it show NaN instead correct number degree.
All other tools work correctly. Also i tried install version 2.2.0 of cornerstoneTools and this error also have been.

### Steps to Reproduce

1. Just add the angle on image.

**Expected behavior:**

Expected correct degree.

**Actual behavior:** 

I got NaN value.

### Repo With Reproduction of Issue:

[Repository on GitHub](https://github.com/Anduil/cornerstonetools-nanangle)
In this repository exist only one example component with minimal functionality. Look inside.
[Short link on it component](https://github.com/Anduil/cornerstonetools-nanangle/blob/master/src/app/components/example/example.component.ts)

**Comment by dannyrb** [comment]
This should be fixed by this now merged PR: https://github.com/cornerstonejs/cornerstoneTools/pull/647
