### ISSUE TITLE
Highlight Touch Tool

### ISSUE THREAD

**Issue by jewettdiane** [cornerstonejs/cornerstoneTools#630]
I am getting the following error when I activate highlightTouch:
ERROR Error: element not enabled

All other tools work fine with mouse or touch and highlight works for mouse.

```
case ToolType.HighLight: {
                cornerstoneTools.highlight.enable(dicomElement);
                cornerstoneTools.highlight.activate(dicomElement, 1);
                cornerstoneTools.highlightTouch.activate(dicomElement);
                break;
            }
```

**Comment by dannyrb** [comment]
@jewettdiane can you create a small reproduction in CodePen or JSFiddle that demonstrates this error/issue?

**Comment by jewettdiane** [comment]
[Highlight Touch Error](https://codepen.io/jewettdiane/pen/XyNYLq)


enabledElements.js:163 Uncaught Error: element not enabled
    at Module.getEnabledElement (VM919 cornerstone.js:2397)
    at u (VM921 cornerstoneTools.min.js:2)
    at t.getToolState (VM921 cornerstoneTools.min.js:2)
    at Object.f [as createNewMeasurement] (VM921 cornerstoneTools.min.js:2)
    at VM921 cornerstoneTools.min.js:2
    at HTMLDivElement.t (VM921 cornerstoneTools.min.js:2)
    at t.default (VM921 cornerstoneTools.min.js:2)
    at VM921 cornerstoneTools.min.js:2

**Comment by dannyrb** [comment]
The error is being thrown in the tool's `createNewMeasurement` method. When the `MouseEvent` is passed to it, it uses `mouseEventData.event.currentTarget`. This same value is `null` when touch calls `createNewMeasurement` with `TouchEvent`

The `TouchEvent` has a `event.srcElement` and `event.target` would need to be used when creating a measurement for a `TouchEvent`

**Comment by dannyrb** [comment]
This likely will not get patched in version 2. If you want to spearhead the effort, feel free to comment, and I can re-open this issue for 6-months or until the PR is merged (whichever happens first).

Your best bet is to give version 3 a go. If this issue exists in v3, create a new issue. If the tool was removed in v3, consider creating a `3rd Party Tool` and have it listed in our 3rd Party Tool directory.
