### ISSUE TITLE
wwwc does not  work

### ISSUE THREAD

**Issue by JustinTQ** [cornerstonejs/cornerstoneTools#646]
Hi,
wwwc does not work for the following DICOM file.
[1.2.840.113619.2.255.2242445014238.2353180809103900.zip](https://github.com/cornerstonejs/cornerstoneTools/files/2494210/1.2.840.113619.2.255.2242445014238.2353180809103900.zip)

**Comment by dannyrb** [comment]
@swederik do you have availability to verify/troubleshoot this?

**Comment by JustinTQ** [comment]
Yes, the file has an empty VOI LUT(0028,3010)

**Comment by dannyrb** [comment]
@JustinTQ this does not appear to be a `cornerstone-tools` issue, and may instead be related to Cornerstone. If you're sure the DICOM file contains appropriate tags and should render differently, then we can investigate further.

Until then, I'm going to close this issue.
