### ISSUE TITLE
[v 2.3.9] Mouse button mask

### ISSUE THREAD

**Issue by tunglt1810** [cornerstonejs/cornerstoneTools#659]
Hi, can you listing a table of mouse button masks? How can I know the exact mask button to configure the active tool?

**Comment by dannyrb** [comment]
I "think" `v2` uses: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which
I know `vNext` uses: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons#Return_value

**Comment by dannyrb** [comment]
@tunglt1810, this repository is maintained mostly by volunteers; often during their free time. I tried to answer as many questions as I am reasonably able to, with the amount of time I have available. If your question wasn't fully answered, or if you have a follow-up question/need clarification, please let me know.

You're always more than welcome to check out the source code or do some minimal testing yourself. If you think information you learned would be beneficial to others, you can contribute it back to the community by updating our documentation or JSDoc comments with a pull request.

## v2.x

https://github.com/cornerstonejs/cornerstoneTools/blob/3e587198a6d1038cb3c1a240d1e6906cf2214536/src/util/isMouseButtonEnabled.js

It looks like `v2` uses `mouseEvent.which`

## vNext Branch (soon to be v3/latest)

`mouseButtonMask` for a tool is a 1:1 mapping to the `mouseEvent.buttons` property. If the browser does not support `mouseEvent.buttons`, then `mouseEvent.which` is mapped to corresponding values.

### MDN `mouseEvent.buttons`

>A number representing one or more buttons. For more than one button pressed simultaneously, the values are combined (e.g. 3 is primary + secondary).

- 0  : No button or un-initialized
- 1  : Primary button (usually left)
- 2  : Secondary button (usually right)
- 4  : Auxilary button (usually middle or mouse wheel button)
- 8  : 4th button (typically the "Browser Back" button)
- 16 : 5th button (typically the "Browser Forward" button)
