### ISSUE TITLE
[v 2.3.9] Deactivate freehand tool, but can not activate right and middle mouse button for other tools

### ISSUE THREAD

**Issue by tunglt1810** [cornerstonejs/cornerstoneTools#660]
### Prerequisites

* [v] Are you running the latest version?
* [v] Are you reporting to the correct repository?
* [v] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Deactivate freehand tool, but can not activate right and middle mouse button for other tools

### Steps to Reproduce

1. activate freehand tool
2. deactivate freehand tool
3. activate pan tool with mouseButtonMask is "2" or "4"

**Expected behavior:** Click right/middle mouse button to pan the image

**Actual behavior:** Click right/middle do not pan the image

**Comment by dannyrb** [comment]
@tunglt1810, did you experience this issue in the `v2` branch or `vNext` branch? Is it reproducible in the existing live examples?

**Comment by tunglt1810** [comment]
> @tunglt1810, did you experience this issue in the `v2` branch or `vNext` branch? Is it reproducible in the existing live examples?

I experience this issue when i try modify your example of all tool. The number of version is 2.3.9
https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/allImageTools/index.html

I just change the mouseButtonMask number (1,2,3,4,5) to test the reaction of pan tool with canvas element. Even value is not work.

**Comment by tunglt1810** [comment]
Thanks for v2.4.0

**Comment by dannyrb** [comment]
@tunglt1810, does that mean your issue has been resolved?

**Comment by dannyrb** [comment]
Closing for now. Feel free to continue the conversation if this has not been resolved.
