### ISSUE TITLE
How to make a magnifying glass display measurement data

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstoneTools#676]
### Prerequisites

* [ √] Are you running the latest version?
* [ √ ] Are you reporting to the correct repository?
* [ √] Did you perform a cursory search?

### Steps to Reproduce

1. Draw a rectangle
2. Use magnify glass tool in the rectangular position 

**Expected behavior:**
Display the corresponding image and rectangle in the range of the magnifying glass.
![image](https://user-images.githubusercontent.com/7867792/47717566-1110b680-dc81-11e8-867a-5ad0fca5fb43.png)

**Actual behavior:** 
Only image display, rectangle doesn't display.
![image](https://user-images.githubusercontent.com/7867792/47718758-24715100-dc84-11e8-85b5-b25bf4701181.png)

**Comment by dannyrb** [comment]
@hu3402379, that would be a nice enhancement, but a bit of a tricky one. I believe magnifying glass is actually displaying the image loaded onto an entirely separate canvas element to achieve a higher quality zoom. You would need to serialize and restore tool state on that ad hoc canvas for all annotation tools/data.

If you wanted to take a stab at this, I would be more than happy to review a PR. It's worth noting that this is a decently difficult problem when you start to factor in potential 3rd party tools, but might be _slightly_ easier if you can do some magic in the `baseAnnotationTool` class to get things working consistently.

**Comment by hu3402379** [comment]
@dannyrb thanks for your reply.

I found in the OHIF viewer that it has implemented this, but I did not find the implementation code in the source code.

So, if you are familiar with ohif code, can you help me point out the source code of the implementation?

Thanks a lot..

**Comment by dannyrb** [comment]
@swederik are you using the old `magnify` source in the deployed OHIF viewer, or have you hatched a custom tool that accomplishes magnifying annotations while keeping image quality?

**Comment by dannyrb** [comment]
@hu3402379, I didn't realize this at first, but if you're using the latest version of `cornerstone-tools` (version 3), you can enable canvases to automatically sync their active tools.

If you do this, when you use the magnification tool, the enabled element created by the magnification tool will activate the annotation tool and render it's data for the displayed image.

As we build out the docs for version 3, this is something that will more clearly be spelled out.

**Comment by qqsea** [comment]
@dannyrb "enable canvases to automatically sync their active tools", what does it mean? Could you provide some examples? For example, I want tho display the circle roi within magnify tool, what should I do? Thanks very much!

**Comment by ankur-originhealthai** [comment]
@hu3402379 @dannyrb What was the solution of above problem, i want a magnify tool that is fixed on top right and show zoomed window along with measurements
