### ISSUE TITLE
Use CornerStone measurements in ultra sound modality.

### ISSUE THREAD

**Issue by RutulSB** [cornerstonejs/cornerstoneTools#684]
Hello, 
I am using the latest version of cornerstone scripts. I'd like to acknowledge the work you are doing here and I must say cornerstone is a great library. It has certainly helped a lot. I have been using this for quite a some time now. 
I am using cornerstoneWadoImageLoader for loading images from DICOM files. Now, I am trying to use cornerstone tools for measurements and it works absolutely perfect when it comes to modalities like MR,CT. But my issue is when I try it with the studies of Ultra sound modality, I find that, it gives me the measurements in terms of pixels/pixel2. So is there a way to solve this issue? And if so, can someone please guide me through the solution ?

**Comment by dannyrb** [comment]
@RutulSB, thanks for your support ^_^ Comments like this, starring the repository, small pull requests, etc. All go a long way to helping out, so thank you.

Most tools rely on the DICOM tag `pixelSpacing` to convert pixels to mm. The CornerstoneWADOImageLoader adds a `metaDataManager` to cornerstone core. That manager is queried by cornerstone tools when it needs important information (like pixel spacing for a given image) so it can do its calculations.

Chances are, the US image you have is missing that tag, hence your issue. I'm not up on the standard, but I know vendors don't always follow it. That same information can sometimes be found in 3 or 4 other DICOM tags; however, the CornerstoneWADOImageLoader does not check those fields as a fallback.

I'll double check which fields those would be, and report back on _where_ you would need to update code in order to add support for them.

**Comment by RutulSB** [comment]
> @RutulSB, thanks for your support ^_^ Comments like this, starring the repository, small pull requests, etc. All go a long way to helping out, so thank you.
> 
> Most tools rely on the DICOM tag `pixelSpacing` to convert pixels to mm. The CornerstoneWADOImageLoader adds a `metaDataManager` to cornerstone core. That manager is queried by cornerstone tools when it needs important information (like pixel spacing for a given image) so it can do its calculations.
> 
> Chances are, the US image you have is missing that tag, hence your issue. I'm not up on the standard, but I know vendors don't always follow it. That same information can sometimes be found in 3 or 4 other DICOM tags; however, the CornerstoneWADOImageLoader does not check those fields as a fallback.
> 
> I'll double check which fields those would be, and report back on _where_ you would need to update code in order to add support for them.

@dannyrb, you specified about the other 3 or 4 DICOM tags. Can you please tell me about those tags and how do i get the pixel spacing by that?

**Comment by dannyrb** [comment]
It looks like (I think the values are correct):

- Pixel Spacing (0028, 0030)
- Imager Pixel Spacing (0018, 1164)
- Nominal Scanned Pixel Spacing (0018, 2010)
- Ultrasound Region Pixel Spacing (0018, 6011)

Are all potential fallback tags if `PixelSpacing` is not available. Your `metaDataProvider` would need to use those values if `PixelSpacing` is not available, and return them as the `PixelSpacing` value as part of the `imagePlaneModule`

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/da4c03933b4b6f634c59614a6aa1a479980f2968/src/imageLoader/wadors/metaData/metaDataProvider.js#L34-L68

**Comment by RutulSB** [comment]
> It looks like (I think the values are correct):
> 
> * Pixel Spacing (0028, 0030)
> * Imager Pixel Spacing (0018, 1164)
> * Nominal Scanned Pixel Spacing (0018, 2010)
> * Ultrasound Region Pixel Spacing (0018, 6011)
> 
> Are all potential fallback tags if `PixelSpacing` is not available. Your `metaDataProvider` would need to use those values if `PixelSpacing` is not available, and return them as the `PixelSpacing` value as part of the `imagePlaneModule`
> 
> https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/da4c03933b4b6f634c59614a6aa1a479980f2968/src/imageLoader/wadors/metaData/metaDataProvider.js#L34-L68

@dannyrb I don't know what is wrong with my application, but i don't see a metaDataProvider.js loaded in my application.(I checked it through the chrome developer's tools)

**Comment by RutulSB** [comment]
@dannyrb I have copied this part of code and pasted it in my loadAndViewImage function as follow :

  function getPixelSpacing(dataSet) {
            // NOTE - these are not required for all SOP Classes
            // so we return them as undefined.  We also do not
            // deal with the complexity associated with projection
            // radiographs here and leave that to a higher layer
            var pixelSpacing = dataSet.uint16('x00182010');
            if (pixelSpacing && pixelSpacing.length > 0) {
                var split = pixelSpacing.split('\\');
                return {
                    row: parseFloat(split[0]),
                    column: parseFloat(split[1])
                };
            }
            else {
                return {
                    row: undefined,
                    column: undefined
                };
            }
        }
        // module exports
        cornerstoneWADOImageLoader.getPixelSpacing = getPixelSpacing;

what changes shall i do here, to get pixel spacing value. I tried tags like x00182010, x00280030, x00181164,

**Comment by RutulSB** [comment]
> US uses a special pixel spacing calibration macro, in which regions can be defined [1]. The calculations to determine which pixel spacing to use for each coordinate is lengthy, and you also have to consider when measurements cross regions and their priority.
> 
> [1] https://dicom.innolitics.com/ciods/us-image/us-region-calibration

so how do i get measurements done in US
 ?

**Comment by RutulSB** [comment]
> Can you provide a minimal repository that reproduces this issue? The metaDataProvider should be part of the bundled/minified code included in cornerstoneWADOImageLoader. If measurements are working for some images, then it is likely registered correctly

The issue u asked me to refer was for X-ray and not for US.

**Comment by RutulSB** [comment]
@dannyrb  Thanks for all your inputs so far on this thread . We are working on a viewer focusing on UltraSound studies at the moment  and need to be firm about this  before
we move ahead .

As @ jdnarvaez mentioned above regarding region calibration we tried to explore more and came to know that Making measurements on Ultrasound images requires that your viewer support the "UltrasoundRegion Calibration" module/attributes as mentioned below .

Region Calibration Module :-
http://dicom.nema.org/medical/dicom/2017b/output/chtml/part03/sect_C.8.5.5.html

So we would like to understand if current implementation of  Cornerstone libraries consider these UltaSound specific calibration requirements while making measurements ?
If not then do we have any plans to enhance libraries to support it specifically for UltaSound measurements ?

We also came across  another recent post below regarding ultrasound measurements :-
https://groups.google.com/forum/#!topic/cornerstone-platform/G0mSINhjrRg

Any quick  response / help  in this regard is much appreciated . If this has to be redirected to someone else can you please help us in redirecting it to the 
correct person / forum ?

**Comment by dannyrb** [comment]
CornerstoneTools will use whatever pixelSpacing is provided by the `metaDataProvider`. Currently, regions are not supported. A single (row/column) pixelSpacing is applied to entire image.

While we have an ongoing issue for this feature, to my knowledge, no one is actively working on it. If you would like to contribute functionality, I would be happy to provide guidance and review any PRs. Feel free to follow-up in this issue. I'm closing it for now, as I believe your core questions have been answered.
