### ISSUE TITLE
Throttle Probe Tool Calculations

### ISSUE THREAD

**Issue by hsahin** [cornerstonejs/cornerstoneTools#693]
### Description

Adding more than ~5 probes makes the canvas unresponsive.
This does not happen when adding more than 20 freehand object (containing more than 100 points).

## Steps to Reproduce

1. Add 5 probe points.
2. Panning and zooming becomes slow.

**Expected behavior:**

Have a smooth experience.

**Actual behavior:**
Slow and sluggish canvas tool.

### Codepen With Reproduction of Issue:

cornerstone.enable(element);
cornerstoneTools.mouseInput.enable(element);

cornerstone.loadImage(imageId).then(function(image) {
    cornerstone.displayImage(element, image);
    cornerstoneTools.probe.activate(element, 1);
    cornerstoneTools.probe.enable(element);
}

**Comment by dannyrb** [comment]
This is likely do to how the tool determines when it should recalculate values. Newer methods throttle the calculation, and/or only update the value if the previous value becomes invalid.

More than happy to review a PR for this fix. The vNext branch would likely need it as well

**Comment by hsahin** [comment]
@dannyrb Could you review #698?

**Comment by dannyrb** [comment]
@hsahin , I believe this is a common problem for any tool that looks at pixel values. I've updated the issue and added labels to address the core issue here. While I will look at a fix for the `master` branch, I would prefer to see the work done in `vNext` to reduce the effort required to port changes.

**Comment by dannyrb** [comment]
@evren217 was this addressed in your recent changes? I think we're throttling all annotation tool recalculations now.

**Comment by evren217** [comment]
That is correct. We can close this issue.
