### ISSUE TITLE
Store the angle inside the tool for outside access

### ISSUE THREAD

**Issue by algates90** [cornerstonejs/cornerstoneTools#703]
### Prerequisites

* [X ] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

cornerstoneTools.getToolState(element,'length') -- returns the calculated length value 

![image](https://user-images.githubusercontent.com/30894700/48352905-52945f00-e68e-11e8-976e-502217e851bc.png)

But the same doesnt work for 'angle' -- Does not return the calculated value.

It would be great, if we could add this. Its just one line change needed, that I have done locally now. But would be good if its added to a release.

![image](https://user-images.githubusercontent.com/30894700/48353002-971ffa80-e68e-11e8-8423-51348caf6b2f.png)

Solution : Inside the imageRendered function for angle.

var rAngle = (0, _roundToDecimal2.default)(_angle, 2);
// Store the angle inside the tool for outside access
data.angle = rAngle;

**Comment by dannyrb** [comment]
This issue was originally for v2. In v3, we store the angle in toolState via `cachedStats`
