### ISSUE TITLE
Create a custom measurement tool.

### ISSUE THREAD

**Issue by RutulSB** [cornerstonejs/cornerstoneTools#704]
Hello,
I am using the latest version of cornerstone scripts. I'd like to acknowledge the work you are doing here and I must say cornerstone is a great library. It has certainly helped a lot. I have been using this for quite a some time now.
My question is, how do i write a custom measurement tool(I wish to write a linked-line tool) ? And i cannot see length.js

**Comment by dannyrb** [comment]
See: https://tools.cornerstonejs.org/custom-tools/#creating-your-tool

If you run into hurdles with the documentation, feel free to continue the conversation here and I will do what I can to assist. A `codepen`, `gist`, etc. would be helpful for providing feedback.
