### ISSUE TITLE
Orientation markers

### ISSUE THREAD

**Issue by PunyFlash** [cornerstonejs/cornerstoneTools#705]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

Orientation markers hiding behind the bottom boundarie of the picture when changing the viewport. By default bottom marker always hidden

**ERIK REMOVED THE IMAGE BECAUSE IT HAD PHI**

**Comment by swederik** [comment]
His image had a pretty good reproduction but I had to erase it because it had PHI. You just need to enable the rotation tool and start rotating the image. I think we may have nuked the OrientationMarkers tool in 3.x though, didn't we?

**Comment by PunyFlash** [comment]
Yes, there is no OrientationMarkers tool in the library now. I think the issue is not relevant at this point.
