### ISSUE TITLE
onmousemove element not enabled (after cornerstone.disable(element))

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneTools#731]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

I'm implementing a "delete" option to my viewer. When the user selects the delete tool (a custom tool implemented outside of Cornerstone) and clicks (onmouseup) on an enabled element containing an image, this sequence is executed:

```
ev.stopPropagation(); 
unSetTools(); // this disables all tools (wwwc, zoom, pan)
Toolbar.releaseToolButtons(); // disable pressed buttons
deleteCell(cell); // removes the image associated to the clicked cell (DIV) from an internal array
cornerstone.disable(cell); 
```
That code removes the image from the clicked div, but after that I move the mouse I get a ton of "element is not enabled" raised by `cornerstoneTools.onmousemove`.

I don't know if this is a bug, but it looks like cornerstoneTools is not notified by cornerstone when an element is disabled.

**Comment by dannyrb** [comment]
@leonardorame is this in `v2` (master) or `vNext`? Does your tool add event listeners?

**Comment by leonardorame** [comment]
Hi @dannyrb, I'm using 2.4. Yes, my tool adds `onmousedown` on `onmouseup`event handlers to the `div` clicked by the user.

**Comment by dannyrb** [comment]
@leonardorame, to the best of my knowledge v2.x does not listen for cornerstone's disabled event. You would either need to add that logic to your tool, or manually deactivate and remove listeners for your tool (if I'm understanding your issue).

**Comment by leonardorame** [comment]
Ok. Now, how can I notify a disabled element to `cornerstoneTools`?

**Comment by dannyrb** [comment]
You'll need to check the list of events in the latest version of `cornestone-core`. I believe it emits an event when it is disabled. You would add a listener for that event when your tool is activated. If you hear the event, then you would handle the event by deactivating your tool.
