### ISSUE TITLE
About Reference Lines using WADOURI

### ISSUE THREAD

**Issue by pavankuppa** [cornerstonejs/cornerstoneTools#735]
I have series for the study. How to use reference lines tools for those series to apply 
Images are fetching through WADOURI

As per threads i can get metadata like ```cornerstone.metaData.get("imagePlaneModule", "wadouri:someurl")```

Live Examples mention about axial and coronal.  Do we need to know concepts of Axial & Coronal.

**Comment by tunglt1810** [comment]
Hi,
I have a question for this reference lines tool. What is proper attribute used by this tool, frameOfReferenceUID or imagePlaneModule. My study does have frameOfReferenceUID value in each instance, but it has enough property of image plane module, which specified in DICOM Standard
http://dicom.nema.org/medical/dicom/2018a/output/chtml/part03/sect_C.7.6.2.html

**Comment by dannyrb** [comment]
It does a quick/simple calculation:

- [calculateReferenceLine.js](https://github.com/cornerstonejs/cornerstoneTools/blob/vNext/src/tools/referenceLines/calculateReferenceLine.js#L19-L29)
- [pointProjector.js --> planePlaneIntersection](https://github.com/cornerstonejs/cornerstoneTools/blob/vNext/src/util/pointProjector.js#L134-L210)

It looks like it uses a combination of:

- `rowCosines`
- `columnCosines`
- `imagePositionPatient` (from `imagePlane`)

If you believe you can enhance the tool, I am more than happy to look at a well documented PR that makes a good case for the change 👍
