### ISSUE TITLE
Default tool configuration is overwritten by custom configuration passed to constructor

### ISSUE THREAD

**Issue by evren217** [cornerstonejs/cornerstoneTools#738]
I think we should merge default and custom configuration objects.
See: https://github.com/cornerstonejs/cornerstoneTools/blob/vNext/src/tools/ReferenceLinesTool.js#L31

**Comment by galelis** [comment]
A possible solution could be: 
Make the BaseTool handle the merge of configurations (similar with ReactJS Components) 
- create a static object with a protected name, maybe: `defaultConfiguration`.
- constructor should pass whatever it receives to super (BaseTool)
- BaseTool should get `defaultConfiguration` and `configuration` and merge it correctly.
