### ISSUE TITLE
"Crop" image

### ISSUE THREAD

**Issue by PunyFlash** [cornerstonejs/cornerstoneTools#745]
I'm trying to crop displayed image using
```
viewport.displayedArea.tlhc;
viewport.displayedArea.brhc;
```
When i set custom area, the tools still uses whole image area. Is there a properly way to crop image?

**Comment by swederik** [comment]
That looks like PHI so I am removing the image. @Zaid-Safadi can maybe answer the tool question.

**Comment by Zaid-Safadi** [comment]
@PunyFlash you can see the example here:
https://github.com/cornerstonejs/cornerstone/blob/master/example/displayedArea/index.html#L118-L132

Make sure you set the viewport back into cornerstone after you update it:
`cornerstone.setViewport(element, viewport);
`

**Comment by PunyFlash** [comment]
I set the viewport. IDK what is PHI, but image was needed to understand issue. Tools uses image object and its Metadata to display lengths, angles etc. That's why after I set a viewport the image size don't change. And tools uses coordinates that actually was croped

**Comment by Zaid-Safadi** [comment]
I misread the question initially. I see your problem now.

Yes, displayed area is only used for rendering the image on the canvas at the moment. The tools needs to be updated to take this into consideration when doing any calculations.

**Comment by PunyFlash** [comment]
Is there a way to use an edited image and
```
cotnerstone.displayImage(element, image, viewport)
```
for this task? I tried to change width and height properties, but it completly broke the image.
![image](https://user-images.githubusercontent.com/14828695/49652342-7f902380-fa3a-11e8-910c-2e3b3c0252a2.png)

**Comment by dannyrb** [comment]
@all-contributors please add @Zaid-Safadi for answering Questions

**Comment by dannyrb** [comment]
@PunyFlash, image pixel values are stored in an array. The width/height help us determine, while iterating over that array, the row/column of each pixel value. Incorrect values can cause the image you've included in your last comment.

This issue is a bit stale. I believe the heart of it has been answered. If you think this is something that should be supported, please consider creating a new issue with your proposed changes.

**Comment by brunoalvesdefaria** [comment]
This issue is related to https://github.com/cornerstonejs/cornerstone/issues/474
