### ISSUE TITLE
Is it possible to change the measurement unit from mm to centimeters?

### ISSUE THREAD

**Issue by JesusParra** [cornerstonejs/cornerstoneTools#749]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Is it possible to change the measurement unit from mm to centimeters maybe with a new parameter?
**Expected behavior:** [What you expected to happen]
I expect to have the possibility to select the unit meassure

**Actual behavior:** [What actually happened]
The unit measure is taken from a string 'mm' or 'px' in the lenght.js tool

**Comment by dannyrb** [comment]
@JesusParra, not currently. I'd be open to adding this as a configuration option, if done in a smart way, in our `vNext` branch. If you want to discuss implementation details, we can discuss?

**Comment by JesusParra** [comment]
It's ok, if I have some dubts or if I can to solve it I'll let you know

**Comment by dannyrb** [comment]
This wasn't a formal request to add this behavior and I think the heart of the question was answered. If someone would like to see this as an enhancement, please feel free to create a new issue.
