### ISSUE TITLE
doesn't work Stack Image Position Offset Synchronizer Tool except CT, MR

### ISSUE THREAD

**Issue by ofleaf** [cornerstonejs/cornerstoneTools#754]
I using stack image position offset synchronizer tool.
When I load MR or CT image it works. 
But when I load another modality image, syncing will not take effect.

I tried debugging, MR and CT images were successfully entered into the stack list, but other images were failed.

**Comment by dannyrb** [comment]
Can you share a repository that demonstrates this issue, or a codepen?

**Comment by ofleaf** [comment]
Hi Danny, thanks for reply

I uploaded test source.

https://github.com/ofleaf/cornerstone-demo

You can run using npm run dev and load test image files you can find
/src/assets/image folder.

That's ES modality and I checked it doesn't works about synchronizer tool.

2018년 12월 17일 (월) 오후 11:30, Danny Brown <notifications@github.com>님이 작성:

**Comment by dannyrb** [comment]
It looks like your DICOM images don't have `imagePositionPatient`:

- https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/synchronization/stackImagePositionOffsetSynchronizer.js#L46-L51

Tested here: https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html

The event you're using for your synchronizer should probably be: `cornerstoneimagerendered`
