### ISSUE TITLE
stackImagePositionOffsetSynchronizer does not work and no error are thrown

### ISSUE THREAD

**Issue by YanZiSen** [cornerstonejs/cornerstoneTools#758]
### Prerequisites

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

I imitate demo to achieve the function which maintain the distance in patient space between multiple stacks,but it doesnt work and no error thrown

### Steps to Reproduce

1. init synchronizer 
2. Cyclic generation of multiple div and display Image on them, in the loadImage Callback add them in the synchronizer

**Expected behavior:** ,when i scroll the mouse wheel, the images was scroll syschronizer
**Actual behavior:** when i scroll the mouse wheel, only one image was scrolled

### Codepen With Reproduction of Issue:
<pre>
renderView (view, imageId, seriesId, viewIndex) {
      console.log('imageId', imageId)
      var that = this
      var empty = {
        currentImageIdIndex: 0,
        imageIds: []
      }
      var stack = Object.assign(empty, this.spaceMap[seriesId].stackStart)
      stack.currentImageIdIndex = stack.currentImageIdIndex + viewIndex
      console.log('stack', stack)
      cornerstone.disable(view);
      cornerstone.enable(view);
      // cornerstone.loadAndCacheImage(imageId).then(function(image) {
      cornerstone.loadImage(imageId).then(function(image) {
        cornerstone.displayImage(view, image);
        that.enableEvent(view)
        /* add the stack state */
        cornerstoneTools.addStackStateManager(view, ['stack'])
        cornerstoneTools.addToolState(view, 'stack', stack)

        cornerstoneTools.stackScroll.activate(view, 1)
        cornerstoneTools.stackScrollWheel.activate(view)
        cornerstoneTools.stackScrollTouchDrag.activate(view, 1)
        console.log('seriesObj', that.spaceMap[seriesId])
        that.spaceMap[seriesId].synchronizer.add(view)
        that.spaceMap[seriesId].synchronizer.getDistances()
        console.log('----sourceElem----',that.spaceMap[seriesId].synchronizer.getSourceElements())
      })
    },
</pre>
 
and the view is add

**Comment by YanZiSen** [comment]
I'm sorry for I'm making a lower-level mistake.
Now i solved my problem, a low-level error, did not introduce metaDataProvier.js.

**Comment by dannyrb** [comment]
Thanks for taking the time to update and close the issue, @YanZiSen :+1:
If you need assistance or clarification in the future, please don't hesitate to reach out.
