### ISSUE TITLE
Mean and StdDev are cero in RectangleROI and EllipticalROI (vNext)

### ISSUE THREAD

**Issue by catalinaduplat** [cornerstonejs/cornerstoneTools#759]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Sometimes when creating an elliptical or rectangle ROI, the mean and StdDev are cero, if you move the measurement then the values change.

Issue can be reproduced here: https://deploy-preview-757--cornerstone-tools.netlify.com/#

![screen shot 2018-12-24 at 8 53 19 am](https://user-images.githubusercontent.com/35478824/50401069-ba43cc80-0759-11e9-9a68-817129fcebe2.png)

### Steps to Reproduce

Draw multiple elliptical or rectangle ROIs

**Comment by dannyrb** [comment]
Thanks for the issue report, @catalinaduplat! I'm able to reproduce this. It should be a simple fix. I'll address it after the holidays :+1:

If you need this patched sooner rather than later, feel free to submit a PR and tag me for review.

**Comment by dannyrb** [comment]
Fixed by: https://github.com/cornerstonejs/cornerstoneTools/pull/779
And: https://github.com/cornerstonejs/cornerstoneTools/pull/778
