### ISSUE TITLE
http://chafey.github.io/cornerstoneDemo/ not working

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneTools#761]
The demo at http://chafey.github.io/cornerstoneDemo/
linked from https://github.com/cornerstonejs/cornerstoneTools
does not load any images ..

**Comment by dannyrb** [comment]
If this is still linked in the ReadMe, then it needs to be changed. Not sure that demo has been maintained for a while now.

**Comment by hypertelia** [comment]
+1 for seeing if the 'simple image viewer' could be fixed and/or removed from the ReadMe so as not to 'tease'. Doesn't _look_ to be failing over too much:
```[Error] Origin http://chafey.github.io is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load http://cornerstonetech.org/images/ClearCanvas/GEOB/IMG/I_000001.dcm due to access control checks.```

**Comment by dannyrb** [comment]
We've started to build out some basic examples here: https://tools.cornerstonejs.org/examples/

You can update them by changing code in the `examples/` folder of this solution. Right now, the examples are "per tool" examples, but I'd like us to spin up a few more complex scenarios. Ideally, one would be a very simple viewer. We could also provide an "advanced" link to OHIF's

**Comment by dannyrb** [comment]
The OHIF viewer demo is now using v2 and appears to work on Safari.
Some basic examples have been spun up. If one is missing that you would like to see added, please create a new issue, or create and contribute an example.
