### ISSUE TITLE
Get images with "alltouchtools" from an url on my server.

### ISSUE THREAD

**Issue by DavidHS03** [cornerstonejs/cornerstoneTools#763]
I have tried to obtain it with cornerstone-wado-image-loader

var imageId = 'wadouri:' + imageUrl;

But it does not show any error or show me the image.
There will be another way to get image dicom from url and use it in "AlltouchTools"

I show the complete code:
  cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
        var element = document.getElementById('dicomImage');

        function onImageRendered(e) {
                var viewport = cornerstone.getViewport(e.target);
                document.getElementById('mrbottomleft').textContent = "WW/WC: " + Math.round(viewport.voi.windowWidth) + "/" + Math.round(viewport.voi.windowCenter);
                document.getElementById('mrbottomright').textContent = "Zoom: " + viewport.scale.toFixed(2);
        };

        element.addEventListener('cornerstoneimagerendered', onImageRendered);

        $(function(){
            getImage("../../../files/ana belen bravo medina-RAD-00000003");
        });

       

        function getImage(url){
            
            const imageUrl = url;
            var imageId = 'wadouri:' + imageUrl;

              

            var imageIds = [
                imageId,        
            ];

            var stack = {
                currentImageIdIndex : 0,
                imageIds: imageIds
            };

            var container = element.parentNode;

            document.getElementById('fullscreen').addEventListener('click', function (e) {
                if (!document.fullscreenElement && !document.mozFullScreenElement &&
                    !document.webkitFullscreenElement && !document.msFullscreenElement) {
                    if (container.requestFullscreen) {
                        container.requestFullscreen();
                    } else if (container.msRequestFullscreen) {
                        container.msRequestFullscreen();
                    } else if (container.mozRequestFullScreen) {
                        container.mozRequestFullScreen();
                    } else if (container.webkitRequestFullscreen) {
                        container.webkitRequestFullscreen();
                    }
                }
            });

            var fullScreenEventTypes = ['webkitfullscreenchange', 'mozfullscreenchange', 'fullscreenchange'];
            fullScreenEventTypes.forEach(function(eventType) {
              document.addEventListener(eventType, function() {
                if (!document.fullscreenElement && !document.mozFullScreenElement &&
                  !document.webkitFullscreenElement && !document.msFullscreenElement) {
                  container.offsetWidth = 256;
                  container.offsetHeight = 256;
                  element.offsetWidth = 256;
                  element.offsetHeight = 256;
                } else {
                  container.offsetWidth = window.outerWidth;
                  container.offsetHeight = window.outerHeight;
                  element.offsetWidth = container.offsetWidth;
                  element.offsetHeight = container.offsetHeight;
                }
                cornerstone.resize(element, true);
              });
            });

            var onResize = function () {
                if (document.fullscreenElement || document.mozFullScreenElement ||
                    document.webkitFullscreenElement || document.msFullscreenElement) {
                    container.offsetWidth = window.outerWidth;
                    container.offsetHeight = window.outerHeight;
                    element.offsetWidth = container.offsetWidth;
                    element.offsetHeight = container.offsetHeight;
                    cornerstone.resize(element, true);
                }
            };
            window.addEventListener("resize", onResize);
            window.addEventListener("orientationchange", onResize);

            // image enable the dicomImage element
            cornerstone.enable(element);

            var configuration = {
                testPointers: function(eventData) {
                    return (eventData.numPointers >= 3);
                }
            };
            cornerstoneTools.panMultiTouch.setConfiguration(configuration);
             
            cornerstone.loadImage(imageIds[0]).then(function(image) {
                 console.log(element);console.log(image);
                cornerstone.displayImage(element, image);
               
                // Set the stack as tool state
                cornerstoneTools.addStackStateManager(element, ['stack']);
                cornerstoneTools.addToolState(element, 'stack', stack);

                cornerstoneTools.touchInput.enable(element);
              
                // Enable all tools we want to use with this element
                cornerstoneTools.zoomTouchPinch.activate(element);
                //cornerstoneTools.rotateTouch.activate(element);
                cornerstoneTools.wwwcTouchDrag.activate(element);
                cornerstoneTools.panMultiTouch.activate(element);

                // helper function used by the tool button handlers to disable the active tool
                // before making a new tool active
                function disableAllTools() {
                    cornerstoneTools.panTouchDrag.deactivate(element);
                    cornerstoneTools.rotateTouchDrag.deactivate(element);
                    cornerstoneTools.rotateTouch.disable(element);
                    cornerstoneTools.ellipticalRoiTouch.deactivate(element);
                    cornerstoneTools.angleTouch.deactivate(element);
                    cornerstoneTools.rectangleRoiTouch.deactivate(element);
                    cornerstoneTools.lengthTouch.deactivate(element);
                    cornerstoneTools.probeTouch.deactivate(element);
                    cornerstoneTools.zoomTouchDrag.deactivate(element);
                    cornerstoneTools.wwwcTouchDrag.deactivate(element);
                    cornerstoneTools.stackScrollTouchDrag.deactivate(element);
                }

                // Tool button event handlers that set the new active tool
                var toolSelector = document.getElementById('toolSelector');
                document.getElementById('enableWindowLevelTool').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.wwwcTouchDrag.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('pan').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.panTouchDrag.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('rotate').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.rotateTouchDrag.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('zoom').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.zoomTouchPinch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('zoomDrag').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.zoomTouchDrag.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('stackScroll').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.stackScrollTouchDrag.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('length').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.lengthTouch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('probe').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.probeTouch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('circleroi').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.ellipticalRoiTouch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('rectangleroi').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.rectangleRoiTouch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('angle').addEventListener('click', function (e) {
                    disableAllTools();
                    cornerstoneTools.angleTouch.activate(element);
                    toolSelector.textContent = e.currentTarget.innerHTML
                });
                document.getElementById('clearToolData').addEventListener('click', function() {
                    disableAllTools();
                    cornerstoneTools.wwwcTouchDrag.activate(element);
                    cornerstoneTools.zoomTouchPinch.activate(element);

                    toolSelector.innerHTML = 'Select tool <span class="caret"></span>';

                    var toolStateManager = cornerstoneTools.globalImageIdSpecificToolStateManager;
                    // Note that this only works on ImageId-specific tool state managers (for now)
                    toolStateManager.clear(element);
                    cornerstone.updateImage(element);
                });
                document.getElementById('resetViewport').addEventListener('click', function() {
                    cornerstone.reset(element);
                });
            });
         }

**Comment by dannyrb** [comment]
```js
getImage("../../../files/ana belen bravo medina-RAD-00000003");

function getImage(url){
        
        const imageUrl = url;
        var imageId = 'wadouri:' + imageUrl;
       ...
}
```

`imageId` would equal `wadouri:../../../files/ana belen bravo medina-RAD-00000003` as your code is written. Unless you're using a custom image loader or non-default settings, an example ID would look more like:

`wadouri:https://www.mywebsite.com/path/to/an/image/asset.dcm`
