### ISSUE TITLE
Error combining 2 libraries: Can not read property 'SUPPORT_POINTER_EVENTS' of undefined

### ISSUE THREAD

**Issue by DavidHS03** [cornerstonejs/cornerstoneTools#768]
Hello community, I hope you can help me solve this issue:
Combine 2 libraries (cornerstoneWADOImageLoader-> wadouri / index.html) and (cornerstoneTools-> alltouchtools / index.html)

cornerstoneWADOImageLoader: I use this library to convert a URL to an object image, then I'm interested in the cornerstoneTools library to get the tools that are used in that example.
If the DICOM image is shown in my element document.getElementById ('dicomImage');
But the tools do not work and they send me an error in the console:

Uncaught (in promise) TypeError: Can not read property 'SUPPORT_POINTER_EVENTS' of undefined
    at Object.r [as enable] (cornerstoneTools.min.js: 2)
    at visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 779
r @ cornerstoneTools.min.js: 2
(anonymous) @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 779
Promise.then (async)
getImagetools @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 772
loadAndViewImage @ visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 699
getImage @ visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 689
(anonymous) @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 661
dispatch @ vendors.min.js: 3
q.handle @ vendors.min.js: 3

I would really appreciate it if you can help me.

**Comment by dannyrb** [comment]
Hi @DavidHS03, can you create a codepen or minimum reproduction of this issue in a repo/gist that you can share?

The `.php` errors are a bit odd.

**Comment by DavidHS03** [comment]
Thank you very much for the answer, give me a few hours to be able to create a codepen quickly

**Comment by DavidHS03** [comment]
I'm trying to combine the WADO and Cornerstonejs libraries and I've already managed to get my image from a URL so I can show it with the tools of the alltouchtools example, but some tools do not work mainly WW / WC.
I hope you can help me, I show the code:


      cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
       cornerstoneWADOImageLoader.configure({
          beforeSend: function(xhr) {
              // Add custom headers here (e.g. auth tokens)
              //xhr.setRequestHeader('APIKEY', 'my auth token');
          }
      });

    
    var element = document.getElementById('dicomImage');
    // Listen for changes to the viewport so we can update the text overlays in the corner
    function onImageRendered(e) {
        var viewport = cornerstone.getViewport(e.target);
        document.getElementById('mrbottomleft').textContent = "WW/WC: " + Math.round(viewport.voi.windowWidth) + "/" + Math.round(viewport.voi.windowCenter);
        document.getElementById('mrbottomright').textContent = "Zoom: " + viewport.scale.toFixed(2);
    };
    element.addEventListener('cornerstoneimagerendered', onImageRendered);

    var imageIds = [
       'wadouri:../../../files/norberta tolentino andrade-RAD-00000007',
        
    ];
    var stack = {
        currentImageIdIndex : 0,
        imageIds: imageIds
    };
    var container = element.parentNode;
    document.getElementById('fullscreen').addEventListener('click', function (e) {
        if (!document.fullscreenElement && !document.mozFullScreenElement &&
            !document.webkitFullscreenElement && !document.msFullscreenElement) {
            if (container.requestFullscreen) {
                container.requestFullscreen();
            } else if (container.msRequestFullscreen) {
                container.msRequestFullscreen();
            } else if (container.mozRequestFullScreen) {
                container.mozRequestFullScreen();
            } else if (container.webkitRequestFullscreen) {
                container.webkitRequestFullscreen();
            }
        }
    });
    var fullScreenEventTypes = ['webkitfullscreenchange', 'mozfullscreenchange', 'fullscreenchange'];
    fullScreenEventTypes.forEach(function(eventType) {
      document.addEventListener(eventType, function() {
        if (!document.fullscreenElement && !document.mozFullScreenElement &&
          !document.webkitFullscreenElement && !document.msFullscreenElement) {
          container.offsetWidth = 256;
          container.offsetHeight = 256;
          element.offsetWidth = 256;
          element.offsetHeight = 256;
        } else {
          container.offsetWidth = window.outerWidth;
          container.offsetHeight = window.outerHeight;
          element.offsetWidth = container.offsetWidth;
          element.offsetHeight = container.offsetHeight;
        }
        cornerstone.resize(element, true);
      });
    });
    var onResize = function () {
        if (document.fullscreenElement || document.mozFullScreenElement ||
            document.webkitFullscreenElement || document.msFullscreenElement) {
            container.offsetWidth = window.outerWidth;
            container.offsetHeight = window.outerHeight;
            element.offsetWidth = container.offsetWidth;
            element.offsetHeight = container.offsetHeight;
            cornerstone.resize(element, true);
        }
    };
    window.addEventListener("resize", onResize);
    window.addEventListener("orientationchange", onResize);
    // image enable the dicomImage element
    cornerstone.enable(element);
    var configuration = {
        testPointers: function(eventData) {
            return (eventData.numPointers >= 3);
        }
    };
    cornerstoneTools.panMultiTouch.setConfiguration(configuration);
    console.log(imageIds[0]);
    cornerstone.loadImage(imageIds[0]).then(function(image) {
        cornerstone.displayImage(element, image);

        console.log(image);
        // Set the stack as tool state
        cornerstoneTools.addStackStateManager(element, ['stack']);
        cornerstoneTools.addToolState(element, 'stack', stack);
        cornerstoneTools.touchInput.enable(element);
      
        // Enable all tools we want to use with this element
        cornerstoneTools.zoomTouchPinch.activate(element);
        //cornerstoneTools.rotateTouch.activate(element);
        cornerstoneTools.wwwcTouchDrag.activate(element);
        cornerstoneTools.panMultiTouch.activate(element);
        // helper function used by the tool button handlers to disable the active tool
        // before making a new tool active
        function disableAllTools() {
            cornerstoneTools.panTouchDrag.deactivate(element);
            cornerstoneTools.rotateTouchDrag.deactivate(element);
            cornerstoneTools.rotateTouch.disable(element);
            cornerstoneTools.ellipticalRoiTouch.deactivate(element);
            cornerstoneTools.angleTouch.deactivate(element);
            cornerstoneTools.rectangleRoiTouch.deactivate(element);
            cornerstoneTools.lengthTouch.deactivate(element);
            cornerstoneTools.probeTouch.deactivate(element);
            cornerstoneTools.zoomTouchDrag.deactivate(element);
            cornerstoneTools.wwwcTouchDrag.deactivate(element);
            cornerstoneTools.stackScrollTouchDrag.deactivate(element);
        }
        // Tool button event handlers that set the new active tool
        var toolSelector = document.getElementById('toolSelector');
        document.getElementById('enableWindowLevelTool').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.wwwcTouchDrag.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('pan').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.panTouchDrag.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('rotate').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.rotateTouchDrag.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('zoom').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.zoomTouchPinch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('zoomDrag').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.zoomTouchDrag.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('stackScroll').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.stackScrollTouchDrag.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('length').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.lengthTouch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('probe').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.probeTouch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('circleroi').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.ellipticalRoiTouch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('rectangleroi').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.rectangleRoiTouch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('angle').addEventListener('click', function (e) {
            disableAllTools();
            cornerstoneTools.angleTouch.activate(element);
            toolSelector.textContent = e.currentTarget.innerHTML
        });
        document.getElementById('clearToolData').addEventListener('click', function() {
            disableAllTools();
            cornerstoneTools.wwwcTouchDrag.activate(element);
            cornerstoneTools.zoomTouchPinch.activate(element);
            toolSelector.innerHTML = 'Select tool <span class="caret"></span>';
            var toolStateManager = cornerstoneTools.globalImageIdSpecificToolStateManager;
            // Note that this only works on ImageId-specific tool state managers (for now)
            toolStateManager.clear(element);
            cornerstone.updateImage(element);
        });
        document.getElementById('resetViewport').addEventListener('click', function() {
            cornerstone.reset(element);
        });
    });

**Comment by dannyrb** [comment]
@DavidHS03, were you able to resolve your issue?

**Comment by xkjq** [comment]
Just came across the same issue, it occurred because I wasn't loading all the required dependencies for cornerstoneTools (in my case hammer.js).
