### ISSUE TITLE
The two online examples of angleTool behaving differently

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneTools#773]
Example 1 is in:
https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html
(part of the "All Image Tools Example" pressing "Angle")

Example 2 is in: 
https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/angleTool/index.html

The two examples behave differently on clicking, while example 1 seems to work correctly (to me), in example 2 if you click (press+release) then move the mouse then click (press+release) again you now have a line with two handles and no angle or measurement and no way to create one - IMO very buggey behavior.

I'm not sure why is this but it is confusing and I hope some of the maintainers can have a look ..

Thx!

**Comment by dannyrb** [comment]
Hi @kofifus,

We definitely need to do a better job at highlighting (and naming) the differences about these tools. The `All Image Tools` example is for the `Angle Tool`:

`cornerstoneTools.angle.enable(element);`

The `Angle Tool` example is for the `Simple Angle Tool`

`cornerstoneTools.simpleAngle.activate(element, 1);`

Where the "Simple Angle Tool" is more commonly referred to as a [Cobb Angle](https://en.wikipedia.org/wiki/Cobb_angle). If you draw a second line, you should see a TextBox appear that includes the Cobb Angle calculation. The tools have more appropriate names in `Version 3` (Angle and CobbAngle)

There is an [Outstanding Bug/PR](https://github.com/cornerstonejs/cornerstoneTools/pull/760) for the Cobb Angle tool as well, that may be adding to the confusion.

**Comment by kofifus** [comment]
Thanks!

It seems that all example pages are down ! 
https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html
and 
https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/angleTool/index.html

We actually use them a lot here - is there anyway they can go back up ?

**Comment by dannyrb** [comment]
@kofifus, as a stop gap you can use: https://5c5afda210c70e0008abc93e--cornerstone-tools.netlify.com/

I'm still trying to determine the best way to preserve [version 2's examples](https://rawgit.com/cornerstonejs/cornerstoneTools/v2.4.x/examples/allImageTools/index.html) as we continue to create new examples for version 3.

**Comment by kofifus** [comment]
hmm that seems to be quite broken, neither angle or cobbangle work

**Comment by dannyrb** [comment]
@kofifus the most recent `Netlify` example _should_ be working.

![image](https://user-images.githubusercontent.com/5797588/52392149-8e14ae80-2a6e-11e9-8e07-2c99f9b1f91d.png)

If you're encountering issues, any steps you can provide to reproduce the issue would be appreciated.

**Comment by kofifus** [comment]
ok I think I see the issue

if you drag while holding the mouse you get the correct behavior

however if you click+release then move it creates just lines which is buggy.

can you reproduce ?

**Comment by dannyrb** [comment]
@kofifus, that appears to be the case. Both tools work as I would expect when `click` + `drag` for initial placement. However, `click` + `release` should probably have better initial handle placement.

![2019-02-07_00-37-25](https://user-images.githubusercontent.com/5797588/52392608-a38ad800-2a70-11e9-9878-3d55bbdbc1cb.gif)

@all-contributors please add @kofifus for finding a small usability bug

**Comment by kofifus** [comment]
the bigger issue is if you do:

click+release
move 
click+release
move
click+release
move 
click+release
move

you end up with two 'dud' lines 
I think this is confusing, there should not be a way to leave angles half done and move to another one

see:
![angle](https://user-images.githubusercontent.com/3926071/52393015-6b2edc80-2af8-11e9-88a9-b407e2cf8d8c.gif)

**Comment by dannyrb** [comment]
@kofifus, I agree that it's an issue. I'll likely create a separate bug tracking issue for the change and mark it `Up For Grabs`. It's a bit late for me, so I'm off to bed. Thanks for bringing up this issue, and for continuing to report discrepancies and user experience short-comings 👍

**Comment by kofifus** [comment]
no worries ... still early here

**Comment by dannyrb** [comment]
The two angle examples are now "separate" and exist here:

- https://tools.cornerstonejs.org/examples/tools/angle.html
- https://tools.cornerstonejs.org/examples/tools/cobb-angle.html

**Comment by kofifus** [comment]
Both of the examples linked above seem to be broken (don't show the image)
