### ISSUE TITLE
freehand tool doesn't fire MEASUREMENT_MODIFIED event

### ISSUE THREAD

**Issue by Zaid-Safadi** [cornerstonejs/cornerstoneTools#774]
### Prerequisites

* [ ] Are you running the latest version?
Using v2.4.0
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

The freehand tool doesn't fire the cornerstonetoolsmeasurementmodified event as the other measurement tools

Not sure if this issue is fixed in vNext.

### Steps to Reproduce

1. Register to the event element.addEventListener("cornerstonetoolsmeasurementmodified", onModified);
2. draw a freehand 
3. Event is not being called.

**Expected behavior:** 
The event "cornerstonetoolsmeasurementmodified" be fired and the handler is called.

**Actual behavior:**
Event is not fired.

**Comment by Zaid-Safadi** [comment]
This is fixed for v2 in branch v2.4.x.
I will leave it open to apply the fix for v3

**Comment by JamesAPetts** [comment]
Hey @Zaid-Safadi , if I get time tomorrow I can do this for v3/master :).

**Comment by Zaid-Safadi** [comment]
That would be really nice @JamesAPetts ! please let me know know if there is anything I can help with. Thank you

**Comment by dannyrb** [comment]
Fixed in 3.10
