### ISSUE TITLE
Freehand handles not closed after loading state data

### ISSUE THREAD

**Issue by Zaid-Safadi** [cornerstonejs/cornerstoneTools#775]
### Prerequisites

* [ ] Are you running the latest version?
V2.4.0
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description
After loading the state of the freehand data. click on the first handle which closes the shape and drag, the handle and closing line will be separated and shape is not closed anymore.

### Steps to Reproduce

1. Save the freehand state
2. load the state to draw the line
3. Click and move the first handle point
4. The only one handle is moved leaving the shape open.

**Expected behavior:** 
The point should be moved and both first and last handles moving together to keep the shape closed.

**Actual behavior:** 
Only one handle moves.

**Comment by Zaid-Safadi** [comment]
When drawing the handles, the last handle line is an object that points to the first handle. The code intentionally doesn't update both handles on drag since it is the same object. However, once the data is saved/loaded, the object reference is lost.

To fix this, we should always update the last handle line to sync with the first handle position:

dragHandle  method:
  ```
if (currentHandle) {
    const lastLineIndex = data.handles[currentHandle - 1].lines.length - 1;
    const lastLine = data.handles[currentHandle - 1].lines[lastLineIndex];

```
can be changed such that:
```
  if(currentHandle === 0){
    handleIndex = data.handles.length-1;
  } else {
    handleIndex = currentHandle - 1;
  }

  if (currentHandle >= 0) {
    const lastLineIndex = data.handles[handleIndex].lines.length - 1;
    const lastLine = data.handles[handleIndex].lines[lastLineIndex];


```

If fix is OK, I'll go ahead and submit a PR.

**Comment by dannyrb** [comment]
@Zaid-Safadi, if you make a PR for v2, and vouch that this fix seems reasonable, and works after you've tested it a bit, I can merge it. 

@JamesAPetts, it may be worth checking to see if this is a `vNext` issue as well.

I know we've been saying it for a while now, but we do intend to switch to vNext _very soon_. Our only hold-up right now is the _getting started_ documentation is outdated.

**Comment by Zaid-Safadi** [comment]
Fixed in v2 and v3
