### ISSUE TITLE
New Tool: DICOM Overlays (C.9 Overlays)

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneTools#780]
Hi,

Does cornerstone supports displaying DICOM overlays ? (C.9 Overlays - http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.9.html)

It doesn't show in my tests.

Thank you!

**Comment by kofifus** [comment]
Thanks for the code, @jdnarvaez 👍 👍 very helpful

@dannyrb, IMO this is very core - DICOM overlays are not an added tool but an integral part of the image and cornerstone should be able to show them (ideally with toggle/opacity) even without the tools package ...

**Comment by dannyrb** [comment]
@kofifus, you may be right. I don't have the qualifications to determine that one way or another. From my perspective, the tech side, we do most of our tag parsing and usage in loaders/tools. I don't think `core` ever uses `get` on a `metaDataProvider`.

Are `DICOM overlays` "rendering", or do they impact rendering? Is there a consistent visual result we expect if DICOM overlays are implemented?

@swederik, care to weigh in?

**Comment by kofifus** [comment]
The overlays are described by the dicom standard here - http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.9.html

> "An Overlay Plane describes graphics or bit-mapped text that is associated with an Image. It may also describe a Region of Interest in an Image.
> Each Overlay Plane is one bit deep. Sixteen separate Overlay Planes may be associated with an Image."

> "How an Overlay Plane is rendered is undefined; specifically there is no mechanism to specify with what color or intensity an Overlay Plane is to be displayed, except when rendered under the control of a Softcopy Presentation State SOP Instance."


Usually you want to:
- toggle a particular layer on or off
- determine the opacity of the layer
- color them (less commonly useful I think)

So I think that core should have functions like - `ToggleOverlay(index)`, `SetOverlayOpacity(index)`, `setOverlayColor(index)`

Then a Tool can be made to use those functions in some graphical way, as there is usually only one layer there can maybe be a single toggle tick and opacity slider etc ...

(The standard also specify ROI overlays which are a bit of a different story ...)

**Comment by kofifus** [comment]
Ok I came up with something

See PRs - https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/239 
and - https://github.com/cornerstonejs/cornerstone/pull/347

Basically wadouri metaDataProvider now accepts the type 'overlays' and reads and returns an array of overlays if existing in the dataset

then in core drawImageSync, if the image has overlays they are added to the canvas.

Each overlay has a 'fillStyle' and 'hidden' properties that can be changed to toggle overlays or color them.

I have tested with single overlays, I don't have images containing multiple overlays or ROI. Perhaps some can donate some examples.

Much of the code is a rewrite of @jdnarvaez solution above thanks!

Let me know what you think ..

**Comment by dannyrb** [comment]
@kofifus, thanks for taking the time to PR these concepts! I think the `cornerstoneWADOImageLoader` enhancement makes sense, and is implemented well. It does make me wonder if we should pull out the _metaDataProvider_ into it's own repository, but that's just a side thought.

If you have any helpful, anonymized, images to test this functionality with, could you pass them along? I'm curious to see what these overlays are used for _in practice_. I'm also curious how a viewer like Radiant or Osirix handles overlays.

I'm less sure about the `cornerstone-core` changes. I value your time, and was curious of the answer myself, so I reached out to @swederik and a few others outside of GitHub. The consensus seems to be that the rendering logic for overlays should live in a tool.

If we don't expose granular enough APIs to accomplish this, or if you need assistance creating a `3rd Party Tool`, I would be more than happy to help. If you disagree, and it's okay if you do, we can continue to discuss.

**Comment by jdnarvaez** [comment]
@kofifus I have updated the gist with the tag file. as far as examples, I suggest using the IHE test case for overlays.

**Comment by jdnarvaez** [comment]
[ovly_p01.zip](https://github.com/cornerstonejs/cornerstoneTools/files/2818222/ovly_p01.zip)

**Comment by jdnarvaez** [comment]
FWIW, that contains both the dicom file and the presentation state, as some overlays are read from the PR and one layer of the overlays is read from the embedded pixel data.

**Comment by kofifus** [comment]
sure @dannyrb 

Can you point out an existing tool that this is similar to and I can use as a skeleton ? I may give it a go ..
If the maintainers think a tool is better then we should try that but its more involved so I need more assistance or maybe someone else can take it from here ?

On a side note, regarding your metadata repository comment, personally I don't like the multiple repositories trend, I feel Javascript offers more than enough mechanisms for encapsulation (ie modules) as is and multiple repositories just create an unnecessary overhead.   

Also, we should probably look at adding an equivalent to the new wadouri processing of type 'overlayPlaneModule' to  imageLoader\wadors\metaData\metaDataProvider.js, I am not sure what is the purpose of wadors and how to do that, maybe someone else can chip in ...

@jdnarvaez  - in https://gist.github.com/jdnarvaez/3368ac3e4f7f4eb14bc5f453f8a1ed1b#file-overlays-js-L7

I don't follow that for loop .. the way I read the standard there can be up to 16 layers in DICOM tag groups 0x6000 to 0x600F .. can you please explain further ? Thanks !

**Comment by kofifus** [comment]
I removed the cornerstone PR (cornerstonejs/cornerstone#347)

and created an overlays tool - https://github.com/cornerstonejs/cornerstoneTools/pull/788

The tool is very simple having only enable and disable

Hope this helps :)

**Comment by dannyrb** [comment]
I've created a feature branch for us to iterate on the `cornerstone-tools` portion of this tool:

- `feature/overlay-tool`

When new code is merged, a release is cut and tagged on NPM for `@cornerstonejs/tools@feature-overlay-tool`

I have a CodeSandbox up that is using the `cornerstoneWADOImageLoader` and `cornerstoneTools` branches that pertain to this feature:

https://codesandbox.io/s/1qj7j8op0l

**Comment by dannyrb** [comment]
@kofifus, here's an update:

- The image loader now stores the information in `overlayPlaneModule`
- The tool retrieves the data from the `overlayPlaneModule` and finds 2 overlays in our test DICOM
- When disabled, the image shows 2-lines of text. When enabled, the image shows no new lines of text

Here is what I am able to see in a desktop viewer:

![image](https://user-images.githubusercontent.com/5797588/52543240-1ac4b280-2d76-11e9-9136-4c4b232d92c7.png)

I haven't found a viewer yet that shows all 6-lines, but I only have a few installed locally.

**Comment by kofifus** [comment]
Can you send me a link to download the dicom image pls ?

**Comment by dannyrb** [comment]
It's a bit higher up in this thread. JD shared it: https://github.com/cornerstonejs/cornerstoneTools/issues/780#issuecomment-459419571

**Comment by dannyrb** [comment]
Updated Sandbox: https://codesandbox.io/s/1qj7j8op0l

This is the PR that fixed things up: https://github.com/cornerstonejs/cornerstoneTools/pull/826

![image](https://user-images.githubusercontent.com/5797588/52544542-6b8cd900-2d7f-11e9-9714-acb384302cdc.png)

**Comment by jdnarvaez** [comment]
The code i provided should read all six layers as we render all six in our viewer. I’ll try to have a look at this this week

**Comment by kofifus** [comment]
Possibly the other layers are in the presentation state (see https://github.com/cornerstonejs/cornerstoneTools/issues/780#issuecomment-459419871) which cornerstone does not support ?

**Comment by jdnarvaez** [comment]
Yep, that’s the case.

**Comment by kofifus** [comment]
cool, I believe this can be closed :)

**Comment by dannyrb** [comment]
@all-contributors please add @jdnarvaez for sharing his code for Overlays

**Comment by kofifus** [comment]
@jdnarvaez - in https://gist.github.com/jdnarvaez/3368ac3e4f7f4eb14bc5f453f8a1ed1b#file-graphicoverlays-js-L38 you again call setTransform after calling just above, can you pls explain what is the purpose of the second call ? Thanks!

**Comment by jdnarvaez** [comment]
@kofifus the transform is first set to the coordinates of the current canvas, then it it is saved, then it is set to 1:1 scaling, then reset to the previous scaling. This allows us to draw the overlays in a uniform coordinate system, so that any transformations or scaling by the user are also applied to the overlays
