### ISSUE TITLE
Deactivating a specific tool

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneTools#782]
I need a way to deactivate a single instance of a tool, that is ie for a specific length measurement prevent it's handles and line  from being 'grabbable' while other displayed tools (lengths/angles etc) remain 'grabbable' as usual.

How can this be achieved ? can it be done without changing cornerstoneTools ?

Thanks!

**Comment by dannyrb** [comment]
@kofifus, I believe there is not an elegant way to do this. This does sound like it would be a good feature to have though, and one I'd be open to supporting.

There's a potential work around in the latest version. You can add multiple instances of the same tool type, but with different names:

```js
const LengthTool = cornerstoneTools.LengthTool;

// Add two instances of the length tool w/ different names
cornerstoneTools.addTool(LengthTool); // DefaultName: Length
cornerstoneTools.addTool(LengthTool, { name: 'EnabledLength' });

// Activate our normal "Length" tool
// Enable our "EnabledLength" tool (never change its mode)
cornerstoneTools.setToolActive("Length", { mouseButtonMask: 1 });
cornerstoneTools.setToolEnabled("EnabledLength");
```

Then, and this is the not-so-fun part, any length annotations you want to avoid interactivity with, you add/restore their state to the `EnabledLength` instance of the tool.

**Comment by kofifus** [comment]
I would tend more towards having a flag in the tool's instyance to determine if it is 'frozen' or not

IN our case we have to different sets of annotations, ones coming from the PACS and ones created in the browser, we want to prevent the user from interacting with the PACS ones (just show them), both groups can contain different kinds of annotations ..

**Comment by kofifus** [comment]
Great! I'll close this for now
