### ISSUE TITLE
Add measurement completed event

### ISSUE THREAD

**Issue by Zaid-Safadi** [cornerstonejs/cornerstoneTools#787]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description
Currently the library support the following events for measurements:
- MEASUREMENT_ADDED: 'cornerstonetoolsmeasurementadded',

-   MEASUREMENT_MODIFIED: 'cornerstonetoolsmeasurementmodified',

-   MEASUREMENT_REMOVED: 'cornerstonemeasurementremoved',

This is a proposal to support a new event that is fired once drawing the measurement is completed.
-   MEASUREMENT_COMPLETED: cornerstonetoolsmeasurementcompleted

### Steps to Reproduce
1. Draw a measurement tool

**Expected behavior:** [What you expected to happen]
An event to be fired once the user complete drawing the measurement 

**Actual behavior:** [What actually happened]
No event exists

**Comment by dannyrb** [comment]
Hmm.. This is interesting and makes sense for most annotation tools that aren't "valid" until multiple steps are completed. Some interesting things to consider:

- The main benefit of this over using _added_ and _modified_ is that you don't need to "validate" annotations are in a "complete" storable/re-storable state.
    - IE. An unclosed `freehand`, or an `angle` with only two handles
- Is a measurement truly "added" if it is not complete? Should we already be using this event for annotations that have been successfully "added/completed"?
- Are there any other `lifecycle events` for an Annotation/measurement that we should be considering? Are the previous events already clearly defined and consistently used?
    - Consider: multi-step tools, tools that may have multiple different, but "completed" states, and temporary annotations (dragProbe)

I'm mostly thinking out loud. I like this event, and we'll probably move forward on adding it, but while I have a captive audience, worth shaking out other considerations ^_^

**Comment by Zaid-Safadi** [comment]
Hey @dannyrb , here are some thoughts around this...

I can think of multiple use-cases where I need to do something once the user completes drawing the measurement. These are some examples that I actually encountered:
- validation 
- displaying a dialog
- updating the measurement
- updating another UI to add the measurement.

For example, the arrow annotation displays an input dialog after completion to capture a label. This same behavior might be needed with all other measurements where you want to allow the user to add a label to an ROI (same as in the OHIF lesion tracker target/non-target labeling)

> "Is a measurement truly "added" if it is not complete?" 

I don't know! it felt wrong when I first used it (in the OHIF Measurements Window) but after I got used to it and since it is accompanied by the "delete" event, it was OK. Bottom line, I wasn't expecting the "added" event to be fired immediately once the user start drawing.

In addition to this, all these tools **should** calculate their data at this point rather than waiting until the image is rendered. This has been another struggle that required a workaround to throttle updating the UI (wait for a few seconds) with measurement data after the "modified" event.

I have implemented this behavior locally and have some working version of it. I'll be happy to propose a PR to start with.

**Comment by Zaid-Safadi** [comment]
@dannyrb I have a working version of this for V2 in my local repo that I am looking to merge here soon. Just wanted to give you heads up. If you got some time you can see it here working for some tools:
https://github.com/Zaid-Safadi/cornerstoneTools/commit/5bdecbc6a36f28e542f8f217a339724a9a925862

**Comment by Zaid-Safadi** [comment]
PR #845 created for V2
![completedeventsdata2](https://user-images.githubusercontent.com/10813109/52893262-80df7a00-3168-11e9-9c1d-07cd3f5b00bd.gif)
