### ISSUE TITLE
🎉Announcement: Version 3 - RELEASED

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#794]
> Quick note! If you use or find this repository helpful, please take the time to _star_ this repository. It's a silly metric that doesn't mean much, but it makes me feel warm inside.

# Version 3 - RELEASED

We've just released a new major version of `cornerstone-tools`. Please feel free to play around, ask questions, submit issues, and pull request changes!

We are a _very_ small team, as such there may be many small inconsistencies in our documentation and examples. It's also possible we've missed one or two small changes that made it into `master` these last couple of months, but not `version 3`.

Please feel empowered to create issues and pull requests. The majority of our maintainers and administrators are not the founders of this library. We're Cornerstone users that have slowly picked up the mantle. First by responding to issues, then small documentation updates, and today, a major version rewrite of `cornerstone-tools`

## Recognition

As you assist us in improving `cornerstone-tools`, we'll try to properly recognize you for those efforts! We've add `all-contributors` to better showcase our community members and the ways in which they've helped progress this library. You can view our contributors in the `readme.md`'s "Contributors" section.

@all-contributors please add @JamesAPetts for Documentation, Questions , and Maintenance

## What about version 2 support?

Version two will no longer receive priority support (and to be honest, it has not been for a while now). Existing v2 PRs will be closed. If it's merge into v2 is critical for your success, reopen the PR and point it at the `v2.4.x` branch. Ideally, the functionality should be PR'd against _only_ v3, if possible. Version 2 will continue to be available on NPM, and on our documentation site: https://tools.cornerstonejs.org/history/v2/

[Previous v3 Announcement](https://github.com/cornerstonejs/cornerstoneTools/issues/737)

**Comment by kofifus** [comment]
Thanks! Is there any summary of changes/differences between V2 and V3 ? Also is there any upgrade guide etc ?

**Comment by dannyrb** [comment]
Now that v3 has been out for a while, I'm going to close this issue. Please feel free to leave comments, ask questions, or create new issues ^_^

**Comment by butschster** [comment]
Thank you for your project! I've created a great viewer based on your tools.
![image](https://user-images.githubusercontent.com/773481/55940445-d4da7c80-5c48-11e9-9f0d-018cd81eefc7.png)

Maybe I'll publish this viewer soon!

**Comment by butschster** [comment]
> Maybe I'll publish this viewer soon!

Hi, everyone. I published my viewer, but now I don't have enough time to create npm package. I think someone can help with this.

https://github.com/butschster/DicomViewer/
