### ISSUE TITLE
Docs rely on @latest released npm package, not the highest semver version

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#855]
See: https://github.com/cornerstonejs/cornerstoneTools/issues/827#issuecomment-465412067

When we release a new package, even if it's for `v2.x`, npm shows `@latest` for that version, despite us having a higher major version release. `unpkg` defaults to latest, and that means our examples can be left relying on a previous major version.

[UNPKG](https://unpkg.com/) has examples on how to specify a semver range. Updating our docs to use that should resolve this issue.

**Comment by dannyrb** [comment]
CC: @kofifus

**Comment by kofifus** [comment]
I hope this can be solved asap. Loosing the v2.x examples (and with V3 still seems unstable - ie angleTools) has made life hard for us here :(
