### ISSUE TITLE
mouseInput mouseWheelInput enable in version 3

### ISSUE THREAD

**Issue by unosbaghaie** [cornerstonejs/cornerstoneTools#863]
How to set below code in version 3?

```
  cornerstoneTools.mouseInput.enable(this.element);
  cornerstoneTools.mouseWheelInput.enable(this.element);
```

**Comment by dannyrb** [comment]
After you call `cornerstoneTools.init()` inputs are enabled automatically for all currently enabled elements. Any elements you enable thereafter also have inputs enabled for them.

When you disable an element, the inputs become disabled.

We tried to remove this as a required step, and instead made it an internal detail. If you're finding you need finer control around input enabling/disabling, please let me know.

**Comment by hgdhot** [comment]
when i call cornerstoneTools.init(), got a error, how can i fix that

**Comment by hgdhot** [comment]
![1565690990](https://user-images.githubusercontent.com/19300626/62933821-aa1a5380-bdf5-11e9-91e8-afadebed4ef7.png)

**Comment by dannyrb** [comment]
@hgdhot please create a new issue with the steps required to reproduce.
