### ISSUE TITLE
Version 3 Tools missing from examples page

### ISSUE THREAD

**Issue by unosbaghaie** [cornerstonejs/cornerstoneTools#864]
Does version 3 have the features like Reference Line, Multi layout, ... ?

**Comment by dannyrb** [comment]
Yes. Not all examples that existed for v3 have been completed for v3. I'll stub out pages for the incomplete ones today so their is less confusion.

Please feel free to contribute/PR a quick example if you find something you'd like to see missing.

**Comment by dannyrb** [comment]
@unosbaghaie, the examples have been added as "stubbed out" pages. It should be clearer what you can accomplish in v3, but a demonstration of how to do it may not yet be complete.

For the most part, tools/synchronization function very similarly to how they did in v2. If you're having trouble with a specific tool, please feel free to create a new issue with any questions you have and what you've tried so far.

https://tools.cornerstonejs.org/examples/
