### ISSUE TITLE
Documentation incorrect for setting tool modes

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstoneTools#875]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Looks like the cTools v3 docs are wrong: https://tools.cornerstonejs.org/anatomy-of-a-tool/#modes: setToolModeActive should be setToolActive, etc...

**Comment by biharck** [comment]
Fixed at https://github.com/cornerstonejs/cornerstoneTools/pull/973

**Comment by dannyrb** [comment]
@all-contributors, please add @biharck for docs
