### ISSUE TITLE
Cant't find API document

### ISSUE THREAD

**Issue by zhangluwei1997** [cornerstonejs/cornerstoneTools#885]
API is 404

**Comment by dannyrb** [comment]
It looks like the API doc generation was broken in the last CI update.

If you have the solution locally, you can generate the docs yourself with the appropriate npm script. It uses the JSDoc comments to create itself, so taking a peak at `src/index.js` and `src/lib.js` should provide a rough version of what is available to you, and any JSDoc comments along the way will provide additional info.

Thanks for the report. I'll take a stab at fixing this when I have a free moment.

**Comment by dannyrb** [comment]
@zhangluwei1997, it needs some love, but https://tools.cornerstonejs.org/api/ is up and running.

Give it a second, as it's a SPA and loads all of it's data on init before displaying any content.
