### ISSUE TITLE
How to configure Reference Lines Tool in version 3 

### ISSUE THREAD

**Issue by federicomrossi** [cornerstonejs/cornerstoneTools#890]
### Description

When trying to add and activate the reference lines tool, it throws the following error:

> cornerstoneTools.js?e6ad:14814 Unable to enable ReferenceLines. Exiting enable callback. Tool will be enabled, but will not render.

### Steps to Reproduce

The reference lines tool was initialized with:

```
cornerstoneTools.init({
    globalToolSyncEnabled: true
})

const ReferenceLinesTool = cornerstoneTools.ReferenceLinesTool
cornerstoneTools.addTool(ReferenceLinesTool)
cornerstoneTools.setToolActive('ReferenceLines', {})
```

**Additional information:** the synchronizer was previously created (before the code above) with the following line: 

```
const synchronizer = new cornerstoneTools.Synchronizer('cornerstonenewimage', cornerstoneTools.updateImageSynchronizer)
```

### Question

What is the right way to initialize and configure the Reference Lines Tools in the new version?

Thanks!

**Comment by unosbaghaie** [comment]
Hi
I need to implement Reference Lines Tool in version 3. When the documentation will be ready?

**Comment by dannyrb** [comment]
@unosbaghaie, when it reaches the top of my priorities list, or some brave soul (maybe even you?) takes the time to PR an example ^_^

**Comment by dannyrb** [comment]
https://tools.cornerstonejs.org/examples/tools/reference-lines.html

I've added a `ReferenceLinesTool` to our examples. FWIW, there is more than one way to skin this cat. I've seen this same thing accomplished with a `CustomTool` that doesn't require a synchronizer.

I'm more than happy to discuss changes to the tool that make it easier to use in a new issue, or look at PRs that improve the tool or it's documentation.
