### ISSUE TITLE
calling setToolModeForElement too many times can cause an exception

### ISSUE THREAD

**Issue by mikehazell** [cornerstonejs/cornerstoneTools#898]
### Prerequisites

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

**Bug**

Calling any of the `setToolMode` methods too many time with options of `{ mouseButtonMask: 1 }` will eventually cause the app to crash with a "RangeError: Invalid array length" error.

This is happening this line: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L213

```js
  // Keep the same if not an array (undefined)
  // Reset if empty array
  // Merge if array contains any bindings
  if (
    Array.isArray(options.mouseButtonMask) &&
    options.mouseButtonMask.length !== 0 &&
    Array.isArray(tool.options.mouseButtonMask)
  ) {
    options.mouseButtonMask = options.mouseButtonMask.concat(
      tool.options.mouseButtonMask
    );
  }
```

The code here is concatenating the `mouseButtonMask` array but not removing duplicates.

I'll create a PR shortly with tests showing the issue and a fix.

**Comment by dannyrb** [comment]
Merged 👍
