### ISSUE TITLE
Enabling prefetch on a second image discards first prefetch

### ISSUE THREAD

**Issue by t-animal** [cornerstonejs/cornerstoneTools#900]
The stack prefetch tool clears the prefetch queue when enabled on an element. If you have two elements on a page and enable the prefetching on both this causes the first element's stack not to be prefetched. 

https://github.com/cornerstonejs/cornerstoneTools/blob/0934f59883f1f2023a0cd5511ddcb00c2e9e23f9/src/stackTools/stackPrefetch.js#L136

**Comment by dannyrb** [comment]
@t-animal, will the changes outlined in @frolic06's PR resolve your issue? Do you have any recommended alternative ways to handle this situation?

**Comment by dannyrb** [comment]
@t-animal check out the configuration added here: https://github.com/cornerstonejs/cornerstoneTools/pull/1074/files

If it doesn't resolve your issue, or if you would like to see the ergonomics of this improved, please don't hesitate to comment and we can discuss.
