### ISSUE TITLE
console.log messages are too noisey

### ISSUE THREAD

**Issue by mikehazell** [cornerstonejs/cornerstoneTools#901]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

There are many places in the codebase which are calling console.log for example on mouse interaction or on state change of a tool. This makes the console very noisy and hard to use as a tool when developing on-top of cornerstoneTools.

The following is a pretty common sight in my console.

![image](https://user-images.githubusercontent.com/814227/54964443-9d20d300-4fc0-11e9-8fe6-498e867b1a24.png)

---

### Suggestion

One solution to this would be to add a tool like [debug](https://github.com/visionmedia/debug#readme) 
 (no affiliation) for logging.

Debug is really useful for library makers to keep useful logging around to aid in debugging issues while having it disabled by default.

It also lets you "scope" logs so they can be filtered in/out and be identified by color.

Debug is enabled/disabled using a field in `localStorage` so the setting will persist through a refresh.
 
```js
// Show all debug logs - note this may include other libraries which also use debug
localStorage.setItem('debug', '*');

// Filter by scope
// - all cornerstoneTools logs
localStorage.setItem('debug', 'cornerstoneTools:*');

// - just the cornerstoneTools:annotation scope
localStorage.setItem('debug', 'cornerstoneTools:annotation');
```

Example output in a chrome console:
![Debug output example](https://user-images.githubusercontent.com/71256/29092033-b65f9f2e-7c39-11e7-8e32-f6f0d8e865c1.png)

I'd be happy to make a PR to get this started.

**Comment by dannyrb** [comment]
Ah! @JamesAPetts and I were just discussing better logging practices. The current state of things is a bit embarrassing. Please feel free to continue down this path ^_^

**Comment by JamesAPetts** [comment]
I approve of any work in this direction. The current console logs are relics from the rapid development of 3.0 haha. It'd be nice to turn it off entirely for production use.
