### ISSUE TITLE
brush tool's passiveCallback throws when changing image if globalToolSyncEnabled is true

### ISSUE THREAD

**Issue by mikehazell** [cornerstonejs/cornerstoneTools#924]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

Crashing Bug: using the Brush tool with `globalToolSyncEnabled` can cause the application to crash when a new element is enabled.

### Steps to Reproduce

1. initialize csTools with `{ globalToolSyncEnabled: true }`
2. enable an element and load an image
3. set the brush tool mode to "active"
4. set the brush tool mode to "passive"
5. enable a second element.

**Expected behavior:** [What you expected to happen]

The 2nd element should be enabled

**Actual behavior:** [What actually happened]

The application crashes with the following error.

```
Uncaught Error: updateImage: image has not been loaded yet
    at Module.<anonymous> (cornerstone.js:7603)
    at BrushTool.passiveCallback (cornerstoneTools.js:24482)
    at setToolModeForElement (cornerstoneTools.js:11614)
    at cornerstoneTools.js:11694
    at Array.forEach (<anonymous>)
    at _resolveInputConflicts (cornerstoneTools.js:11684)
    at setToolActiveForElement (cornerstoneTools.js:11430)
    at cornerstoneTools.js:10756
    at Array.forEach (<anonymous>)
    at _repeatGlobalToolHistory (cornerstoneTools.js:10753)
```

**Comment by dannyrb** [comment]
`{ globalToolSyncEnabled: true }` and I thought I was the only one using that setting ^_^
I'll take a look at your PR. Thanks for the report!
