### ISSUE TITLE
Polygons disappear when viewport resized

### ISSUE THREAD

**Issue by dongtanhuy** [cornerstonejs/cornerstoneTools#926]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

I use `draw()` API of `cornerstoneTools` to draw a polygon on canvas by clicking on a button. I draw successful but when the viewport resized (by opening size bar menu), the polygon was disappeared. How can I keep the polygon shown when resizing the viewport?

### Steps to Reproduce

1. Click the button to draw the polygon
2. Open the sidebar menu

**Expected behavior:**
The polygon is shown
**Actual behavior:** 
It disappeared and I have to click the button again to re-draw it

### My code
```js
import { cornerstone, cornerstoneTools } from 'meteor/ohif:cornerstone';

const { draw, path } = cornerstoneTools.drawing;
const drawingPolygons = (canvas) => {
  const context = canvas.getContext('2d');
  console.log(canvas);
  const points = [100, 100, 150, 100, 150, 150, 100, 150];
  draw(context, (ctx) => {
    ctx.fillStyle = 'red';
    ctx.beginPath();
    ctx.moveTo(points[0], points[1]);
    for (let item = 2; item < points.length - 1; item += 2) {
       ctx.lineTo(points[item], points[item + 1]);
     }
    ctx.closePath();
    ctx.fill();
    });
  });
};
```

**Comment by dannyrb** [comment]
The draw api helps tools render annotations in a consistent way. They do not account for the entire lifecycle of a tool on their own. For example, any time tool data is manipulated, or the viewport changes, the canvas needs to re-render. Any previously rendered annotations are cleared, and they need to be drawn with the viewport's changes in mind.

Your best bet is to create a custom cornerstone polygon tool. Then, set its state and allow the tool to manage the nitty gritty details for you.
