### ISSUE TITLE
How to resize an ellipse making it a perfect circle and maintaining its centre?

### ISSUE THREAD

**Issue by pedj21** [cornerstonejs/cornerstoneTools#927]
### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
### Description
Hi,
 I would like to create a circle tool or adapt the Elliptical tool that maintains its centre when it is resized. I have thought in these two approaches: 
•	Force the handles of an ellipse to move diagonally, similar to the way that the bidirectional tool propose new handle points. Then, adjust the handle.start if the handle.end has moved and vice-versa, so that the centre is kept the same.
•	Press the shift key while dragging the handle to turn the ellipse into a circle. This will cause the mouse to no longer be attached with the handle (e.g Microsoft Word shapes).
Any suggestions?

**Comment by dannyrb** [comment]
👋 Hello, @pedj21.

This is possible to do by creating a custom tool, but it's also something we might be interested in baking in as supported/maintained functionality.

Take a look at the source code for the [EllipticalRoiTool](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/EllipticalRoiTool.js)

A circle tool would be very similar, if not a bit simpler. I think the key would be to only have one handle.

_Create_

- Clicking (`createNewMeasurement`) prompts for a radius in `mm` OR
- Clicking and dragging places the center and drags the _radius handle_

_Reposition_

- The circle is draggable by a `center` crosshair OR
- The circle is draggable by the rendered annotation (within a threshold)

(This is already the default behavior for _pointNearTool_)

_Resize_ 

- Double clicking an annotation prompts for a new radius in `mm`
- Grab the _radius handle_ to set the circle's radius. The center remains stationary

In essence, if we move away from two handles to one handle, we can use the position and a radius to draw the circle.

If you prefer to modify the behavior of the ellipse tool when a key is down, you may want to look at how the FreeHandTool accomplishes this.

**Comment by singhArmani** [comment]
Hi @dannyrb, 
I have created a CircleRoiTool implementation which has similar functionality as described above. I can create a PR for this tool 😄

**Comment by dannyrb** [comment]
That would be awesome, @singhArmani ^_^

**Comment by dannyrb** [comment]
@pedj21, @singhArmani was nice enough to contribute his CircleRoiTool -- it is available in the latest version.

If anyone else is hiding out there and wants to contribute a tool, either to core or as one maintained in a separate repo, don't hesitate to reach out ^_^
