### ISSUE TITLE
Prevent WheelEvent from propagating when middle mouse button is pressed

### ISSUE THREAD

**Issue by Karl-Heinrich** [cornerstonejs/cornerstoneTools#935]
When pressing the middle mouse button to activate a tool (e.g. PanTool, LengthTool, ..) a WheelEvent might be triggered and propagated as well. 

This itself might not be problematic, but when using a stack of images and the middle mouse button is pressed to e.g. zoom, pan, measure, .. the images in the stack start scrolling.

This behaviour is unwanted and can be deactivated by manually grabbing the native event and disabling the usual scroll behaviour:

```
enabledElement.onwheel = evt => {
            if (evt.deltaY < 1 || evt.deltaY > -1) {
                evt.stopImmediatePropagation();
            }
        };
```

Recreating this is straightforward, just set the `mouseButtonMask` to 4 (middle mouse button) in any of the public examples and e.g. log something when the WheelEvent happens or take a look at [this fiddle](https://jsfiddle.net/g2jefho7/1/).

**Important**: If you have a good mouse, you might not be affected! I am using a Logitech M500 for which the bug certainly is real.

![wheelOnFire](https://user-images.githubusercontent.com/38315992/57937300-f07b1780-78c5-11e9-8dc9-2d9297180361.gif)

**Comment by dannyrb** [comment]
@Karl-Heinrich, I am able to reproduce, and I agree with your assessment. Is this something you would be interested in drafting a Pull Request for?

**Comment by Karl-Heinrich** [comment]
Sure! Could you point me to the correct file(s), where you think a fix to this should go?

**Comment by dannyrb** [comment]
Pretty much all of the events we support tool interaction for go through our global listeners, so we can normalize them across browsers, and tack on some extra data. You can find them here:

- [src/eventListeners](https://github.com/cornerstonejs/cornerstoneTools/tree/master/src/eventListeners)

For `wheelEvent` specific logic, check out:

- [src/eventListeners/wheelEventListener.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/eventListeners/wheelEventListener.js) and
- [src/eventListeners/wheelEventListener.test.js](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/eventListeners/wheelEventListener.test.js)

It should be as simple as modifying the first few lines of the wheelEventListener's handler function.
