### ISSUE TITLE
MouseButtonMask is not mapped correctly

### ISSUE THREAD

**Issue by lgaudez** [cornerstonejs/cornerstoneTools#946]
### Prerequisites

* [ ] Are you running the latest version? Yes
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

When I was playing with example, I switched RectangleRoiTool to be triggered only on Mouse 2 button (mouseButtonMask : 2). It is working fine when creating a new shape but button 1 click is always triggered when trying to move an existing shape. I was not expecting that and I can't find any solution to hook this behaviour. 

I also tried with other tools and the behaviour is the same (ProbeTool, ArrowAnnotateTool...)

It seems to be a regression from version 3. It didn't happens with version 2. 

Here is a video of the bug, playing with mouse 2 button, then mouse 1 : https://www.loom.com/share/9b833f7caa604013883b8ebf8f7b420f 

With this code 
`   cornerstoneTools.addTool(cornerstoneTools.RectangleRoiTool);
     cornerstoneTools.setToolActive("RectangleRoi", {mouseButtonMask: 2})`

And the same is happening when using option : {mouseButtonMask: [2]}

Any workaround ?

**Expected behavior:** Button mask should match only the given button mask.

**Actual behavior:** Button mouse 1 triggers moving shapes.

### Codepen With Reproduction of Issue:

Basic template does not display any viewer. I didn't success to make it work.
- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by dannyrb** [comment]
All `active` and `passive` annotations can be interacted with. `enabled` tools are "read only" and cannot be dragged: https://tools.cornerstonejs.org/anatomy-of-a-tool/#modes

AFAIK, this has always been true and the intent.

It's common to draw a `line` annotation, and then draw a `square` annotation. You shouldn't have to re-select the `line` annotation to move it. I believe most other editors follow a similar pattern? But I may be mistaken.

I don't think it's currently possible to do what you want without a PR to add new functionality. If I'm misunderstanding your issue, please don't hesitate to clarify.

I'll create a new issue shortly for the broken basic template. That version does look outdated.

**Comment by lgaudez** [comment]
Thank for your reactivity. I actually expect that an existing annotation would interact only with the maskMouseButton given in parameter using setToolActive method : `cornerstoneTools.setToolActive("RectangleRoi", {mouseButtonMask: 2})`

The behaviour for now is that when I'm clicking with button 1, I can move the annotation. Is that clearer ? Thanks

**Comment by dannyrb** [comment]
As it stands, all existing annotations respond to the primary input regardless of their `mouseButtonMask`. The `mouseButtonMask` is really for defining which buttons are used for _creating_ new annotation data.

You could create a PR that adds a new global configuration setting, that changes the behavior in the `mouseDown` event handler: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/eventDispatchers/mouseEventHandlers/mouseDown.js#L31

This is where we filter tools to determine if they can be interacted with. If no tools are found, we fall into the `mouseDownActivate` handler.

**Comment by lgaudez** [comment]
thanks for explanation, you can close this issue :)
