### ISSUE TITLE
How to add a unit to ScaleOverlayTool, version 2.4.0

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneTools#948]
How to add a unit to ScaleOverlayTool, version 2.4.0

**Comment by dannyrb** [comment]
AFAIK, this is not currently supported. I'm also skeptical that the scale is accurate when a rotation is applied. To accomplish this, you would likely need to create a fork of 2.4, or add a custom tool in 3.x, or PR the updated functionality in 3.x.
