### ISSUE TITLE
How to implement ArrowAnnotate tool on cornerstoneJs

### ISSUE THREAD

**Issue by chaiwatt** [cornerstonejs/cornerstoneTools#950]
Dear Sir, I have usage problem on 'arrowannotate' tool. Below is my javascript code.

```
function loadAndViewImage(imageId) {
    var element = document.getElementById('demo-element');
    try {
        var start = new Date().getTime();
        cornerstone.loadAndCacheImage(imageId).then(function(image) {
            var viewport = cornerstone.getDefaultViewportForImage(element, image);
            cornerstone.displayImage(element, image, viewport);
            if(loaded === false) {
                cornerstoneTools.mouseInput.enable(element);
                cornerstoneTools.mouseWheelInput.enable(element);
                cornerstoneTools.wwwc.activate(element, 1); // ww/wc is the default tool for left mouse button
                loaded = true;
            }
            document.getElementById('btndeactivatewwwc').addEventListener('click', function(e) {
               cornerstoneTools.wwwc.deactivate(element, 1); 
               cornerstoneTools.arrowannotate.activate(element, 1); // activate arrowannotate here, but not work.
            });
        }, function(err) {
            alert(">>" + err);
        });
    }
    catch(err) {
        alert(err);
    }
}
```
Code work find for 'wwwc' tool, but once I change to arrowannotate then nothing draw on viewport. I'm very new on cornerstoneJs, Any advise or guidance would be greatly appreciated, Thanks.

**Comment by dannyrb** [comment]
:wave: Hi! It looks like you're using an older version of CornerstoneTools. It'll be easier for you to find support here if you're using the latest major version.

If you create a minimal reproduction in Codepen or Codesanbox, I can take a quick peak. There should be a version 2 branch in this repo if you need to poke through old examples or source code.

**Comment by dannyrb** [comment]
It's been a little over a week with no response. I'm going to close this for now, but feel free to respond to continue the conversation.
