### ISSUE TITLE
Zoom out limited to 25%

### ISSUE THREAD

**Issue by LadislavBohm** [cornerstonejs/cornerstoneTools#964]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

I noticed in every example of cornerstone tool zoom for both mouse wheel and mouse button, that it is limited to zoom out to 25%. Is there any reason for that and is it possible to change this so I can zoom out more?
I checked source code and there doesn't seem to be a way to set this value. I also thought that I should probably play with viewport scale but I am not sure whether it is the right solution.
I can upload my dcm file that I used for testing, but I think the example used below should be enough.

### Steps to Reproduce

1. Go to this official example: https://tools.cornerstonejs.org/examples/tools/zoom.html
2. Zoom in a little bit and you will see that the zoom "jumps" a bit
3. There is no way to zoom out to the original image size

**Expected behavior:**
I would expect to be able to either set minimum zoom value (less than 25%) or otherwise scale my image so I can fully zoom out.

**Actual behavior:** 
Once I zoom I cannot zoom out enough so I can't see whole original image.

### Codepen With Reproduction of Issue:
I hope this example is enough, although its not Codepen.
https://tools.cornerstonejs.org/examples/tools/zoom.html

**Comment by dannyrb** [comment]
https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/ZoomTool.js#L28-L33

Our docs are pretty sparse. Issues like these help my prioritize which ones are being used and should receive attention. Most of the tool logic is easy enough to find by exploring the source code. Please don't hesitate to do a little digging and PR your own update to the docs -- still can't find what you're looking for? Reach out. I'm always more than happy to help ^_^

```js
  cornerstoneTools.addTool(cornerstoneTools.ZoomTool, {
    configuration: {
      invert: false,
      preventZoomOutsideImage: false,
      minScale: .1,
      maxScale: 20.0,
    }
  });
  cornerstoneTools.setToolActive('Zoom', { mouseButtonMask: 1 })
```

A few tools have multiple strategies or configuration that can be set when added. Other tools have "options" that can be set in any `setToolXXX` call.

I have an active PR to tidy up a few examples. I'll add this information to the Zoom Tool's page.

**Comment by dannyrb** [comment]
Addressed here: https://github.com/cornerstonejs/cornerstoneTools/pull/961/commits/c35f7ec0ec62c490ba909cd42e79abb60b3c6526
