### ISSUE TITLE
Hello, why can't I find orientationMarkers Tool in v3.12.2 source code?

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneTools#967]
Hello, why can't I find orientationMarkers Tool in v3.12.2 source code?

**Comment by dannyrb** [comment]
I'm not sure it was brought over in the transition to v3. Looking back as far as `tag` 3.0.1, I see that it's core logic exists, but nothing that would render to the canvas:

https://github.com/cornerstonejs/cornerstoneTools/tree/v3.0.1/src/orientation

I would be more than happy to accept an "overlay example" of orientation markers, or an updated tool for rendering those markers to the canvas.

**Comment by dannyrb** [comment]
Addressed here: https://github.com/cornerstonejs/cornerstoneTools/pull/1089
