### ISSUE TITLE
Memory leaks with Magnifier

### ISSUE THREAD

**Issue by kisadam220** [cornerstonejs/cornerstoneTools#977]
Hi everyone.

When using the magnifier multiple times (just clicking mad many times), memory used is going up. I found this problem even with the example of the memory tool : https://tools.cornerstonejs.org/examples/tools/magnify.html 
I might be doing something wrong here but i do not know if the magnifier canvas gets disposed after use. The memory leaks happen even when loading new images repeatedly. I use cornerstone.disable() and cornerstone.imagecache.purgecache() after use but they dont seem to take effect. It might be something I am not doing right but i did not find anything that helped me.
(images are loaded with loadAndCache)
 Thanks for any suggestion or help in advance!

**Comment by dannyrb** [comment]
It's possible we're not disposing of something properly. You can find all of the `Magnify` Tool's code here:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/MagnifyTool.js

The tool works be creating a `canvas` element, enabling it w/ cornerstone, and rendering an image to the canvas at a new scale:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/MagnifyTool.js#L202

We set our reference to the element to null to clean-up, but maybe that's not enough, or this isn't behaving as expected. There are a couple of other areas in that file that could be causing the issue as well.

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/MagnifyTool.js#L226-L231

Unfortunately, this isn't something I'll find to address soon. However, if you can identify the leak and draft a PR, I can prioritize reviewing it.

**Comment by dannyrb** [comment]
Related: https://github.com/cornerstonejs/cornerstoneTools/pull/934

**Comment by dannyrb** [comment]
With #934's merge, this should be fixed. If you're still experiencing memory issues, please feel free to re-open or create a new issue.
