### ISSUE TITLE
CORS issue while starting Jekyll examples from suggested initial url.

### ISSUE THREAD

**Issue by romulobordezani** [cornerstonejs/cornerstoneTools#978]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description
CORS issue while starting Jekyll examples from suggested initial url, `127.0.0.1:400`
![Screen Shot 2019-06-17 at 1 23 01 PM](https://user-images.githubusercontent.com/3472146/59625000-a082b100-910e-11e9-9655-6974796c359d.png)

### Steps to Reproduce

1. Follow the /examples docs to run Jekyll, open the suggested initial url.
![Screen Shot 2019-06-17 at 2 02 25 PM](https://user-images.githubusercontent.com/3472146/59625024-a9738280-910e-11e9-8603-dde3ff8eedc5.png)

**Expected behavior:**
To have the working initial url suggested: localhost:4000 or make `cornerstoneWADOImageLoader` dependency accepts also 127.0.0.1 IP.

**Actual behavior:** 
CORS issues are stopping `cornerstoneWADOImageLoader`, which is not work properly from 127.0.0.1:400

**Comment by vsaase** [comment]
Hi,
the same issue appeared again. I ran jekyll and opened the rectangle scissors example at 127.0.0.1:4000
This gives me a CORS error on loading the DICOM, which is resolved by using localhost:4000

**Comment by dadlaniTarun** [comment]
@vsaase I am also getting CORS issue, did you find any fix for it?

**Comment by jayendramadaram** [comment]
i have also encountered this issue i am running my server at localhost : 80 still i get error to change cors

how to change headers manually 

which file shall i edit
