### ISSUE TITLE
API to store / retrieve enabled tools by mouse button

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstoneTools#98]
We need an API to store / retrieve the enabled/activated tools for each mouse button. This will make it easier for users to switch tools in their applications.

Brought up here:
https://groups.google.com/forum/#!topic/cornerstone-platform/6JVm2Jb59SI

**Comment by dannyrb** [comment]
@swederik, would this work by...

1. New top level property: 
    - `activeTools: []`
2. `cornerstoneTools.someToolName.activate(canvas, mouseButtonNum)`
    - Add `{ toolName: "", mouseBinding: 1, deactivate: deactivateFn() }` to `activeTools` array
3. `cornerstoneTools.someToolName.deactivate(canvas, mouseButtonNum)`
    - Remove tool from `activeTools` array
4. Top level getter:
    - GetActiveTools( (optional) mouseBindingNum)

**Comment by dannyrb** [comment]
You can do this in `vNext`.

`store.state.tools` contains an array of tools. If you filter by tool's where:

- tool.mode is `active`
- tool.mouseButtonMask (array) contains the mouse button int

There is a very crude additional abstraction to help if your use case means tools will always be in sync across canvases.

I'll close this for now, but I'm open to a discussing a more explicit or friendlier option
