### ISSUE TITLE
How disable or deactive all tools for an element

### ISSUE THREAD

**Issue by unosbaghaie** [cornerstonejs/cornerstoneTools#981]
How can I disable or deactive all tools for an element?

**Comment by dannyrb** [comment]
`cornerstoneTools.store.state.tools`

Is an array of tools. Each tool has an `element` property.

1. Filter the array by the target element.
2. For each tool in the filtered array, call `cornerstoneTools.setToolDisabledForElement(element, tool.name)`

Or at least something similar to that song and dance.
