### ISSUE TITLE
Tools are not activated

### ISSUE THREAD

**Issue by dimo2008** [cornerstonejs/cornerstoneTools#982]
I am trying to activate any tool but it none is working ,for example: lengthtool
steps:
1-cornerstoneTools initialization 
2- enabling cornerstone to the needed element
3- adding LengthTool to the element
4- when setting it to active the console gives me the message:
(Unable to find tool "Length" for enabledElement)
however when trying to add the tool again a message says:
(Length has already been added to the target element)
** using cornerstoneTools version 3.13.0

**Comment by dannyrb** [comment]
@dimo2008 can you create a minimal reproduction in a Codepen, CodeSandbox, or separate repository? A snippet would also be helpful

**Comment by dimo2008** [comment]
sorry for late reply, i solved the problem, i was referring to the parent element.
