### ISSUE TITLE
Hello, team I've requested to develop wheel experience.

### ISSUE THREAD

**Issue by gkgkska** [cornerstonejs/cornerstoneTools#983]
### Prerequisites

* [O] Are you running the latest version?
   yes, currently, want to extend tool.
* [O] Are you reporting to the correct repository?
  cornerstoneTool what I've been requested to
* [O] Did you perform a cursory search?
    mouse event? I did

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
 I was using cornerstone2.x version and I like the feature that I can enable mouse event with wheel zoomIn, zoomOut behavior, but what I update feature to cornerstoneTool3.x, I can only use right click to zoomIn, zoomOut with my wheel. 
2. [Second Step]
is it anyway I can control mouse event with setToolActive?
3. [and so on...]
if not I would like to contribute my request. 
Thanks.
**Expected behavior:** [What you expected to happen]
Wheel to zoomIn
**Actual behavior:** [What actually happened]

### Codepen With Reproduction of Issue:

- [Basic Template](https://codepen.io/dannyrb/pen/OQQwza)

**Comment by dannyrb** [comment]
It looks like our examples need updated for this specific tool. Ideally, this tool should be located here:

https://tools.cornerstonejs.org/examples/tools/zoom-mouse-wheel.html

This should more or less do the trick:

```js
cornerstoneTools.addTool(cornerstoneTools.StackScrollMouseWheelTool)
cornerstoneTools.setToolActive('StackScrollMouseWheel', { })
```

**Comment by gkgkska** [comment]
what I've been working with zoom-mouse-wheel tool, and it's been already implement by our app. 
I can see any StackScroll api on cornerstoneTools, is it new feature you will be update?

**Comment by gkgkska** [comment]
Thank you for your prompt repose. please let me know what is different between stackScrollMouseWheelTool and zoomMouseWheel?

**Comment by swederik** [comment]
The first one scrolls images in the stack. The second one zooms into a single image.

**Comment by dannyrb** [comment]
Closing. If you've managed to figure things out @gkgkska, please consider adding a minimal example to our collection of examples so that others may benefit.
