### ISSUE TITLE
yalc publish for OHIF Viewer

### ISSUE THREAD

**Issue by MathisGuilhin** [cornerstonejs/cornerstoneTools#988]
Hello, 

I'm using cornerstoneTools with OHIFViewer to add a segmentation tool and the possibility to save the ROI formed. As I did with ohif-core to add modifications, I forked and clone this repo and I went into it to run : 

* yarn install
* yalc publish

I have no problem with the install, but for the publishment, instead of just grabbing the file and put them in a local folder, it runs a lot of test and I get errors as you can see on the picture.

![yalc_publish_cornerstoneTools](https://user-images.githubusercontent.com/45480583/60262596-ceba7a80-98de-11e9-9db5-6ae0d83ed1e1.PNG)

Do you have any idea of what is happening, and why that won't work?

Many thanks in advance

**Comment by dannyrb** [comment]
To maintain a consistent look and feel, we enforce [eslint](https://eslint.org/) and [prettier](https://prettier.io/) rules (as warnings or errors). These boil down to things you would normally consider preferences:

- No `console.log()` use
- Wrap code longer than 80 characters per line
- Prefer single quotes over double quotes for strings
- etc.

These checks run when we try to publish as a last catch to make sure we've caught as much as we reasonably can before cutting a new version and merging the code into the `master` branch.

You should be able to run `npm run lint` to autofix issues that the tooling is capable of automatically fixing on your behalf. Other issues, you will need to track down and change yourself. Most rules, like `valid-jsdoc` can be found by googling: [`eslint valid-jsdoc`](https://eslint.org/docs/rules/valid-jsdoc) if you need help understanding how to fix manually.

Only rules that result in an `error` need to be addressed before you can publish.
