### ISSUE TITLE
When can orientation Markers Tools be used in version 3.x

### ISSUE THREAD

**Issue by chenxxcc** [cornerstonejs/cornerstoneTools#993]
Because of the cornerstone. resize () method, we upgraded the version to 3.x, but unfortunately orientationMarkersTools disappeared.

**Comment by dannyrb** [comment]
@chenxxcc, I responded to a previous issue you created here: https://github.com/cornerstonejs/cornerstoneTools/issues/967

We are more than happy to accept and review a PR to add orientation markers, but to the best of my knowledge, it is not on any core team member's roadmap to add this functionality in the near future. If you need immediate assistance, I recommend reaching out to a consultant.
