### ISSUE TITLE
Reference line implementation, getting ImagIds and Stack

### ISSUE THREAD

**Issue by dimo2008** [cornerstonejs/cornerstoneTools#997]
i want to enable the reference line tool.
my problem is with getting the image Ids of the current element.
and how to implement the corresponding promises ?
this is how i implemented it:

        const element1 = this._seriesElement.get(0).children[0].children[0];
        const element2 = this._seriesElement.get(0).children[1].children[0];

        cornerstoneTools.init();
        cornerstone.enable(element1);
        cornerstone.enable(element2);

        //////first stack implementation??
        //////second stack implementation??

        // Create the synchronizer
        const synchronizer = new cornerstoneTools.Synchronizer(
          // Cornerstone event that should trigger synchronizer
          'cornerstonenewimage',
          // Logic that should run on target elements when event is observed on source elements
          cornerstoneTools.updateImageSynchronizer
        )
    
        cornerstoneTools.addTool(cornerstoneTools.StackScrollTool);
        cornerstoneTools.addTool(cornerstoneTools.StackScrollMouseWheelTool);
        cornerstoneTools.setToolActive('StackScroll', { mouseButtonMask: 1 });
        cornerstoneTools.setToolActive('StackScrollMouseWheel', {});

        ///////firstLoadImagePromise implementation  ??
        ///////secondLoadImageProm iseimplementation ??

        // After images have loaded, and our sync context has added both elements
        Promise.all([firstLoadImagePromise, secondLoadImagePromise])
          .then(() => {
              cornerstoneTools.addTool(cornerstoneTools.ReferenceLinesTool);
              cornerstoneTools.setToolEnabled('ReferenceLines', {
                  synchronizationContext: synchronizer,
              });
          });

**Comment by dannyrb** [comment]
You should know the image Ids because you set them when setting the stack's state:

https://tools.cornerstonejs.org/examples/tools/stack-scroll-mouse-wheel.html

`cornerstone.loadImage(imageId)` returns a promise

**Comment by dimo2008** [comment]
i managed to get the imageIds by other means as i made a specific helper for each tool.
now the reference line is drawn correctly but series are not synced with scroll
![1](https://user-images.githubusercontent.com/20152012/61643704-b2261e00-aca3-11e9-892f-1cc4fcf194ef.PNG)
, actually no series can be scrolled it just stay in the same frame .
( i am using a view port of 4 series shown at once

**Comment by dimo2008** [comment]
@dannyrb ?

**Comment by dannyrb** [comment]
This issue feels separate from your first. It should probably be a new GitHub issue. Also, in general, please try to include what you have tried, what you think the issue may be, and code snippets or a minimal reproduction.

Core functionality like this should be well documented. If it's not, call out where you would expect to see it documented or if the current steps are outdated/have issues.
