### ISSUE TITLE
vNext - moveEndHandler will trigger that when i click the enabled element, but it is not the same with 2.4.x

### ISSUE THREAD

**Issue by xingbofeng** [cornerstonejs/cornerstoneTools#998]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce
( In vNext )
1. Active LengthTool
2. Click the enabled element
3. there is a new measurement with 0 px length and i can't continue to draw the measurement

(In 2.4.x)

1. Active LengthTool
2. Click the enabled element
3. there is a new measurement
4. move on the element
5. Click the other area, then i can draw a new measurement

**Expected behavior:** [What you expected to happen]

same as 2.4.x

**Comment by xingbofeng** [comment]
In 2.4.x, 

https://github.com/cornerstonejs/cornerstoneTools/blob/cb606085b80b72160e6ad48899f62be995d92272/src/manipulators/moveNewHandle.js#L33-L44

when i add the new measurement, moveNewHandle will be called , and the `moveEndCallback` listener will be added after the `MOUSE_MOVE` event trigger:

But in vNext.

https://github.com/cornerstonejs/cornerstoneTools/blob/cc6ba5e14c79f16172da5f7c7be139ee03845cf7/src/manipulators/moveNewHandle.js#L89-L91

the `moveEndCallback` listener will be added just at moveNewHandle called:

**Comment by xingbofeng** [comment]
@dannyrb If you think it's necessary to keep the same behavior between vNext and v2.4.x, i will create a Pull Request.

**Comment by dannyrb** [comment]
@xingbofeng I think `v2.4.x` is exhibiting the preferred behavior. You'll likely notice the same issue with any tools that have multiple handles.

**Comment by xingbofeng** [comment]
I created the #1008 PR. Thanks @dannyrb
